/* Generated by the Nim Compiler v0.17.1 */
/*   (c) 2017 Andreas Rumpf */

var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;
var NTI70026 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI34062 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI34063 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI55524 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI55520 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI55121 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI55487 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI55486 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI55484 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI55482 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI55466 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI55002 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI55476 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI55468 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI25383 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25379 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25375 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25371 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25367 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25363 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25359 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25355 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25351 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25347 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25343 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25339 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25335 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25331 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25327 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25323 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25319 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25315 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25311 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25307 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI25204 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI25258 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI25218 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI25431 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI25429 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI25427 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI25222 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI25220 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI70022 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI70024 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI25260 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI55458 = {size: 0,kind: 16,base: null,node: null,finalizer: null};
var NTI3454 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI55452 = {size: 0,kind: 16,base: null,node: null,finalizer: null};
var NTI3446 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI104 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI13409 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI3408 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI138 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI140 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI3487 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI3424 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI3438 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI3442 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI74019 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI74015 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NNI3442 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI3442.node = NNI3442;
var NNI3438 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI3438.node = NNI3438;
NTI3487.base = NTI3424;
var NNI3424 = {kind: 2, len: 4, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI3487, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI140, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI138, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI138, name: "trace", sons: null}]};
NTI3424.node = NNI3424;
var NNI3408 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI3408.node = NNI3408;
NTI3424.base = NTI3408;
NTI3438.base = NTI3424;
NTI3442.base = NTI3438;
var NNI13409 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI140, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI104, name: "Field1", sons: null}]};
NTI13409.node = NNI13409;
var NNI3446 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI3446.node = NNI3446;
NTI3446.base = NTI3424;
NTI55452.base = NTI140;
var NNI3454 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI3454.node = NNI3454;
NTI3454.base = NTI3424;
NTI55458.base = NTI140;
var NNI25260 = {kind: 2, len: 91, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "background", len: 0, typ: NTI140, name: "background", sons: null}, 
{kind: 1, offset: "backgroundAttachment", len: 0, typ: NTI140, name: "backgroundAttachment", sons: null}, 
{kind: 1, offset: "backgroundColor", len: 0, typ: NTI140, name: "backgroundColor", sons: null}, 
{kind: 1, offset: "backgroundImage", len: 0, typ: NTI140, name: "backgroundImage", sons: null}, 
{kind: 1, offset: "backgroundPosition", len: 0, typ: NTI140, name: "backgroundPosition", sons: null}, 
{kind: 1, offset: "backgroundRepeat", len: 0, typ: NTI140, name: "backgroundRepeat", sons: null}, 
{kind: 1, offset: "border", len: 0, typ: NTI140, name: "border", sons: null}, 
{kind: 1, offset: "borderBottom", len: 0, typ: NTI140, name: "borderBottom", sons: null}, 
{kind: 1, offset: "borderBottomColor", len: 0, typ: NTI140, name: "borderBottomColor", sons: null}, 
{kind: 1, offset: "borderBottomStyle", len: 0, typ: NTI140, name: "borderBottomStyle", sons: null}, 
{kind: 1, offset: "borderBottomWidth", len: 0, typ: NTI140, name: "borderBottomWidth", sons: null}, 
{kind: 1, offset: "borderColor", len: 0, typ: NTI140, name: "borderColor", sons: null}, 
{kind: 1, offset: "borderLeft", len: 0, typ: NTI140, name: "borderLeft", sons: null}, 
{kind: 1, offset: "borderLeftColor", len: 0, typ: NTI140, name: "borderLeftColor", sons: null}, 
{kind: 1, offset: "borderLeftStyle", len: 0, typ: NTI140, name: "borderLeftStyle", sons: null}, 
{kind: 1, offset: "borderLeftWidth", len: 0, typ: NTI140, name: "borderLeftWidth", sons: null}, 
{kind: 1, offset: "borderRight", len: 0, typ: NTI140, name: "borderRight", sons: null}, 
{kind: 1, offset: "borderRightColor", len: 0, typ: NTI140, name: "borderRightColor", sons: null}, 
{kind: 1, offset: "borderRightStyle", len: 0, typ: NTI140, name: "borderRightStyle", sons: null}, 
{kind: 1, offset: "borderRightWidth", len: 0, typ: NTI140, name: "borderRightWidth", sons: null}, 
{kind: 1, offset: "borderStyle", len: 0, typ: NTI140, name: "borderStyle", sons: null}, 
{kind: 1, offset: "borderTop", len: 0, typ: NTI140, name: "borderTop", sons: null}, 
{kind: 1, offset: "borderTopColor", len: 0, typ: NTI140, name: "borderTopColor", sons: null}, 
{kind: 1, offset: "borderTopStyle", len: 0, typ: NTI140, name: "borderTopStyle", sons: null}, 
{kind: 1, offset: "borderTopWidth", len: 0, typ: NTI140, name: "borderTopWidth", sons: null}, 
{kind: 1, offset: "borderWidth", len: 0, typ: NTI140, name: "borderWidth", sons: null}, 
{kind: 1, offset: "bottom", len: 0, typ: NTI140, name: "bottom", sons: null}, 
{kind: 1, offset: "captionSide", len: 0, typ: NTI140, name: "captionSide", sons: null}, 
{kind: 1, offset: "clear", len: 0, typ: NTI140, name: "clear", sons: null}, 
{kind: 1, offset: "clip", len: 0, typ: NTI140, name: "clip", sons: null}, 
{kind: 1, offset: "color", len: 0, typ: NTI140, name: "color", sons: null}, 
{kind: 1, offset: "cursor", len: 0, typ: NTI140, name: "cursor", sons: null}, 
{kind: 1, offset: "direction", len: 0, typ: NTI140, name: "direction", sons: null}, 
{kind: 1, offset: "display", len: 0, typ: NTI140, name: "display", sons: null}, 
{kind: 1, offset: "emptyCells", len: 0, typ: NTI140, name: "emptyCells", sons: null}, 
{kind: 1, offset: "cssFloat", len: 0, typ: NTI140, name: "cssFloat", sons: null}, 
{kind: 1, offset: "font", len: 0, typ: NTI140, name: "font", sons: null}, 
{kind: 1, offset: "fontFamily", len: 0, typ: NTI140, name: "fontFamily", sons: null}, 
{kind: 1, offset: "fontSize", len: 0, typ: NTI140, name: "fontSize", sons: null}, 
{kind: 1, offset: "fontStretch", len: 0, typ: NTI140, name: "fontStretch", sons: null}, 
{kind: 1, offset: "fontStyle", len: 0, typ: NTI140, name: "fontStyle", sons: null}, 
{kind: 1, offset: "fontVariant", len: 0, typ: NTI140, name: "fontVariant", sons: null}, 
{kind: 1, offset: "fontWeight", len: 0, typ: NTI140, name: "fontWeight", sons: null}, 
{kind: 1, offset: "height", len: 0, typ: NTI140, name: "height", sons: null}, 
{kind: 1, offset: "left", len: 0, typ: NTI140, name: "left", sons: null}, 
{kind: 1, offset: "letterSpacing", len: 0, typ: NTI140, name: "letterSpacing", sons: null}, 
{kind: 1, offset: "lineHeight", len: 0, typ: NTI140, name: "lineHeight", sons: null}, 
{kind: 1, offset: "listStyle", len: 0, typ: NTI140, name: "listStyle", sons: null}, 
{kind: 1, offset: "listStyleImage", len: 0, typ: NTI140, name: "listStyleImage", sons: null}, 
{kind: 1, offset: "listStylePosition", len: 0, typ: NTI140, name: "listStylePosition", sons: null}, 
{kind: 1, offset: "listStyleType", len: 0, typ: NTI140, name: "listStyleType", sons: null}, 
{kind: 1, offset: "margin", len: 0, typ: NTI140, name: "margin", sons: null}, 
{kind: 1, offset: "marginBottom", len: 0, typ: NTI140, name: "marginBottom", sons: null}, 
{kind: 1, offset: "marginLeft", len: 0, typ: NTI140, name: "marginLeft", sons: null}, 
{kind: 1, offset: "marginRight", len: 0, typ: NTI140, name: "marginRight", sons: null}, 
{kind: 1, offset: "marginTop", len: 0, typ: NTI140, name: "marginTop", sons: null}, 
{kind: 1, offset: "maxHeight", len: 0, typ: NTI140, name: "maxHeight", sons: null}, 
{kind: 1, offset: "maxWidth", len: 0, typ: NTI140, name: "maxWidth", sons: null}, 
{kind: 1, offset: "minHeight", len: 0, typ: NTI140, name: "minHeight", sons: null}, 
{kind: 1, offset: "minWidth", len: 0, typ: NTI140, name: "minWidth", sons: null}, 
{kind: 1, offset: "overflow", len: 0, typ: NTI140, name: "overflow", sons: null}, 
{kind: 1, offset: "padding", len: 0, typ: NTI140, name: "padding", sons: null}, 
{kind: 1, offset: "paddingBottom", len: 0, typ: NTI140, name: "paddingBottom", sons: null}, 
{kind: 1, offset: "paddingLeft", len: 0, typ: NTI140, name: "paddingLeft", sons: null}, 
{kind: 1, offset: "paddingRight", len: 0, typ: NTI140, name: "paddingRight", sons: null}, 
{kind: 1, offset: "paddingTop", len: 0, typ: NTI140, name: "paddingTop", sons: null}, 
{kind: 1, offset: "pageBreakAfter", len: 0, typ: NTI140, name: "pageBreakAfter", sons: null}, 
{kind: 1, offset: "pageBreakBefore", len: 0, typ: NTI140, name: "pageBreakBefore", sons: null}, 
{kind: 1, offset: "pointerEvents", len: 0, typ: NTI140, name: "pointerEvents", sons: null}, 
{kind: 1, offset: "position", len: 0, typ: NTI140, name: "position", sons: null}, 
{kind: 1, offset: "right", len: 0, typ: NTI140, name: "right", sons: null}, 
{kind: 1, offset: "scrollbar3dLightColor", len: 0, typ: NTI140, name: "scrollbar3dLightColor", sons: null}, 
{kind: 1, offset: "scrollbarArrowColor", len: 0, typ: NTI140, name: "scrollbarArrowColor", sons: null}, 
{kind: 1, offset: "scrollbarBaseColor", len: 0, typ: NTI140, name: "scrollbarBaseColor", sons: null}, 
{kind: 1, offset: "scrollbarDarkshadowColor", len: 0, typ: NTI140, name: "scrollbarDarkshadowColor", sons: null}, 
{kind: 1, offset: "scrollbarFaceColor", len: 0, typ: NTI140, name: "scrollbarFaceColor", sons: null}, 
{kind: 1, offset: "scrollbarHighlightColor", len: 0, typ: NTI140, name: "scrollbarHighlightColor", sons: null}, 
{kind: 1, offset: "scrollbarShadowColor", len: 0, typ: NTI140, name: "scrollbarShadowColor", sons: null}, 
{kind: 1, offset: "scrollbarTrackColor", len: 0, typ: NTI140, name: "scrollbarTrackColor", sons: null}, 
{kind: 1, offset: "tableLayout", len: 0, typ: NTI140, name: "tableLayout", sons: null}, 
{kind: 1, offset: "textAlign", len: 0, typ: NTI140, name: "textAlign", sons: null}, 
{kind: 1, offset: "textDecoration", len: 0, typ: NTI140, name: "textDecoration", sons: null}, 
{kind: 1, offset: "textIndent", len: 0, typ: NTI140, name: "textIndent", sons: null}, 
{kind: 1, offset: "textTransform", len: 0, typ: NTI140, name: "textTransform", sons: null}, 
{kind: 1, offset: "transform", len: 0, typ: NTI140, name: "transform", sons: null}, 
{kind: 1, offset: "top", len: 0, typ: NTI140, name: "top", sons: null}, 
{kind: 1, offset: "verticalAlign", len: 0, typ: NTI140, name: "verticalAlign", sons: null}, 
{kind: 1, offset: "visibility", len: 0, typ: NTI140, name: "visibility", sons: null}, 
{kind: 1, offset: "width", len: 0, typ: NTI140, name: "width", sons: null}, 
{kind: 1, offset: "wordSpacing", len: 0, typ: NTI140, name: "wordSpacing", sons: null}, 
{kind: 1, offset: "zIndex", len: 0, typ: NTI104, name: "zIndex", sons: null}]};
NTI25260.node = NNI25260;
NTI25260.base = NTI3408;
var NNI70022 = {kind: 2, offset: 0, typ: null, name: null, len: 5, sons: {"0": {kind: 1, offset: 0, typ: NTI70022, name: "pkReplace", len: 0, sons: null}, 
"1": {kind: 1, offset: 1, typ: NTI70022, name: "pkRemove", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI70022, name: "pkAppend", len: 0, sons: null}, 
"3": {kind: 1, offset: 3, typ: NTI70022, name: "pkInsertBefore", len: 0, sons: null}, 
"4": {kind: 1, offset: 4, typ: NTI70022, name: "pkDetach", len: 0, sons: null}}};
NTI70022.node = NNI70022;
NTI25427.base = NTI25220;
NTI25429.base = NTI25220;
NTI25431.base = NTI25220;
var NNI25218 = {kind: 2, offset: 0, typ: null, name: null, len: 12, sons: {"1": {kind: 1, offset: 1, typ: NTI25218, name: "ElementNode", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI25218, name: "AttributeNode", len: 0, sons: null}, 
"3": {kind: 1, offset: 3, typ: NTI25218, name: "TextNode", len: 0, sons: null}, 
"4": {kind: 1, offset: 4, typ: NTI25218, name: "CDATANode", len: 0, sons: null}, 
"5": {kind: 1, offset: 5, typ: NTI25218, name: "EntityRefNode", len: 0, sons: null}, 
"6": {kind: 1, offset: 6, typ: NTI25218, name: "EntityNode", len: 0, sons: null}, 
"7": {kind: 1, offset: 7, typ: NTI25218, name: "ProcessingInstructionNode", len: 0, sons: null}, 
"8": {kind: 1, offset: 8, typ: NTI25218, name: "CommentNode", len: 0, sons: null}, 
"9": {kind: 1, offset: 9, typ: NTI25218, name: "DocumentNode", len: 0, sons: null}, 
"10": {kind: 1, offset: 10, typ: NTI25218, name: "DocumentTypeNode", len: 0, sons: null}, 
"11": {kind: 1, offset: 11, typ: NTI25218, name: "DocumentFragmentNode", len: 0, sons: null}, 
"12": {kind: 1, offset: 12, typ: NTI25218, name: "NotationNode", len: 0, sons: null}}};
NTI25218.node = NNI25218;
NTI25258.base = NTI25260;
var NNI25222 = {kind: 2, len: 14, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "attributes", len: 0, typ: NTI25427, name: "attributes", sons: null}, 
{kind: 1, offset: "childNodes", len: 0, typ: NTI25429, name: "childNodes", sons: null}, 
{kind: 1, offset: "children", len: 0, typ: NTI25431, name: "children", sons: null}, 
{kind: 1, offset: "data", len: 0, typ: NTI140, name: "data", sons: null}, 
{kind: 1, offset: "firstChild", len: 0, typ: NTI25220, name: "firstChild", sons: null}, 
{kind: 1, offset: "lastChild", len: 0, typ: NTI25220, name: "lastChild", sons: null}, 
{kind: 1, offset: "nextSibling", len: 0, typ: NTI25220, name: "nextSibling", sons: null}, 
{kind: 1, offset: "nodeName", len: 0, typ: NTI140, name: "nodeName", sons: null}, 
{kind: 1, offset: "nodeType", len: 0, typ: NTI25218, name: "nodeType", sons: null}, 
{kind: 1, offset: "nodeValue", len: 0, typ: NTI140, name: "nodeValue", sons: null}, 
{kind: 1, offset: "parentNode", len: 0, typ: NTI25220, name: "parentNode", sons: null}, 
{kind: 1, offset: "previousSibling", len: 0, typ: NTI25220, name: "previousSibling", sons: null}, 
{kind: 1, offset: "innerHTML", len: 0, typ: NTI140, name: "innerHTML", sons: null}, 
{kind: 1, offset: "style", len: 0, typ: NTI25258, name: "style", sons: null}]};
NTI25222.node = NNI25222;
var NNI25204 = {kind: 2, len: 20, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "onabort", len: 0, typ: NTI25307, name: "onabort", sons: null}, 
{kind: 1, offset: "onblur", len: 0, typ: NTI25311, name: "onblur", sons: null}, 
{kind: 1, offset: "onchange", len: 0, typ: NTI25315, name: "onchange", sons: null}, 
{kind: 1, offset: "onclick", len: 0, typ: NTI25319, name: "onclick", sons: null}, 
{kind: 1, offset: "ondblclick", len: 0, typ: NTI25323, name: "ondblclick", sons: null}, 
{kind: 1, offset: "onerror", len: 0, typ: NTI25327, name: "onerror", sons: null}, 
{kind: 1, offset: "onfocus", len: 0, typ: NTI25331, name: "onfocus", sons: null}, 
{kind: 1, offset: "onkeydown", len: 0, typ: NTI25335, name: "onkeydown", sons: null}, 
{kind: 1, offset: "onkeypress", len: 0, typ: NTI25339, name: "onkeypress", sons: null}, 
{kind: 1, offset: "onkeyup", len: 0, typ: NTI25343, name: "onkeyup", sons: null}, 
{kind: 1, offset: "onload", len: 0, typ: NTI25347, name: "onload", sons: null}, 
{kind: 1, offset: "onmousedown", len: 0, typ: NTI25351, name: "onmousedown", sons: null}, 
{kind: 1, offset: "onmousemove", len: 0, typ: NTI25355, name: "onmousemove", sons: null}, 
{kind: 1, offset: "onmouseout", len: 0, typ: NTI25359, name: "onmouseout", sons: null}, 
{kind: 1, offset: "onmouseover", len: 0, typ: NTI25363, name: "onmouseover", sons: null}, 
{kind: 1, offset: "onmouseup", len: 0, typ: NTI25367, name: "onmouseup", sons: null}, 
{kind: 1, offset: "onreset", len: 0, typ: NTI25371, name: "onreset", sons: null}, 
{kind: 1, offset: "onselect", len: 0, typ: NTI25375, name: "onselect", sons: null}, 
{kind: 1, offset: "onsubmit", len: 0, typ: NTI25379, name: "onsubmit", sons: null}, 
{kind: 1, offset: "onunload", len: 0, typ: NTI25383, name: "onunload", sons: null}]};
NTI25204.node = NNI25204;
NTI25204.base = NTI3408;
NTI25222.base = NTI25204;
NTI25220.base = NTI25222;
var NNI55002 = {kind: 2, offset: 0, typ: null, name: null, len: 117, sons: {"0": {kind: 1, offset: 0, typ: NTI55002, name: "#text", len: 0, sons: null}, 
"1": {kind: 1, offset: 1, typ: NTI55002, name: "#int", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI55002, name: "#bool", len: 0, sons: null}, 
"3": {kind: 1, offset: 3, typ: NTI55002, name: "#vthunk", len: 0, sons: null}, 
"4": {kind: 1, offset: 4, typ: NTI55002, name: "#dthunk", len: 0, sons: null}, 
"5": {kind: 1, offset: 5, typ: NTI55002, name: "#component", len: 0, sons: null}, 
"6": {kind: 1, offset: 6, typ: NTI55002, name: "html", len: 0, sons: null}, 
"7": {kind: 1, offset: 7, typ: NTI55002, name: "head", len: 0, sons: null}, 
"8": {kind: 1, offset: 8, typ: NTI55002, name: "title", len: 0, sons: null}, 
"9": {kind: 1, offset: 9, typ: NTI55002, name: "base", len: 0, sons: null}, 
"10": {kind: 1, offset: 10, typ: NTI55002, name: "link", len: 0, sons: null}, 
"11": {kind: 1, offset: 11, typ: NTI55002, name: "meta", len: 0, sons: null}, 
"12": {kind: 1, offset: 12, typ: NTI55002, name: "style", len: 0, sons: null}, 
"13": {kind: 1, offset: 13, typ: NTI55002, name: "script", len: 0, sons: null}, 
"14": {kind: 1, offset: 14, typ: NTI55002, name: "noscript", len: 0, sons: null}, 
"15": {kind: 1, offset: 15, typ: NTI55002, name: "body", len: 0, sons: null}, 
"16": {kind: 1, offset: 16, typ: NTI55002, name: "section", len: 0, sons: null}, 
"17": {kind: 1, offset: 17, typ: NTI55002, name: "nav", len: 0, sons: null}, 
"18": {kind: 1, offset: 18, typ: NTI55002, name: "article", len: 0, sons: null}, 
"19": {kind: 1, offset: 19, typ: NTI55002, name: "aside", len: 0, sons: null}, 
"20": {kind: 1, offset: 20, typ: NTI55002, name: "h1", len: 0, sons: null}, 
"21": {kind: 1, offset: 21, typ: NTI55002, name: "h2", len: 0, sons: null}, 
"22": {kind: 1, offset: 22, typ: NTI55002, name: "h3", len: 0, sons: null}, 
"23": {kind: 1, offset: 23, typ: NTI55002, name: "h4", len: 0, sons: null}, 
"24": {kind: 1, offset: 24, typ: NTI55002, name: "h5", len: 0, sons: null}, 
"25": {kind: 1, offset: 25, typ: NTI55002, name: "h6", len: 0, sons: null}, 
"26": {kind: 1, offset: 26, typ: NTI55002, name: "header", len: 0, sons: null}, 
"27": {kind: 1, offset: 27, typ: NTI55002, name: "footer", len: 0, sons: null}, 
"28": {kind: 1, offset: 28, typ: NTI55002, name: "address", len: 0, sons: null}, 
"29": {kind: 1, offset: 29, typ: NTI55002, name: "main", len: 0, sons: null}, 
"30": {kind: 1, offset: 30, typ: NTI55002, name: "p", len: 0, sons: null}, 
"31": {kind: 1, offset: 31, typ: NTI55002, name: "hr", len: 0, sons: null}, 
"32": {kind: 1, offset: 32, typ: NTI55002, name: "pre", len: 0, sons: null}, 
"33": {kind: 1, offset: 33, typ: NTI55002, name: "blockquote", len: 0, sons: null}, 
"34": {kind: 1, offset: 34, typ: NTI55002, name: "ol", len: 0, sons: null}, 
"35": {kind: 1, offset: 35, typ: NTI55002, name: "ul", len: 0, sons: null}, 
"36": {kind: 1, offset: 36, typ: NTI55002, name: "li", len: 0, sons: null}, 
"37": {kind: 1, offset: 37, typ: NTI55002, name: "dl", len: 0, sons: null}, 
"38": {kind: 1, offset: 38, typ: NTI55002, name: "dt", len: 0, sons: null}, 
"39": {kind: 1, offset: 39, typ: NTI55002, name: "dd", len: 0, sons: null}, 
"40": {kind: 1, offset: 40, typ: NTI55002, name: "figure", len: 0, sons: null}, 
"41": {kind: 1, offset: 41, typ: NTI55002, name: "figcaption", len: 0, sons: null}, 
"42": {kind: 1, offset: 42, typ: NTI55002, name: "div", len: 0, sons: null}, 
"43": {kind: 1, offset: 43, typ: NTI55002, name: "a", len: 0, sons: null}, 
"44": {kind: 1, offset: 44, typ: NTI55002, name: "em", len: 0, sons: null}, 
"45": {kind: 1, offset: 45, typ: NTI55002, name: "strong", len: 0, sons: null}, 
"46": {kind: 1, offset: 46, typ: NTI55002, name: "small", len: 0, sons: null}, 
"47": {kind: 1, offset: 47, typ: NTI55002, name: "s", len: 0, sons: null}, 
"48": {kind: 1, offset: 48, typ: NTI55002, name: "cite", len: 0, sons: null}, 
"49": {kind: 1, offset: 49, typ: NTI55002, name: "quote", len: 0, sons: null}, 
"50": {kind: 1, offset: 50, typ: NTI55002, name: "dfn", len: 0, sons: null}, 
"51": {kind: 1, offset: 51, typ: NTI55002, name: "abbr", len: 0, sons: null}, 
"52": {kind: 1, offset: 52, typ: NTI55002, name: "data", len: 0, sons: null}, 
"53": {kind: 1, offset: 53, typ: NTI55002, name: "time", len: 0, sons: null}, 
"54": {kind: 1, offset: 54, typ: NTI55002, name: "code", len: 0, sons: null}, 
"55": {kind: 1, offset: 55, typ: NTI55002, name: "var", len: 0, sons: null}, 
"56": {kind: 1, offset: 56, typ: NTI55002, name: "samp", len: 0, sons: null}, 
"57": {kind: 1, offset: 57, typ: NTI55002, name: "kdb", len: 0, sons: null}, 
"58": {kind: 1, offset: 58, typ: NTI55002, name: "sub", len: 0, sons: null}, 
"59": {kind: 1, offset: 59, typ: NTI55002, name: "sup", len: 0, sons: null}, 
"60": {kind: 1, offset: 60, typ: NTI55002, name: "i", len: 0, sons: null}, 
"61": {kind: 1, offset: 61, typ: NTI55002, name: "b", len: 0, sons: null}, 
"62": {kind: 1, offset: 62, typ: NTI55002, name: "u", len: 0, sons: null}, 
"63": {kind: 1, offset: 63, typ: NTI55002, name: "mark", len: 0, sons: null}, 
"64": {kind: 1, offset: 64, typ: NTI55002, name: "ruby", len: 0, sons: null}, 
"65": {kind: 1, offset: 65, typ: NTI55002, name: "rt", len: 0, sons: null}, 
"66": {kind: 1, offset: 66, typ: NTI55002, name: "rp", len: 0, sons: null}, 
"67": {kind: 1, offset: 67, typ: NTI55002, name: "bdi", len: 0, sons: null}, 
"68": {kind: 1, offset: 68, typ: NTI55002, name: "dbo", len: 0, sons: null}, 
"69": {kind: 1, offset: 69, typ: NTI55002, name: "span", len: 0, sons: null}, 
"70": {kind: 1, offset: 70, typ: NTI55002, name: "br", len: 0, sons: null}, 
"71": {kind: 1, offset: 71, typ: NTI55002, name: "wbr", len: 0, sons: null}, 
"72": {kind: 1, offset: 72, typ: NTI55002, name: "ins", len: 0, sons: null}, 
"73": {kind: 1, offset: 73, typ: NTI55002, name: "del", len: 0, sons: null}, 
"74": {kind: 1, offset: 74, typ: NTI55002, name: "img", len: 0, sons: null}, 
"75": {kind: 1, offset: 75, typ: NTI55002, name: "iframe", len: 0, sons: null}, 
"76": {kind: 1, offset: 76, typ: NTI55002, name: "embed", len: 0, sons: null}, 
"77": {kind: 1, offset: 77, typ: NTI55002, name: "object", len: 0, sons: null}, 
"78": {kind: 1, offset: 78, typ: NTI55002, name: "param", len: 0, sons: null}, 
"79": {kind: 1, offset: 79, typ: NTI55002, name: "video", len: 0, sons: null}, 
"80": {kind: 1, offset: 80, typ: NTI55002, name: "audio", len: 0, sons: null}, 
"81": {kind: 1, offset: 81, typ: NTI55002, name: "source", len: 0, sons: null}, 
"82": {kind: 1, offset: 82, typ: NTI55002, name: "track", len: 0, sons: null}, 
"83": {kind: 1, offset: 83, typ: NTI55002, name: "canvas", len: 0, sons: null}, 
"84": {kind: 1, offset: 84, typ: NTI55002, name: "map", len: 0, sons: null}, 
"85": {kind: 1, offset: 85, typ: NTI55002, name: "area", len: 0, sons: null}, 
"86": {kind: 1, offset: 86, typ: NTI55002, name: "svg", len: 0, sons: null}, 
"87": {kind: 1, offset: 87, typ: NTI55002, name: "math", len: 0, sons: null}, 
"88": {kind: 1, offset: 88, typ: NTI55002, name: "table", len: 0, sons: null}, 
"89": {kind: 1, offset: 89, typ: NTI55002, name: "caption", len: 0, sons: null}, 
"90": {kind: 1, offset: 90, typ: NTI55002, name: "colgroup", len: 0, sons: null}, 
"91": {kind: 1, offset: 91, typ: NTI55002, name: "col", len: 0, sons: null}, 
"92": {kind: 1, offset: 92, typ: NTI55002, name: "tbody", len: 0, sons: null}, 
"93": {kind: 1, offset: 93, typ: NTI55002, name: "thead", len: 0, sons: null}, 
"94": {kind: 1, offset: 94, typ: NTI55002, name: "tfoot", len: 0, sons: null}, 
"95": {kind: 1, offset: 95, typ: NTI55002, name: "tr", len: 0, sons: null}, 
"96": {kind: 1, offset: 96, typ: NTI55002, name: "td", len: 0, sons: null}, 
"97": {kind: 1, offset: 97, typ: NTI55002, name: "th", len: 0, sons: null}, 
"98": {kind: 1, offset: 98, typ: NTI55002, name: "form", len: 0, sons: null}, 
"99": {kind: 1, offset: 99, typ: NTI55002, name: "fieldset", len: 0, sons: null}, 
"100": {kind: 1, offset: 100, typ: NTI55002, name: "legend", len: 0, sons: null}, 
"101": {kind: 1, offset: 101, typ: NTI55002, name: "label", len: 0, sons: null}, 
"102": {kind: 1, offset: 102, typ: NTI55002, name: "input", len: 0, sons: null}, 
"103": {kind: 1, offset: 103, typ: NTI55002, name: "button", len: 0, sons: null}, 
"104": {kind: 1, offset: 104, typ: NTI55002, name: "select", len: 0, sons: null}, 
"105": {kind: 1, offset: 105, typ: NTI55002, name: "datalist", len: 0, sons: null}, 
"106": {kind: 1, offset: 106, typ: NTI55002, name: "optgroup", len: 0, sons: null}, 
"107": {kind: 1, offset: 107, typ: NTI55002, name: "option", len: 0, sons: null}, 
"108": {kind: 1, offset: 108, typ: NTI55002, name: "textarea", len: 0, sons: null}, 
"109": {kind: 1, offset: 109, typ: NTI55002, name: "keygen", len: 0, sons: null}, 
"110": {kind: 1, offset: 110, typ: NTI55002, name: "output", len: 0, sons: null}, 
"111": {kind: 1, offset: 111, typ: NTI55002, name: "progress", len: 0, sons: null}, 
"112": {kind: 1, offset: 112, typ: NTI55002, name: "meter", len: 0, sons: null}, 
"113": {kind: 1, offset: 113, typ: NTI55002, name: "details", len: 0, sons: null}, 
"114": {kind: 1, offset: 114, typ: NTI55002, name: "summary", len: 0, sons: null}, 
"115": {kind: 1, offset: 115, typ: NTI55002, name: "command", len: 0, sons: null}, 
"116": {kind: 1, offset: 116, typ: NTI55002, name: "menu", len: 0, sons: null}}};
NTI55002.node = NNI55002;
NTI55482.base = NTI55468;
NTI55484.base = NTI140;
var NNI55121 = {kind: 2, offset: 0, typ: null, name: null, len: 28, sons: {"0": {kind: 1, offset: 0, typ: NTI55121, name: "onclick", len: 0, sons: null}, 
"1": {kind: 1, offset: 1, typ: NTI55121, name: "oncontextmenu", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI55121, name: "ondblclick", len: 0, sons: null}, 
"3": {kind: 1, offset: 3, typ: NTI55121, name: "onkeyup", len: 0, sons: null}, 
"4": {kind: 1, offset: 4, typ: NTI55121, name: "onkeydown", len: 0, sons: null}, 
"5": {kind: 1, offset: 5, typ: NTI55121, name: "onkeypressed", len: 0, sons: null}, 
"6": {kind: 1, offset: 6, typ: NTI55121, name: "onfocus", len: 0, sons: null}, 
"7": {kind: 1, offset: 7, typ: NTI55121, name: "onblur", len: 0, sons: null}, 
"8": {kind: 1, offset: 8, typ: NTI55121, name: "onchange", len: 0, sons: null}, 
"9": {kind: 1, offset: 9, typ: NTI55121, name: "onscroll", len: 0, sons: null}, 
"10": {kind: 1, offset: 10, typ: NTI55121, name: "onmousedown", len: 0, sons: null}, 
"11": {kind: 1, offset: 11, typ: NTI55121, name: "onmouseenter", len: 0, sons: null}, 
"12": {kind: 1, offset: 12, typ: NTI55121, name: "onmouseleave", len: 0, sons: null}, 
"13": {kind: 1, offset: 13, typ: NTI55121, name: "onmousemove", len: 0, sons: null}, 
"14": {kind: 1, offset: 14, typ: NTI55121, name: "onmouseout", len: 0, sons: null}, 
"15": {kind: 1, offset: 15, typ: NTI55121, name: "onmouseover", len: 0, sons: null}, 
"16": {kind: 1, offset: 16, typ: NTI55121, name: "onmouseup", len: 0, sons: null}, 
"17": {kind: 1, offset: 17, typ: NTI55121, name: "ondrag", len: 0, sons: null}, 
"18": {kind: 1, offset: 18, typ: NTI55121, name: "ondragend", len: 0, sons: null}, 
"19": {kind: 1, offset: 19, typ: NTI55121, name: "ondragenter", len: 0, sons: null}, 
"20": {kind: 1, offset: 20, typ: NTI55121, name: "ondragleave", len: 0, sons: null}, 
"21": {kind: 1, offset: 21, typ: NTI55121, name: "ondragover", len: 0, sons: null}, 
"22": {kind: 1, offset: 22, typ: NTI55121, name: "ondragstart", len: 0, sons: null}, 
"23": {kind: 1, offset: 23, typ: NTI55121, name: "ondrop", len: 0, sons: null}, 
"24": {kind: 1, offset: 24, typ: NTI55121, name: "onsubmit", len: 0, sons: null}, 
"25": {kind: 1, offset: 25, typ: NTI55121, name: "oninput", len: 0, sons: null}, 
"26": {kind: 1, offset: 26, typ: NTI55121, name: "onkeyupenter", len: 0, sons: null}, 
"27": {kind: 1, offset: 27, typ: NTI55121, name: "onkeyuplater", len: 0, sons: null}}};
NTI55121.node = NNI55121;
var NNI55487 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI55121, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI55520, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI55524, name: "Field2", sons: null}]};
NTI55487.node = NNI55487;
NTI55486.base = NTI55487;
var NNI34062 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI34062.node = NNI34062;
NTI34063.base = NTI34062;
var NNI55476 = {kind: 2, len: 10, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "kind", len: 0, typ: NTI55002, name: "kind", sons: null}, 
{kind: 1, offset: "key", len: 0, typ: NTI55466, name: "key", sons: null}, 
{kind: 1, offset: "id", len: 0, typ: NTI140, name: "id", sons: null}, 
{kind: 1, offset: "class", len: 0, typ: NTI140, name: "class", sons: null}, 
{kind: 1, offset: "text", len: 0, typ: NTI140, name: "text", sons: null}, 
{kind: 1, offset: "kids", len: 0, typ: NTI55482, name: "kids", sons: null}, 
{kind: 1, offset: "attrs", len: 0, typ: NTI55484, name: "attrs", sons: null}, 
{kind: 1, offset: "events", len: 0, typ: NTI55486, name: "events", sons: null}, 
{kind: 1, offset: "style", len: 0, typ: NTI34063, name: "style", sons: null}, 
{kind: 1, offset: "dom", len: 0, typ: NTI25220, name: "dom", sons: null}]};
NTI55476.node = NNI55476;
NTI55476.base = NTI3408;
NTI55468.base = NTI55476;
var NNI70024 = {kind: 2, len: 4, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "k", len: 0, typ: NTI70022, name: "k", sons: null}, 
{kind: 1, offset: "parent", len: 0, typ: NTI25220, name: "parent", sons: null}, 
{kind: 1, offset: "current", len: 0, typ: NTI25220, name: "current", sons: null}, 
{kind: 1, offset: "n", len: 0, typ: NTI55468, name: "n", sons: null}]};
NTI70024.node = NNI70024;
var NNI70026 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI55468, name: "parent", sons: null}, 
{kind: 1, offset: "newChild", len: 0, typ: NTI55468, name: "newChild", sons: null}, 
{kind: 1, offset: "pos", len: 0, typ: NTI104, name: "pos", sons: null}]};
NTI70026.node = NNI70026;

function setConstr() {
		      var result = {};
      for (var i = 0; i < arguments.length; ++i) {
        var x = arguments[i];
        if (typeof(x) == "object") {
          for (var j = x[0]; j <= x[1]; ++j) {
            result[j] = true;
          }
        } else {
          result[x] = true;
        }
      }
      return result;
    

	
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_19617, src_19618, ti_19619) {
	var result_20029 = null;

		switch (ti_19619.kind) {
		case 21:
		case 22:
		case 23:
		case 5:
			if (!(isFatPointer_19601(ti_19619))) {
			result_20029 = src_19618;
			}
			else {
				result_20029 = [src_19618[0], src_19618[1]];
			}
			
			break;
		case 19:
			      if (dest_19617 === null || dest_19617 === undefined) {
        dest_19617 = {};
      }
      else {
        for (var key in dest_19617) { delete dest_19617[key]; }
      }
      for (var key in src_19618) { dest_19617[key] = src_19618[key]; }
      result_20029 = dest_19617;
    
			break;
		case 18:
		case 17:
			if (!((ti_19619.base == null))) {
			result_20029 = nimCopy(dest_19617, src_19618, ti_19619.base);
			}
			else {
			if ((ti_19619.kind == 17)) {
			result_20029 = (dest_19617 === null || dest_19617 === undefined) ? {m_type: ti_19619} : dest_19617;
			}
			else {
				result_20029 = (dest_19617 === null || dest_19617 === undefined) ? {} : dest_19617;
			}
			}
			nimCopyAux(result_20029, src_19618, ti_19619.node);
			break;
		case 24:
		case 4:
		case 27:
		case 16:
			      if (src_19618 === null) {
        result_20029 = null;
      }
      else {
        if (dest_19617 === null || dest_19617 === undefined) {
          dest_19617 = new Array(src_19618.length);
        }
        else {
          dest_19617.length = src_19618.length;
        }
        result_20029 = dest_19617;
        for (var i = 0; i < src_19618.length; ++i) {
          result_20029[i] = nimCopy(result_20029[i], src_19618[i], ti_19619.base);
        }
      }
    
			break;
		case 28:
			      if (src_19618 !== null) {
        result_20029 = src_19618.slice(0);
      }
    
			break;
		default: 
			result_20029 = src_19618;
			break;
		}

	return result_20029;

}

function makeNimstrLit(c_14403) {
		    var ln = c_14403.length;
    var result = new Array(ln + 1);
    var i = 0;
    for (; i < ln; ++i) {
      result[i] = c_14403.charCodeAt(i);
    }
    result[i] = 0; // terminating zero
    return result;
    

	
}

function eqStrings(a_17003, b_17004) {
		    if (a_17003 == b_17004) return true;
    if ((!a_17003) || (!b_17004)) return false;
    var alen = a_17003.length;
    if (alen != b_17004.length) return false;
    for (var i = 0; i < alen; ++i)
      if (a_17003[i] != b_17004[i]) return false;
    return true;
  

	
}

function arrayConstr(len_20064, value_20065, typ_20066) {
		      var result = new Array(len_20064);
      for (var i = 0; i < len_20064; ++i) result[i] = nimCopy(null, value_20065, typ_20066);
      return result;
    

	
}

function cstrToNimstr(c_14603) {
		  var ln = c_14603.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_14603.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else if((ch > 127) && (ch < 2048)) {
      result[r] = (ch >> 6) | 192;
      ++r;
      result[r] = (ch & 63) | 128;
    }
    else {
      result[r] = (ch >> 12) | 224;
      ++r;
      result[r] = ((ch >> 6) & 63) | 128;
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  result[r] = 0; // terminating zero
  return result;
  

	
}

function toJSStr(s_14803) {
		    var len = s_14803.length-1;
    var asciiPart = new Array(len);
    var fcc = String.fromCharCode;
    var nonAsciiPart = null;
    var nonAsciiOffset = 0;
    for (var i = 0; i < len; ++i) {
      if (nonAsciiPart !== null) {
        var offset = (i - nonAsciiOffset) * 2;
        var code = s_14803[i].toString(16);
        if (code.length == 1) {
          code = "0"+code;
        }
        nonAsciiPart[offset] = "%";
        nonAsciiPart[offset + 1] = code;
      }
      else if (s_14803[i] < 128)
        asciiPart[i] = fcc(s_14803[i]);
      else {
        asciiPart.length = i;
        nonAsciiOffset = i;
        nonAsciiPart = new Array((len - i) * 2);
        --i;
      }
    }
    asciiPart = asciiPart.join("");
    return (nonAsciiPart === null) ?
        asciiPart : asciiPart + decodeURIComponent(nonAsciiPart.join(""));
  

	
}

function raiseException(e_13806, ename_13807) {
		e_13806.name = ename_13807;
		if ((excHandler == 0)) {
		unhandledException(e_13806);
		}
		
		e_13806.trace = nimCopy(null, rawWriteStackTrace_13628(), NTI138);
		throw e_13806;

	
}

function addInt(a_17203, b_17204) {
		      var result = a_17203 + b_17204;
      if (result > 2147483647 || result < -2147483648) raiseOverflow();
      return result;
    

	
}
			var toTag_55449 = nimCopy(null, ["#text", "#int", "#bool", "#vthunk", "#dthunk", "#component", "HTML", "HEAD", "TITLE", "BASE", "LINK", "META", "STYLE", "SCRIPT", "NOSCRIPT", "BODY", "SECTION", "NAV", "ARTICLE", "ASIDE", "H1", "H2", "H3", "H4", "H5", "H6", "HEADER", "FOOTER", "ADDRESS", "MAIN", "P", "HR", "PRE", "BLOCKQUOTE", "OL", "UL", "LI", "DL", "DT", "DD", "FIGURE", "FIGCAPTION", "DIV", "A", "EM", "STRONG", "SMALL", "S", "CITE", "QUOTE", "DFN", "ABBR", "DATA", "TIME", "CODE", "VAR", "SAMP", "KDB", "SUB", "SUP", "I", "B", "U", "MARK", "RUBY", "RT", "RP", "BDI", "DBO", "SPAN", "BR", "WBR", "INS", "DEL", "IMG", "IFRAME", "EMBED", "OBJECT", "PARAM", "VIDEO", "AUDIO", "SOURCE", "TRACK", "CANVAS", "MAP", "AREA", "SVG", "MATH", "TABLE", "CAPTION", "COLGROUP", "COL", "TBODY", "THEAD", "TFOOT", "TR", "TD", "TH", "FORM", "FIELDSET", "LEGEND", "LABEL", "INPUT", "BUTTON", "SELECT", "DATALIST", "OPTGROUP", "OPTION", "TEXTAREA", "KEYGEN", "OUTPUT", "PROGRESS", "METER", "DETAILS", "SUMMARY", "COMMAND", "MENU"], NTI55452);

function chckIndx(i_20203, a_20204, b_20205) {
			var Tmp1;

	var result_20206 = 0;

	BeforeRet: do {
			if (!(a_20204 <= i_20203)) Tmp1 = false; else {				Tmp1 = (i_20203 <= b_20205);			}		if (Tmp1) {
		result_20206 = i_20203;
		break BeforeRet;
		}
		else {
		raiseIndexError();
		}
		
	} while (false);

	return result_20206;

}

function subInt(a_17403, b_17404) {
		      var result = a_17403 - b_17404;
      if (result > 2147483647 || result < -2147483648) raiseOverflow();
      return result;
    

	
}
			var toEventName_55455 = nimCopy(null, ["click", "contextmenu", "dblclick", "keyup", "keydown", "keypressed", "focus", "blur", "change", "scroll", "mousedown", "mouseenter", "mouseleave", "mousemove", "mouseout", "mouseover", "mouseup", "drag", "dragend", "dragenter", "dragleave", "dragover", "dragstart", "drop", "submit", "input", "keyupenter", "keyuplater"], NTI55458);

function nimMin(a_19239, b_19240) {
		var Tmp1;

	var result_19241 = 0;

	BeforeRet: do {
		if ((a_19239 <= b_19240)) {
		Tmp1 = a_19239;
		}
		else {
		Tmp1 = b_19240;
		}
		
		result_19241 = Tmp1;
		break BeforeRet;
	} while (false);

	return result_19241;

}
var nimvm_5887 = false;
var nim_program_result = 0;
var globalRaiseHook_11405 = [null];
var localRaiseHook_11410 = [null];
var outOfMemHook_11413 = [null];
var gid_55694 = [0];
var objectID_57232 = [0];
var vcomponents_64014 = [{}];
var dcomponents_64028 = [{}];
var kxi_70083 = [null];

function isFatPointer_19601(ti_19603) {
	var result_19604 = false;

	BeforeRet: do {
		result_19604 = !((ConstSet1[ti_19603.base.kind] != undefined));
		break BeforeRet;
	} while (false);

	return result_19604;

}

function nimCopyAux(dest_19622, src_19623, n_19625) {
		switch (n_19625.kind) {
		case 0:
			break;
		case 1:
			      dest_19622[n_19625.offset] = nimCopy(dest_19622[n_19625.offset], src_19623[n_19625.offset], n_19625.typ);
    
			break;
		case 2:
			L1: do {
				var i_20015 = 0;
				var colontmp__20017 = 0;
				colontmp__20017 = (n_19625.len - 1);
				var res_20020 = 0;
				L2: do {
						L3: while (true) {
						if (!(res_20020 <= colontmp__20017)) break L3;
							i_20015 = res_20020;
							nimCopyAux(dest_19622, src_19623, n_19625.sons[i_20015]);
							res_20020 += 1;
						}
				} while(false);
			} while(false);
			break;
		case 3:
			      dest_19622[n_19625.offset] = nimCopy(dest_19622[n_19625.offset], src_19623[n_19625.offset], n_19625.typ);
      for (var i = 0; i < n_19625.sons.length; ++i) {
        nimCopyAux(dest_19622, src_19623, n_19625.sons[i][1]);
      }
    
			break;
		}

	
}

function newSeq_74037(len_74041) {
	var result_74043 = null;

	var F={procname:"newSeq.newSeq",prev:framePtr,filename:"lib/system.nim",line:0};
	framePtr = F;
		F.line = 696;
		result_74043 = new Array(len_74041); for (var i=0;i<len_74041;++i) {result_74043[i]={k: 0, parent: null, current: null, n: null};}	framePtr = F.prev;

	return result_74043;

}

function newSeq_74076(len_74080) {
	var result_74082 = null;

	var F={procname:"newSeq.newSeq",prev:framePtr,filename:"lib/system.nim",line:0};
	framePtr = F;
		F.line = 696;
		result_74082 = new Array(len_74080); for (var i=0;i<len_74080;++i) {result_74082[i]={parent: null, newChild: null, pos: 0};}	framePtr = F.prev;

	return result_74082;

}

function add_11429(x_11432, x_11432_Idx, y_11433) {
		        var len = x_11432[0].length-1;
        for (var i = 0; i < y_11433.length; ++i) {
          x_11432[0][len] = y_11433.charCodeAt(i);
          ++len;
        }
        x_11432[0][len] = 0
      

	
}

function auxWriteStackTrace_13404(f_13406) {
					var Tmp3;

	var result_13407 = [null];

		var it_13415 = f_13406;
		var i_13416 = 0;
		var total_13417 = 0;
		var tempFrames_13421 = arrayConstr(64, {Field0: null, Field1: 0}, NTI13409);
		L1: do {
				L2: while (true) {
					if (!!((it_13415 == null))) Tmp3 = false; else {						Tmp3 = (i_13416 <= 63);					}				if (!Tmp3) break L2;
					tempFrames_13421[i_13416].Field0 = it_13415.procname;
					tempFrames_13421[i_13416].Field1 = it_13415.line;
					i_13416 += 1;
					total_13417 += 1;
					it_13415 = it_13415.prev;
				}
		} while(false);
		L4: do {
				L5: while (true) {
				if (!!((it_13415 == null))) break L5;
					total_13417 += 1;
					it_13415 = it_13415.prev;
				}
		} while(false);
		result_13407[0] = nimCopy(null, makeNimstrLit(""), NTI138);
		if (!((total_13417 == i_13416))) {
		if (result_13407[0] != null) { result_13407[0] = (result_13407[0].slice(0, -1)).concat(makeNimstrLit("(")); } else { result_13407[0] = makeNimstrLit("(");};
		if (result_13407[0] != null) { result_13407[0] = (result_13407[0].slice(0, -1)).concat(cstrToNimstr(((total_13417 - i_13416))+"")); } else { result_13407[0] = cstrToNimstr(((total_13417 - i_13416))+"");};
		if (result_13407[0] != null) { result_13407[0] = (result_13407[0].slice(0, -1)).concat(makeNimstrLit(" calls omitted) ...\x0A")); } else { result_13407[0] = makeNimstrLit(" calls omitted) ...\x0A");};
		}
		
		L6: do {
			var j_13615 = 0;
			var colontmp__13621 = 0;
			colontmp__13621 = (i_13416 - 1);
			var res_13624 = colontmp__13621;
			L7: do {
					L8: while (true) {
					if (!(0 <= res_13624)) break L8;
						j_13615 = res_13624;
						add_11429(result_13407, 0, tempFrames_13421[j_13615].Field0);
						if ((0 < tempFrames_13421[j_13615].Field1)) {
						if (result_13407[0] != null) { result_13407[0] = (result_13407[0].slice(0, -1)).concat(makeNimstrLit(", line: ")); } else { result_13407[0] = makeNimstrLit(", line: ");};
						if (result_13407[0] != null) { result_13407[0] = (result_13407[0].slice(0, -1)).concat(cstrToNimstr((tempFrames_13421[j_13615].Field1)+"")); } else { result_13407[0] = cstrToNimstr((tempFrames_13421[j_13615].Field1)+"");};
						}
						
						if (result_13407[0] != null) { result_13407[0] = (result_13407[0].slice(0, -1)).concat(makeNimstrLit("\x0A")); } else { result_13407[0] = makeNimstrLit("\x0A");};
						res_13624 -= 1;
					}
			} while(false);
		} while(false);

	return result_13407[0];

}

function rawWriteStackTrace_13628() {
	var result_13630 = null;

		if (!((framePtr == null))) {
		result_13630 = nimCopy(null, (makeNimstrLit("Traceback (most recent call last)\x0A").slice(0,-1)).concat(auxWriteStackTrace_13404(framePtr)), NTI138);
		}
		else {
			result_13630 = nimCopy(null, makeNimstrLit("No stack traceback available\x0A"), NTI138);
		}
		

	return result_13630;

}

function unhandledException(e_13653) {
			var Tmp1;

		var buf_13654 = [makeNimstrLit("")];
			if (!!(eqStrings(e_13653.message, null))) Tmp1 = false; else {				Tmp1 = !((e_13653.message[0] == 0));			}		if (Tmp1) {
		if (buf_13654[0] != null) { buf_13654[0] = (buf_13654[0].slice(0, -1)).concat(makeNimstrLit("Error: unhandled exception: ")); } else { buf_13654[0] = makeNimstrLit("Error: unhandled exception: ");};
		if (buf_13654[0] != null) { buf_13654[0] = (buf_13654[0].slice(0, -1)).concat(e_13653.message); } else { buf_13654[0] = e_13653.message;};
		}
		else {
		if (buf_13654[0] != null) { buf_13654[0] = (buf_13654[0].slice(0, -1)).concat(makeNimstrLit("Error: unhandled exception")); } else { buf_13654[0] = makeNimstrLit("Error: unhandled exception");};
		}
		
		if (buf_13654[0] != null) { buf_13654[0] = (buf_13654[0].slice(0, -1)).concat(makeNimstrLit(" [")); } else { buf_13654[0] = makeNimstrLit(" [");};
		add_11429(buf_13654, 0, e_13653.name);
		if (buf_13654[0] != null) { buf_13654[0] = (buf_13654[0].slice(0, -1)).concat(makeNimstrLit("]\x0A")); } else { buf_13654[0] = makeNimstrLit("]\x0A");};
		if (buf_13654[0] != null) { buf_13654[0] = (buf_13654[0].slice(0, -1)).concat(rawWriteStackTrace_13628()); } else { buf_13654[0] = rawWriteStackTrace_13628();};
		var cbuf_13801 = toJSStr(buf_13654[0]);
		framePtr = null;
		  if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_13801);
  }
  else {
    throw cbuf_13801;
  }
  

	
}

function raiseOverflow() {
		var e_14240 = null;
		e_14240 = {m_type: NTI3442, parent: null, name: null, message: null, trace: null};
		e_14240.message = nimCopy(null, makeNimstrLit("over- or underflow"), NTI138);
		e_14240.parent = null;
		raiseException(e_14240, "OverflowError");

	
}

function sysFatal_22221(message_22227) {
	var F={procname:"sysFatal.sysFatal",prev:framePtr,filename:"lib/system.nim",line:0};
	framePtr = F;
		F.line = 2703;
		var e_22229 = null;
		F.line = 2704;
		e_22229 = {m_type: NTI3446, parent: null, name: null, message: null, trace: null};
		F.line = 2705;
		e_22229.message = nimCopy(null, message_22227, NTI138);
		F.line = 2706;
		raiseException(e_22229, "AssertionError");
	framePtr = F.prev;

	
}

function raiseAssert_22216(msg_22218) {
	var F={procname:"system.raiseAssert",prev:framePtr,filename:"lib/system.nim",line:0};
	framePtr = F;
		F.line = 3586;
		sysFatal_22221(msg_22218);
	framePtr = F.prev;

	
}

function failedAssertImpl_22239(msg_22241) {
	var F={procname:"system.failedAssertImpl",prev:framePtr,filename:"lib/system.nim",line:0};
	framePtr = F;
		F.line = 3594;
		raiseAssert_22216(msg_22241);
	framePtr = F.prev;

	
}

function raiseIndexError() {
		var e_14294 = null;
		e_14294 = {m_type: NTI3454, parent: null, name: null, message: null, trace: null};
		e_14294.message = nimCopy(null, makeNimstrLit("index out of bounds"), NTI138);
		e_14294.parent = null;
		raiseException(e_14294, "IndexError");

	
}

function valueeq__55575(n_55577, v_55578) {
	var F={procname:"vdom.value=",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
		F.line = 141;
		n_55577.text = v_55578;
	framePtr = F.prev;

	
}

function value_55571(n_55573) {
	var result_55574 = null;

	var F={procname:"vdom.value",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
		F.line = 140;
		result_55574 = n_55573.text;
	framePtr = F.prev;

	return result_55574;

}

function wrapEvent_70111(d_70113, n_70114, k_70115, action_70116) {

			function laterWrapper_70165() {

					function colonanonymous__70171(ev_70173) {

							function wrapper_70174() {
								var F={procname:":anonymous.wrapper",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
								framePtr = F;
									F.line = 65;
									var v_70179 = ev_70173.target.value;
									F.line = 66;
									valueeq__55575(n_70169, v_70179);
									F.line = 67;
									action_70168(ev_70173, n_70169);
									if (!((value_55571(n_70169) == v_70179))) {
									F.line = 69;
									ev_70173.target.value = value_55571(n_70169);
									}
									
								framePtr = F.prev;

								
							}

						var F={procname:"laterWrapper.:anonymous",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
						framePtr = F;
							if (!((timer_70170 == null))) {
							F.line = 95;
							clearTimeout(timer_70170);
							}
							
							F.line = 96;
							timer_70170 = setTimeout(wrapper_70174, 400);
						framePtr = F.prev;

						
					}

				var result_70167 = null;

				var F={procname:"wrapEvent.laterWrapper",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
				framePtr = F;
					F.line = 90;
					var action_70168 = action_70116;
					F.line = 91;
					var n_70169 = n_70114;
					F.line = 92;
					var timer_70170 = null;
					F.line = 93;
					result_70167 = colonanonymous__70171;
				framePtr = F.prev;

				return result_70167;

			}

			function enterWrapper_70150() {

					function colonanonymous__70155(ev_70157) {
						var F={procname:"enterWrapper.:anonymous",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
						framePtr = F;
							if ((ev_70157.keyCode == 13)) {
							F.line = 65;
							var v_70162 = ev_70157.target.value;
							F.line = 66;
							valueeq__55575(n_70154, v_70162);
							F.line = 67;
							action_70153(ev_70157, n_70154);
							if (!((value_55571(n_70154) == v_70162))) {
							F.line = 69;
							ev_70157.target.value = value_55571(n_70154);
							}
							
							}
							
						framePtr = F.prev;

						
					}

				var result_70152 = null;

				var F={procname:"wrapEvent.enterWrapper",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
				framePtr = F;
					F.line = 84;
					var action_70153 = action_70116;
					F.line = 85;
					var n_70154 = n_70114;
					F.line = 86;
					result_70152 = colonanonymous__70155;
				framePtr = F.prev;

				return result_70152;

			}

			function stdWrapper_70118() {

					function colonanonymous__70123(ev_70125) {
								var Tmp1;

						var F={procname:"stdWrapper.:anonymous",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
						framePtr = F;
								if ((n_70122.kind == 108)) Tmp1 = true; else {									Tmp1 = (n_70122.kind == 102);								}							if (Tmp1) {
							F.line = 65;
							var v_70147 = ev_70125.target.value;
							F.line = 66;
							valueeq__55575(n_70122, v_70147);
							F.line = 67;
							action_70121(ev_70125, n_70122);
							if (!((value_55571(n_70122) == v_70147))) {
							F.line = 69;
							ev_70125.target.value = value_55571(n_70122);
							}
							
							}
							else {
								F.line = 81;
							action_70121(ev_70125, n_70122);
							}
							
						framePtr = F.prev;

						
					}

				var result_70120 = null;

				var F={procname:"wrapEvent.stdWrapper",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
				framePtr = F;
					F.line = 76;
					var action_70121 = action_70116;
					F.line = 77;
					var n_70122 = n_70114;
					F.line = 78;
					result_70120 = colonanonymous__70123;
				framePtr = F.prev;

				return result_70120;

			}

	var result_70117 = null;

	var F={procname:"karax.wrapEvent",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		F.line = 98;
		switch (k_70115) {
		case 27:
			F.line = 100;
			result_70117 = laterWrapper_70165();
			F.line = 101;
			d_70113.addEventListener("keyup", result_70117, false);
			break;
		case 26:
			F.line = 103;
			result_70117 = enterWrapper_70150();
			F.line = 104;
			d_70113.addEventListener("keyup", result_70117, false);
			break;
		default: 
			F.line = 106;
			result_70117 = stdWrapper_70118();
			F.line = 107;
			d_70113.addEventListener(toEventName_55455[chckIndx(k_70115, 0, toEventName_55455.length-1)-0], result_70117, false);
			break;
		}
	framePtr = F.prev;

	return result_70117;

}

function applyEvents_70205(n_70207, kxi_70208) {
	var F={procname:"karax.applyEvents",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		F.line = 118;
		var dest_70209 = n_70207.dom;
		L1: do {
			F.line = 119;
			var i_70226 = 0;
			F.line = 3812;
			var colontmp__70228 = 0;
			F.line = 119;
			colontmp__70228 = (n_70207.events != null ? n_70207.events.length : 0);
			F.line = 3813;
			var i_70231 = 0;
			L2: do {
				F.line = 3814;
					L3: while (true) {
					if (!(i_70231 < colontmp__70228)) break L3;
						F.line = 3815;
						i_70226 = i_70231;
						F.line = 120;
						n_70207.events[chckIndx(i_70226, 0, n_70207.events.length-1)-0]["Field2"] = wrapEvent_70111(dest_70209, n_70207, n_70207.events[chckIndx(i_70226, 0, n_70207.events.length-1)-0]["Field0"], n_70207.events[chckIndx(i_70226, 0, n_70207.events.length-1)-0]["Field1"]);
						F.line = 3816;
						i_70231 = addInt(i_70231, 1);
					}
			} while(false);
		} while(false);
	framePtr = F.prev;

	
}

function applyStyle_36308(n_36310, s_36311) {
	var F={procname:"vstyles.applyStyle",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vstyles.nim",line:0};
	framePtr = F;
		F.line = 290;
		n_36310.style = {};
		L1: do {
			F.line = 291;
			var i_36347 = 0;
			F.line = 1965;
			var colontmp__36381 = 0;
			F.line = 291;
			colontmp__36381 = subInt(s_36311.length, 1);
			F.line = 1955;
			var res_36384 = 0;
			L2: do {
				F.line = 1956;
					L3: while (true) {
					if (!(res_36384 <= colontmp__36381)) break L3;
						F.line = 1957;
						i_36347 = res_36384;
						F.line = 292;
						n_36310.style[s_36311[i_36347]] = s_36311[addInt(i_36347, 1)];
						F.line = 1971;
						res_36384 = addInt(res_36384, 2);
					}
			} while(false);
		} while(false);
	framePtr = F.prev;

	
}

function vnodeToDom_70234(n_70236, kxi_70237) {
			var Tmp9;

	var result_70238 = null;

	var F={procname:"karax.vnodeToDom",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if ((n_70236.kind == 0)) {
		F.line = 124;
		result_70238 = document.createTextNode(n_70236.text);
		F.line = 125;
		n_70236.dom = result_70238;
		}
		else {
		if ((n_70236.kind == 3)) {
		F.line = 127;
		var x_70274 = vcomponents_64014[0][n_70236.text](n_70236.kids);
		F.line = 128;
		result_70238 = vnodeToDom_70234(x_70274, kxi_70237);
		F.line = 130;
		n_70236.dom = result_70238;
		F.line = 131;
		break BeforeRet;
		}
		else {
		if ((n_70236.kind == 4)) {
		F.line = 133;
		result_70238 = dcomponents_64028[0][n_70236.text](n_70236.kids);
		F.line = 135;
		n_70236.dom = result_70238;
		F.line = 136;
		break BeforeRet;
		}
		else {
		if ((n_70236.kind == 5)) {
		F.line = 138;
		var x_70310 = n_70236;
		if (!((x_70310.onAttachImpl == null))) {
		F.line = 139;
		x_70310.onAttachImpl(x_70310);
		}
		
		if (!(!((x_70310.renderImpl == null)))) {
		F.line = 140;
		failedAssertImpl_22239(makeNimstrLit("\x0A  not (x.renderImpl == nil) "));
		}
		
		if ((x_70310.expanded == null)) {
		F.line = 142;
		x_70310.expanded = x_70310.renderImpl(x_70310);
		}
		
		if (!(!((x_70310.expanded == null)))) {
		F.line = 144;
		failedAssertImpl_22239(makeNimstrLit("\x0A  not (x.expanded == nil) "));
		}
		
		F.line = 145;
		result_70238 = vnodeToDom_70234(x_70310.expanded, kxi_70237);
		F.line = 146;
		n_70236.dom = result_70238;
		F.line = 147;
		break BeforeRet;
		}
		else {
			F.line = 149;
			result_70238 = document.createElement(toTag_55449[chckIndx(n_70236.kind, 0, toTag_55449.length-1)-0]);
			F.line = 150;
			n_70236.dom = result_70238;
			L1: do {
				F.line = 151;
				var k_70601 = null;
				L2: do {
					F.line = 221;
					var i_70632 = 0;
					F.line = 3812;
					var colontmp__70634 = 0;
					F.line = 221;
					colontmp__70634 = (n_70236.kids != null ? n_70236.kids.length : 0);
					F.line = 3813;
					var i_70636 = 0;
					L3: do {
						F.line = 3814;
							L4: while (true) {
							if (!(i_70636 < colontmp__70634)) break L4;
								F.line = 3815;
								i_70632 = i_70636;
								F.line = 221;
								k_70601 = n_70236.kids[chckIndx(i_70632, 0, n_70236.kids.length-1)-0];
								F.line = 152;
								result_70238.appendChild(vnodeToDom_70234(k_70601, kxi_70237));
								F.line = 3816;
								i_70636 = addInt(i_70636, 1);
							}
					} while(false);
				} while(false);
			} while(false);
			if (!((n_70236.text == null))) {
			F.line = 155;
			result_70238.value = n_70236.text;
			}
			
		}
		}}}
		if (!((n_70236.id == null))) {
		F.line = 157;
		result_70238.id = n_70236.id;
		}
		
		if (!((n_70236.class == null))) {
		F.line = 159;
		result_70238.className = n_70236.class;
		}
		
		L5: do {
			F.line = 162;
			var k_70602 = null;
			F.line = 162;
			var v_70603 = null;
			L6: do {
				F.line = 224;
				var i_70641 = 0;
				F.line = 1965;
				var colontmp__70643 = 0;
				F.line = 224;
				colontmp__70643 = subInt((n_70236.attrs != null ? n_70236.attrs.length : 0), 2);
				F.line = 1955;
				var res_70645 = 0;
				L7: do {
					F.line = 1956;
						L8: while (true) {
						if (!(res_70645 <= colontmp__70643)) break L8;
							F.line = 1957;
							i_70641 = res_70645;
							F.line = 225;
							k_70602 = n_70236.attrs[chckIndx(i_70641, 0, n_70236.attrs.length-1)-0];
							F.line = 225;
							v_70603 = n_70236.attrs[chckIndx(addInt(i_70641, 1), 0, n_70236.attrs.length-1)-0];
							if (!((v_70603 == null))) {
							F.line = 164;
							result_70238.setAttribute(k_70602, v_70603);
							}
							
							F.line = 1971;
							res_70645 = addInt(res_70645, 2);
						}
				} while(false);
			} while(false);
		} while(false);
		F.line = 165;
		applyEvents_70205(n_70236, kxi_70237);
			if (!(n_70236 == kxi_70237.toFocusV)) Tmp9 = false; else {				Tmp9 = (kxi_70237.toFocus === null);			}		if (Tmp9) {
		F.line = 167;
		kxi_70237.toFocus = result_70238;
		}
		
		if (!((n_70236.style === null))) {
		F.line = 168;
		applyStyle_36308(result_70238, n_70236.style);
		}
		
	} while (false);
	framePtr = F.prev;

	return result_70238;

}

function replaceById_70720(id_70722, newTree_70723) {
	var F={procname:"karax.replaceById",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		F.line = 188;
		var x_70724 = document.getElementById(id_70722);
		F.line = 189;
		x_70724.parentNode.replaceChild(newTree_70723, x_70724);
	framePtr = F.prev;

	
}

function len_55849(x_55851) {
	var result_55852 = 0;

	var F={procname:"vdom.len",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
		F.line = 202;
		result_55852 = (x_55851.kids != null ? x_55851.kids.length : 0);
	framePtr = F.prev;

	return result_55852;

}

function X5BX5D__55860(x_55862, idx_55863) {
	var result_55864 = null;

	var F={procname:"vdom.[]",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
		F.line = 203;
		result_55864 = x_55862.kids[chckIndx(idx_55863, 0, x_55862.kids.length-1)-0];
	framePtr = F.prev;

	return result_55864;

}

function same_70650(n_70652, e_70653, nesting_70654) {
			var Tmp1;

	var result_70655 = false;

	var F={procname:"karax.same",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if ((n_70652.kind == 5)) {
		F.line = 172;
		result_70655 = same_70650(n_70652.expanded, e_70653, addInt(nesting_70654, 1));
		}
		else {
			if ((n_70652.kind == 3)) Tmp1 = true; else {				Tmp1 = (n_70652.kind == 4);			}		if (Tmp1) {
		F.line = 175;
		result_70655 = true;
		}
		else {
		if ((toTag_55449[chckIndx(n_70652.kind, 0, toTag_55449.length-1)-0] == e_70653.nodeName)) {
		F.line = 177;
		result_70655 = true;
		if (!((n_70652.kind == 0))) {
		if (!((e_70653.childNodes.length == len_55849(n_70652)))) {
		F.line = 180;
		console.log(e_70653.childNodes.length, len_55849(n_70652), toTag_55449[chckIndx(n_70652.kind, 0, toTag_55449.length-1)-0], nesting_70654);
		F.line = 181;
		result_70655 = false;
		break BeforeRet;
		}
		
		L2: do {
			F.line = 182;
			var i_70707 = 0;
			F.line = 3812;
			var colontmp__70715 = 0;
			F.line = 182;
			colontmp__70715 = len_55849(n_70652);
			F.line = 3813;
			var i_70718 = 0;
			L3: do {
				F.line = 3814;
					L4: while (true) {
					if (!(i_70718 < colontmp__70715)) break L4;
						F.line = 3815;
						i_70707 = i_70718;
						if (!(same_70650(X5BX5D__55860(n_70652, i_70707), e_70653.childNodes[i_70707], addInt(nesting_70654, 1)))) {
						F.line = 183;
						result_70655 = false;
						break BeforeRet;
						}
						
						F.line = 3816;
						i_70718 = addInt(i_70718, 1);
					}
			} while(false);
		} while(false);
		}
		
		}
		else {
			F.line = 185;
		console.log(toTag_55449[chckIndx(n_70652.kind, 0, toTag_55449.length-1)-0], e_70653.nodeName);
		}
		}}
	} while (false);
	framePtr = F.prev;

	return result_70655;

}

function sameAttrs_56032(a_56034, b_56035) {
	var result_56036 = false;

	var F={procname:"vdom.sameAttrs",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if (((a_56034.attrs != null ? a_56034.attrs.length : 0) == (b_56035.attrs != null ? b_56035.attrs.length : 0))) {
		F.line = 229;
		result_56036 = true;
		L1: do {
			F.line = 230;
			var i_56067 = 0;
			F.line = 3812;
			var colontmp__56069 = 0;
			F.line = 230;
			colontmp__56069 = (a_56034.attrs != null ? a_56034.attrs.length : 0);
			F.line = 3813;
			var i_56072 = 0;
			L2: do {
				F.line = 3814;
					L3: while (true) {
					if (!(i_56072 < colontmp__56069)) break L3;
						F.line = 3815;
						i_56067 = i_56072;
						if (!((a_56034.attrs[chckIndx(i_56067, 0, a_56034.attrs.length-1)-0] == b_56035.attrs[chckIndx(i_56067, 0, b_56035.attrs.length-1)-0]))) {
						F.line = 231;
						result_56036 = false;
						break BeforeRet;
						}
						
						F.line = 3816;
						i_56072 = addInt(i_56072, 1);
					}
			} while(false);
		} while(false);
		}
		
	} while (false);
	framePtr = F.prev;

	return result_56036;

}

function eq_35451(a_35453, b_35454) {
	var result_35455 = false;

	var F={procname:"vstyles.eq",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vstyles.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if ((a_35453 === null)) {
		if ((b_35454 === null)) {
		F.line = 220;
		result_35455 = true;
		break BeforeRet;
		}
		else {
			F.line = 221;
			result_35455 = false;
			break BeforeRet;
		}
		
		}
		else {
		if ((b_35454 === null)) {
		F.line = 222;
		result_35455 = false;
		break BeforeRet;
		}
		}
		if (!((a_35453.length == b_35454.length))) {
		F.line = 223;
		result_35455 = false;
		break BeforeRet;
		}
		
		L1: do {
			F.line = 224;
			var i_35558 = 0;
			F.line = 3812;
			var colontmp__35592 = 0;
			F.line = 224;
			colontmp__35592 = a_35453.length;
			F.line = 3813;
			var i_35595 = 0;
			L2: do {
				F.line = 3814;
					L3: while (true) {
					if (!(i_35595 < colontmp__35592)) break L3;
						F.line = 3815;
						i_35558 = i_35595;
						if (!((a_35453[i_35558] == b_35454[i_35558]))) {
						F.line = 225;
						result_35455 = false;
						break BeforeRet;
						}
						
						F.line = 3816;
						i_35595 = addInt(i_35595, 1);
					}
			} while(false);
		} while(false);
		F.line = 226;
		result_35455 = true;
		break BeforeRet;
	} while (false);
	framePtr = F.prev;

	return result_35455;

}

function eq_70732(a_70734, b_70735) {
			var Tmp1;
		var Tmp5;

	var result_70736 = 0;

	var F={procname:"karax.eq",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if (!((a_70734.kind == b_70735.kind))) {
		F.line = 196;
		result_70736 = 1;
		break BeforeRet;
		}
		
		if (!((a_70734.id == b_70735.id))) {
		F.line = 197;
		result_70736 = 1;
		break BeforeRet;
		}
		
		F.line = 198;
		result_70736 = 3;
		if (!((a_70734.key == b_70735.key))) {
		F.line = 199;
		result_70736 = 1;
		break BeforeRet;
		}
		
		if ((a_70734.kind == 0)) {
		if (!((a_70734.text == b_70735.text))) {
		F.line = 201;
		result_70736 = 1;
		break BeforeRet;
		}
		
		}
		else {
			if ((a_70734.kind == 3)) Tmp1 = true; else {				Tmp1 = (a_70734.kind == 4);			}		if (Tmp1) {
		if (!((a_70734.text == b_70735.text))) {
		F.line = 203;
		result_70736 = 1;
		break BeforeRet;
		}
		
		if (!((len_55849(a_70734) == len_55849(b_70735)))) {
		F.line = 204;
		result_70736 = 1;
		break BeforeRet;
		}
		
		L2: do {
			F.line = 205;
			var i_70781 = 0;
			F.line = 3812;
			var colontmp__71002 = 0;
			F.line = 205;
			colontmp__71002 = len_55849(a_70734);
			F.line = 3813;
			var i_71005 = 0;
			L3: do {
				F.line = 3814;
					L4: while (true) {
					if (!(i_71005 < colontmp__71002)) break L4;
						F.line = 3815;
						i_70781 = i_71005;
						if ((eq_70732(X5BX5D__55860(a_70734, i_70781), X5BX5D__55860(b_70735, i_70781)) == 1)) {
						F.line = 206;
						result_70736 = 1;
						break BeforeRet;
						}
						
						F.line = 3816;
						i_71005 = addInt(i_71005, 1);
					}
			} while(false);
		} while(false);
		}
		else {
		if ((b_70735.kind == 5)) {
		if (!((a_70734.text == b_70735.text))) {
		F.line = 209;
		result_70736 = 1;
		break BeforeRet;
		}
		
		F.line = 210;
		var x_70799 = b_70735;
		if (!(!((x_70799.changedImpl == null)))) {
		F.line = 211;
		failedAssertImpl_22239(makeNimstrLit("\x0A  not (x.changedImpl == nil) "));
		}
		
		F.line = 212;
		if (x_70799.changedImpl(x_70799, a_70734)) {
		Tmp5 = 0;
		}
		else {
		Tmp5 = 3;
		}
		
		result_70736 = Tmp5;
		break BeforeRet;
		}
		}}
		if (!(sameAttrs_56032(a_70734, b_70735))) {
		F.line = 213;
		result_70736 = 1;
		break BeforeRet;
		}
		
		if (!((a_70734.class == b_70735.class))) {
		F.line = 214;
		result_70736 = 1;
		break BeforeRet;
		}
		
		if (!(eq_35451(a_70734.style, b_70735.style))) {
		F.line = 215;
		result_70736 = 2;
		break BeforeRet;
		}
		
		F.line = 217;
		break BeforeRet;
	} while (false);
	framePtr = F.prev;

	return result_70736;

}

function updateStyles_71008(newNode_71010, oldNode_71011) {
	var F={procname:"karax.updateStyles",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		if (!((oldNode_71011.dom == null))) {
		if (!((newNode_71010.style == null))) {
		F.line = 222;
		applyStyle_36308(oldNode_71011.dom, newNode_71010.style);
		}
		else {
			F.line = 223;
			oldNode_71011.dom.style = {m_type: NTI25260, background: null, backgroundAttachment: null, backgroundColor: null, backgroundImage: null, backgroundPosition: null, backgroundRepeat: null, border: null, borderBottom: null, borderBottomColor: null, borderBottomStyle: null, borderBottomWidth: null, borderColor: null, borderLeft: null, borderLeftColor: null, borderLeftStyle: null, borderLeftWidth: null, borderRight: null, borderRightColor: null, borderRightStyle: null, borderRightWidth: null, borderStyle: null, borderTop: null, borderTopColor: null, borderTopStyle: null, borderTopWidth: null, borderWidth: null, bottom: null, captionSide: null, clear: null, clip: null, color: null, cursor: null, direction: null, display: null, emptyCells: null, cssFloat: null, font: null, fontFamily: null, fontSize: null, fontStretch: null, fontStyle: null, fontVariant: null, fontWeight: null, height: null, left: null, letterSpacing: null, lineHeight: null, listStyle: null, listStyleImage: null, listStylePosition: null, listStyleType: null, margin: null, marginBottom: null, marginLeft: null, marginRight: null, marginTop: null, maxHeight: null, maxWidth: null, minHeight: null, minWidth: null, overflow: null, padding: null, paddingBottom: null, paddingLeft: null, paddingRight: null, paddingTop: null, pageBreakAfter: null, pageBreakBefore: null, pointerEvents: null, position: null, right: null, scrollbar3dLightColor: null, scrollbarArrowColor: null, scrollbarBaseColor: null, scrollbarDarkshadowColor: null, scrollbarFaceColor: null, scrollbarHighlightColor: null, scrollbarShadowColor: null, scrollbarTrackColor: null, tableLayout: null, textAlign: null, textDecoration: null, textIndent: null, textTransform: null, transform: null, top: null, verticalAlign: null, visibility: null, width: null, wordSpacing: null, zIndex: 0};
		}
		
		}
		
		F.line = 224;
		oldNode_71011.style = newNode_71010.style;
	framePtr = F.prev;

	
}

function mergeEvents_71035(newNode_71037, oldNode_71038, kxi_71039) {
						var Tmp4;

	var F={procname:"karax.mergeEvents",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		F.line = 227;
		var d_71040 = oldNode_71038.dom;
		L1: do {
			F.line = 228;
			var i_71057 = 0;
			F.line = 3812;
			var colontmp__71063 = 0;
			F.line = 228;
			colontmp__71063 = (oldNode_71038.events != null ? oldNode_71038.events.length : 0);
			F.line = 3813;
			var i_71066 = 0;
			L2: do {
				F.line = 3814;
					L3: while (true) {
					if (!(i_71066 < colontmp__71063)) break L3;
						F.line = 3815;
						i_71057 = i_71066;
						F.line = 229;
						var k_71058 = oldNode_71038.events[chckIndx(i_71057, 0, oldNode_71038.events.length-1)-0]["Field0"];
						F.line = 230;
						F.line = 230;
						switch (k_71058) {
						case 27:
						case 26:
							Tmp4 = "keyup";
							break;
						default: 
							Tmp4 = toEventName_55455[chckIndx(k_71058, 0, toEventName_55455.length-1)-0];
							break;
						}
						var name_71061 = Tmp4;
						F.line = 233;
						d_71040.removeEventListener(name_71061, oldNode_71038.events[chckIndx(i_71057, 0, oldNode_71038.events.length-1)-0]["Field2"]);
						F.line = 3816;
						i_71066 = addInt(i_71066, 1);
					}
			} while(false);
		} while(false);
		F.line = 234;
		oldNode_71038.events = newNode_71037.events;
		F.line = 235;
		applyEvents_70205(oldNode_71038, kxi_71039);
	framePtr = F.prev;

	
}

function X5BX5Deq__55865(x_55867, idx_55868, y_55869) {
	var F={procname:"vdom.[]=",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
		F.line = 204;
		x_55867.kids[chckIndx(idx_55868, 0, x_55867.kids.length-1)-0] = y_55869;
	framePtr = F.prev;

	
}

function addPatchV_71172(kxi_71174, parent_71175, pos_71176, newChild_71177) {
	var F={procname:"karax.addPatchV",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		F.line = 263;
		var L_71178 = kxi_71174.patchLenV;
		if (((kxi_71174.patchesV != null ? kxi_71174.patchesV.length : 0) <= L_71178)) {
		F.line = 266;
		if (kxi_71174.patchesV != null) { kxi_71174.patchesV.push({parent: parent_71175, newChild: newChild_71177, pos: pos_71176}); } else { kxi_71174.patchesV = [{parent: parent_71175, newChild: newChild_71177, pos: pos_71176}]; };
		}
		else {
			F.line = 268;
			kxi_71174.patchesV[chckIndx(L_71178, 0, kxi_71174.patchesV.length-1)-0].parent = parent_71175;
			F.line = 269;
			kxi_71174.patchesV[chckIndx(L_71178, 0, kxi_71174.patchesV.length-1)-0].newChild = newChild_71177;
			F.line = 270;
			kxi_71174.patchesV[chckIndx(L_71178, 0, kxi_71174.patchesV.length-1)-0].pos = pos_71176;
		}
		
		F.line = 271;
		kxi_71174.patchLenV = addInt(kxi_71174.patchLenV, 1);
	framePtr = F.prev;

	
}

function addPatch_71137(kxi_71139, ka_71140, parenta_71141, currenta_71142, na_71143) {
	var F={procname:"karax.addPatch",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		F.line = 251;
		var L_71144 = kxi_71139.patchLen;
		if (((kxi_71139.patches != null ? kxi_71139.patches.length : 0) <= L_71144)) {
		F.line = 254;
		if (kxi_71139.patches != null) { kxi_71139.patches.push({k: ka_71140, parent: parenta_71141, current: currenta_71142, n: na_71143}); } else { kxi_71139.patches = [{k: ka_71140, parent: parenta_71141, current: currenta_71142, n: na_71143}]; };
		}
		else {
			F.line = 256;
			kxi_71139.patches[chckIndx(L_71144, 0, kxi_71139.patches.length-1)-0].k = ka_71140;
			F.line = 257;
			kxi_71139.patches[chckIndx(L_71144, 0, kxi_71139.patches.length-1)-0].parent = parenta_71141;
			F.line = 258;
			kxi_71139.patches[chckIndx(L_71144, 0, kxi_71139.patches.length-1)-0].current = currenta_71142;
			F.line = 259;
			kxi_71139.patches[chckIndx(L_71144, 0, kxi_71139.patches.length-1)-0].n = na_71143;
		}
		
		F.line = 260;
		kxi_71139.patchLen = addInt(kxi_71139.patchLen, 1);
	framePtr = F.prev;

	
}

function diff_71414(newNode_71416, oldNode_71417, parent_71418, current_71419, kxi_71420) {
				var Tmp1;
				var Tmp2;
			var Tmp3;
			var Tmp4;
						var Tmp7;
						var Tmp10;
						var Tmp11;

	var result_71421 = 0;

	var F={procname:"karax.diff",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		F.line = 313;
		result_71421 = eq_70732(newNode_71416, oldNode_71417);
		F.line = 314;
		switch (result_71421) {
		case 3:
		case 2:
			F.line = 316;
			newNode_71416.dom = oldNode_71417.dom;
			if ((result_71421 == 2)) {
			F.line = 317;
			updateStyles_71008(newNode_71416, oldNode_71417);
			}
			
				if (!(((newNode_71416.events != null ? newNode_71416.events.length : 0) == 0))) Tmp1 = true; else {					Tmp1 = !(((oldNode_71417.events != null ? oldNode_71417.events.length : 0) == 0));				}			if (Tmp1) {
			F.line = 319;
			mergeEvents_71035(newNode_71416, oldNode_71417, kxi_71420);
			}
			
				if ((oldNode_71417.kind == 102)) Tmp2 = true; else {					Tmp2 = (oldNode_71417.kind == 108);				}			if (Tmp2) {
			if (!((oldNode_71417.text == newNode_71416.text))) {
			F.line = 322;
			oldNode_71417.text = newNode_71416.text;
			F.line = 323;
			oldNode_71417.dom.value = newNode_71416.text;
			}
			
			}
			
			F.line = 325;
			var newLength_71641 = len_55849(newNode_71416);
			F.line = 326;
			var oldLength_71642 = len_55849(oldNode_71417);
			if (((newLength_71641 == 0) && (oldLength_71642 == 0))) {
			F.line = 327;
			break BeforeRet;
			}
			
			F.line = 328;
			var minLength_71643 = nimMin(newLength_71641, oldLength_71642);
			if (!((oldNode_71417.kind == newNode_71416.kind))) {
			F.line = 330;
			failedAssertImpl_22239(makeNimstrLit("oldNode.kind == newNode.kind "));
			}
			
			F.line = 331;
			var commonPrefix_71801 = 0;
			F.line = 332;
			if ((oldNode_71417.kind == 5)) Tmp4 = true; else {				Tmp4 = (oldNode_71417.kind == 3);			}			if (Tmp4) Tmp3 = true; else {				Tmp3 = (oldNode_71417.kind == 4);			}			var isSpecial_71829 = Tmp3;
			L5: do {
				F.line = 361;
					L6: while (true) {
					if (!(commonPrefix_71801 < minLength_71643)) break L6;
						F.line = 337;
						var oldLen_71861 = kxi_71420.patchLen;
						F.line = 338;
						var oldLenV_71863 = kxi_71420.patchLenV;
						if (!((commonPrefix_71801 < len_55849(newNode_71416)))) {
						F.line = 339;
						failedAssertImpl_22239(makeNimstrLit("commonPrefix < len(newNode) "));
						}
						
						if (!((commonPrefix_71801 < len_55849(oldNode_71417)))) {
						F.line = 340;
						failedAssertImpl_22239(makeNimstrLit("commonPrefix < len(oldNode) "));
						}
						
						F.line = 341;
						if (isSpecial_71829) {
						Tmp7 = diff_71414(X5BX5D__55860(newNode_71416, commonPrefix_71801), X5BX5D__55860(oldNode_71417, commonPrefix_71801), parent_71418, current_71419, kxi_71420);
						}
						else {
						Tmp7 = diff_71414(X5BX5D__55860(newNode_71416, commonPrefix_71801), X5BX5D__55860(oldNode_71417, commonPrefix_71801), current_71419, current_71419.childNodes[chckIndx(commonPrefix_71801, 0, current_71419.childNodes.length-1)-0], kxi_71420);
						}
						
						var r_72202 = Tmp7;
						F.line = 362;
						switch (r_72202) {
						case 3:
						case 0:
						case 2:
							F.line = 347;
							X5BX5Deq__55865(newNode_71416, commonPrefix_71801, X5BX5D__55860(oldNode_71417, commonPrefix_71801));
							F.line = 363;
							commonPrefix_71801 = addInt(commonPrefix_71801, 1);
							break;
						case 4:
							F.line = 350;
							addPatchV_71172(kxi_71420, oldNode_71417, commonPrefix_71801, X5BX5D__55860(newNode_71416, commonPrefix_71801));
							F.line = 363;
							commonPrefix_71801 = addInt(commonPrefix_71801, 1);
							F.line = 353;
							result_71421 = 4;
							break;
						case 1:
							F.line = 356;
							kxi_71420.patchLen = oldLen_71861;
							F.line = 357;
							kxi_71420.patchLenV = oldLenV_71863;
							if (!((result_71421 == 1))) {
							F.line = 358;
							result_71421 = r_72202;
							}
							
							F.line = 359;
							break L5;
							break;
						}
					}
			} while(false);
			F.line = 366;
			var oldPos_72229 = subInt(oldLength_71642, 1);
			F.line = 367;
			var newPos_72230 = subInt(newLength_71641, 1);
			L8: do {
				F.line = 368;
					L9: while (true) {
						if (!(commonPrefix_71801 <= oldPos_72229)) Tmp10 = false; else {							Tmp10 = (commonPrefix_71801 <= newPos_72230);						}					if (!Tmp10) break L9;
						F.line = 337;
						var oldLen_72238 = kxi_71420.patchLen;
						F.line = 338;
						var oldLenV_72240 = kxi_71420.patchLenV;
						if (!((newPos_72230 < len_55849(newNode_71416)))) {
						F.line = 339;
						failedAssertImpl_22239(makeNimstrLit("newPos < len(newNode) "));
						}
						
						if (!((oldPos_72229 < len_55849(oldNode_71417)))) {
						F.line = 340;
						failedAssertImpl_22239(makeNimstrLit("oldPos < len(oldNode) "));
						}
						
						F.line = 341;
						if (isSpecial_71829) {
						Tmp11 = diff_71414(X5BX5D__55860(newNode_71416, newPos_72230), X5BX5D__55860(oldNode_71417, oldPos_72229), parent_71418, current_71419, kxi_71420);
						}
						else {
						Tmp11 = diff_71414(X5BX5D__55860(newNode_71416, newPos_72230), X5BX5D__55860(oldNode_71417, oldPos_72229), current_71419, current_71419.childNodes[chckIndx(oldPos_72229, 0, current_71419.childNodes.length-1)-0], kxi_71420);
						}
						
						var r_72602 = Tmp11;
						F.line = 369;
						switch (r_72602) {
						case 3:
						case 0:
						case 2:
							F.line = 347;
							X5BX5Deq__55865(newNode_71416, newPos_72230, X5BX5D__55860(oldNode_71417, oldPos_72229));
							F.line = 370;
							oldPos_72229 = subInt(oldPos_72229, 1);
							F.line = 371;
							newPos_72230 = subInt(newPos_72230, 1);
							break;
						case 4:
							F.line = 350;
							addPatchV_71172(kxi_71420, oldNode_71417, oldPos_72229, X5BX5D__55860(newNode_71416, newPos_72230));
							F.line = 370;
							oldPos_72229 = subInt(oldPos_72229, 1);
							F.line = 371;
							newPos_72230 = subInt(newPos_72230, 1);
							F.line = 353;
							result_71421 = 4;
							break;
						case 1:
							F.line = 356;
							kxi_71420.patchLen = oldLen_72238;
							F.line = 357;
							kxi_71420.patchLenV = oldLenV_72240;
							if (!((result_71421 == 1))) {
							F.line = 358;
							result_71421 = r_72602;
							}
							
							F.line = 359;
							break L8;
							break;
						}
					}
			} while(false);
			F.line = 373;
			var pos_72647 = addInt(nimMin(oldPos_72229, newPos_72230), 1);
			L12: do {
				F.line = 375;
				var i_72657 = 0;
				F.line = 1973;
				var colontmp__73404 = 0;
				F.line = 375;
				colontmp__73404 = subInt(pos_72647, 1);
				F.line = 1955;
				var res_73407 = commonPrefix_71801;
				L13: do {
					F.line = 1956;
						L14: while (true) {
						if (!(res_73407 <= colontmp__73404)) break L14;
							F.line = 1957;
							i_72657 = res_73407;
							F.line = 376;
							var r_72658 = diff_71414(X5BX5D__55860(newNode_71416, i_72657), X5BX5D__55860(oldNode_71417, i_72657), current_71419, current_71419.childNodes[chckIndx(i_72657, 0, current_71419.childNodes.length-1)-0], kxi_71420);
							if ((r_72658 == 4)) {
							F.line = 379;
							addPatchV_71172(kxi_71420, oldNode_71417, i_72657, X5BX5D__55860(newNode_71416, i_72657));
							}
							else {
							if (!((r_72658 == 1))) {
							F.line = 381;
							X5BX5Deq__55865(newNode_71416, i_72657, X5BX5D__55860(oldNode_71417, i_72657));
							}
							}
							F.line = 1976;
							res_73407 = addInt(res_73407, 1);
						}
				} while(false);
			} while(false);
			if ((addInt(oldPos_72229, 1) == oldLength_71642)) {
			L15: do {
				F.line = 386;
				var i_72684 = 0;
				F.line = 1955;
				var res_73414 = pos_72647;
				L16: do {
					F.line = 1956;
						L17: while (true) {
						if (!(res_73414 <= newPos_72230)) break L17;
							F.line = 1957;
							i_72684 = res_73414;
							F.line = 387;
							addPatch_71137(kxi_71420, 2, current_71419, null, X5BX5D__55860(newNode_71416, i_72684));
							F.line = 388;
							result_71421 = 4;
							F.line = 1976;
							res_73414 = addInt(res_73414, 1);
						}
				} while(false);
			} while(false);
			}
			else {
				F.line = 390;
				var before_72685 = current_71419.childNodes[chckIndx(addInt(oldPos_72229, 1), 0, current_71419.childNodes.length-1)-0];
				L18: do {
					F.line = 391;
					var i_72695 = 0;
					F.line = 1955;
					var res_73421 = pos_72647;
					L19: do {
						F.line = 1956;
							L20: while (true) {
							if (!(res_73421 <= newPos_72230)) break L20;
								F.line = 1957;
								i_72695 = res_73421;
								F.line = 392;
								addPatch_71137(kxi_71420, 3, current_71419, before_72685, X5BX5D__55860(newNode_71416, i_72695));
								F.line = 393;
								result_71421 = 4;
								F.line = 1976;
								res_73421 = addInt(res_73421, 1);
							}
					} while(false);
				} while(false);
			}
			
			L21: do {
				F.line = 395;
				var i_72705 = 0;
				F.line = 1955;
				var res_73428 = pos_72647;
				L22: do {
					F.line = 1956;
						L23: while (true) {
						if (!(res_73428 <= oldPos_72229)) break L23;
							F.line = 1957;
							i_72705 = res_73428;
							F.line = 396;
							addPatch_71137(kxi_70083[0], 4, null, null, X5BX5D__55860(oldNode_71417, i_72705));
							F.line = 398;
							addPatch_71137(kxi_71420, 1, current_71419, current_71419.childNodes[chckIndx(i_72705, 0, current_71419.childNodes.length-1)-0], null);
							F.line = 399;
							result_71421 = 4;
							F.line = 1976;
							res_73428 = addInt(res_73428, 1);
						}
				} while(false);
			} while(false);
			break;
		case 0:
			if (!((oldNode_71417.kind == 5))) {
			F.line = 402;
			failedAssertImpl_22239(makeNimstrLit("oldNode.kind == component "));
			}
			
			F.line = 403;
			var x_72801 = oldNode_71417;
			F.line = 404;
			x_72801.updatedImpl(x_72801, newNode_71416);
			F.line = 405;
			var oldExpanded_72802 = x_72801.expanded;
			F.line = 406;
			x_72801.expanded = x_72801.renderImpl(x_72801);
			F.line = 407;
			x_72801.renderedVersion = x_72801.version;
			if ((oldExpanded_72802 == null)) {
			F.line = 409;
			addPatch_71137(kxi_70083[0], 4, null, null, oldNode_71417);
			F.line = 410;
			addPatch_71137(kxi_71420, 0, parent_71418, current_71419, x_72801.expanded);
			}
			else {
				F.line = 412;
				var res_72814 = diff_71414(x_72801.expanded, oldExpanded_72802, parent_71418, current_71419, kxi_71420);
				if ((res_72814 == 4)) {
				}
				else {
				if (!((res_72814 == 1))) {
				F.line = 417;
				x_72801.expanded = oldExpanded_72802;
				if (!(!((oldExpanded_72802.dom == null)))) {
				F.line = 418;
				failedAssertImpl_22239(makeNimstrLit("\x0A  not (oldExpanded.dom == nil) old expanded.dom is nil"));
				}
				
				}
				else {
					if (!(!((x_72801.expanded.dom == null)))) {
					F.line = 420;
					failedAssertImpl_22239(makeNimstrLit("\x0A  not (x.expanded.dom == nil) expanded.dom is nil"));
					}
					
				}
				}
			}
			
			break;
		case 1:
			F.line = 422;
			addPatch_71137(kxi_70083[0], 4, null, null, oldNode_71417);
			F.line = 423;
			addPatch_71137(kxi_71420, 0, parent_71418, current_71419, newNode_71416);
			break;
		case 4:
			if (true) {
			F.line = 424;
			raiseAssert_22216(makeNimstrLit("false eq returned usenewNode"));
			}
			
			break;
		}
	} while (false);
	framePtr = F.prev;

	return result_71421;

}

function apply_71206(kxi_71208) {
	var F={procname:"karax.apply",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		L1: do {
			F.line = 274;
			var i_71218 = 0;
			F.line = 3812;
			var colontmp__71402 = 0;
			F.line = 274;
			colontmp__71402 = kxi_71208.patchLen;
			F.line = 3813;
			var i_71405 = 0;
			L2: do {
				F.line = 3814;
					L3: while (true) {
					if (!(i_71405 < colontmp__71402)) break L3;
						F.line = 3815;
						i_71218 = i_71405;
						F.line = 275;
						var p_71219 = nimCopy(null, kxi_71208.patches[chckIndx(i_71218, 0, kxi_71208.patches.length-1)-0], NTI70024);
						F.line = 276;
						switch (p_71219.k) {
						case 0:
							F.line = 278;
							var nn_71220 = vnodeToDom_70234(p_71219.n, kxi_71208);
							if ((p_71219.parent == null)) {
							F.line = 280;
							replaceById_70720(kxi_71208.rootId, nn_71220);
							}
							else {
								F.line = 282;
							p_71219.parent.replaceChild(nn_71220, p_71219.current);
							}
							
							break;
						case 1:
							F.line = 284;
							p_71219.parent.removeChild(p_71219.current);
							break;
						case 2:
							F.line = 286;
							var nn_71232 = vnodeToDom_70234(p_71219.n, kxi_71208);
							F.line = 287;
							p_71219.parent.appendChild(nn_71232);
							break;
						case 3:
							F.line = 289;
							var nn_71233 = vnodeToDom_70234(p_71219.n, kxi_71208);
							F.line = 290;
							p_71219.parent.insertBefore(nn_71233, p_71219.current);
							break;
						case 4:
							F.line = 292;
							var n_71234 = p_71219.n;
							if ((n_71234.kind == 5)) {
							F.line = 294;
							var x_71244 = n_71234;
							if (!((x_71244.onDetachImpl == null))) {
							F.line = 295;
							x_71244.onDetachImpl(x_71244);
							}
							
							}
							
							F.line = 296;
							n_71234.dom = null;
							break;
						}
						F.line = 3816;
						i_71405 = addInt(i_71405, 1);
					}
			} while(false);
		} while(false);
		F.line = 297;
		kxi_71208.patchLen = 0;
		L4: do {
			F.line = 298;
			var i_71262 = 0;
			F.line = 3812;
			var colontmp__71408 = 0;
			F.line = 298;
			colontmp__71408 = kxi_71208.patchLenV;
			F.line = 3813;
			var i_71411 = 0;
			L5: do {
				F.line = 3814;
					L6: while (true) {
					if (!(i_71411 < colontmp__71408)) break L6;
						F.line = 3815;
						i_71262 = i_71411;
						F.line = 299;
						var p_71263 = nimCopy(null, kxi_71208.patchesV[chckIndx(i_71262, 0, kxi_71208.patchesV.length-1)-0], NTI70026);
						F.line = 300;
						X5BX5Deq__55865(p_71263.parent, p_71263.pos, p_71263.newChild);
						if (!(!((p_71263.newChild.dom == null)))) {
						F.line = 301;
						failedAssertImpl_22239(makeNimstrLit("\x0A  not (p.newChild.dom == nil) "));
						}
						
						F.line = 3816;
						i_71411 = addInt(i_71411, 1);
					}
			} while(false);
		} while(false);
		F.line = 302;
		kxi_71208.patchLenV = 0;
	framePtr = F.prev;

	
}

function dodraw_73601(kxi_73603) {
	var F={procname:"karax.dodraw",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if ((kxi_73603.renderer === null)) {
		F.line = 437;
		break BeforeRet;
		}
		
		F.line = 438;
		var newtree_73610 = kxi_73603.renderer();
		F.line = 439;
		kxi_73603.runCount = addInt(kxi_73603.runCount, 1);
		F.line = 440;
		newtree_73610.id = kxi_73603.rootId;
		F.line = 441;
		kxi_73603.toFocus = null;
		if ((kxi_73603.currentTree == null)) {
		F.line = 443;
		kxi_73603.currentTree = newtree_73610;
		F.line = 444;
		var asdom_73631 = vnodeToDom_70234(kxi_73603.currentTree, kxi_73603);
		F.line = 445;
		replaceById_70720(kxi_73603.rootId, asdom_73631);
		}
		else {
			if (!(same_70650(kxi_73603.currentTree, document.getElementById(kxi_73603.rootId), 0))) {
			F.line = 447;
			raiseAssert_22216(makeNimstrLit("same(kxi.currentTree, getElementById(document, kxi.rootId), 0) "));
			}
			
			F.line = 448;
			var olddom_73632 = document.getElementById(kxi_73603.rootId);
			F.line = 449;
			diff_71414(newtree_73610, kxi_73603.currentTree, null, olddom_73632, kxi_73603);
			F.line = 451;
			apply_71206(kxi_73603);
			F.line = 452;
			kxi_73603.currentTree = newtree_73610;
		}
		
		if (!(same_70650(kxi_73603.currentTree, document.getElementById(kxi_73603.rootId), 0))) {
		F.line = 453;
		raiseAssert_22216(makeNimstrLit("same(kxi.currentTree, getElementById(document, kxi.rootId), 0) "));
		}
		
		if (!((kxi_73603.postRenderCallback === null))) {
		F.line = 456;
		kxi_73603.postRenderCallback();
		}
		
		if (!((kxi_73603.toFocus == null))) {
		F.line = 460;
		kxi_73603.toFocus.focus();
		}
		
		F.line = 461;
		kxi_73603.renderId = 0;
	} while (false);
	framePtr = F.prev;

	
}

function init_74007(ev_74009) {

		function colonanonymous__74010() {
			var F={procname:"init.:anonymous",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
			framePtr = F;
				F.line = 485;
				dodraw_73601(kxi_70083[0]);
			framePtr = F.prev;

			
		}

	var F={procname:"karax.init",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		F.line = 485;
		kxi_70083[0].renderId = window.requestAnimationFrame(colonanonymous__74010);
	framePtr = F.prev;

	
}

function setRenderer_74013(renderer_74017, root_74018, clientPostRenderCallback_74021) {
	var result_74022 = null;

	var F={procname:"karax.setRenderer",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		F.line = 490;
		result_74022 = {rootId: root_74018, renderer: nimCopy(null, renderer_74017, NTI74015), postRenderCallback: nimCopy(null, clientPostRenderCallback_74021, NTI74019), patches: newSeq_74037(60), patchesV: newSeq_74076(30), currentTree: null, toFocus: null, toFocusV: null, renderId: 0, patchLen: 0, patchLenV: 0, runCount: 0};
		F.line = 494;
		kxi_70083[0] = result_74022;
		F.line = 495;
		window.onload = init_74007;
	framePtr = F.prev;

	return result_74022;

}

function newVNode_55884(kind_55886) {
	var result_55887 = null;

	var F={procname:"vdom.newVNode",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
		F.line = 206;
		result_55887 = {kind: kind_55886, key: -1, m_type: NTI55476, id: null, class: null, text: null, kids: null, attrs: null, events: null, style: null, dom: null};
	framePtr = F.prev;

	return result_55887;

}

function add_55870(parent_55872, kid_55873) {
	var F={procname:"vdom.add",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
		F.line = 205;
		if (parent_55872.kids != null) { parent_55872.kids.push(kid_55873); } else { parent_55872.kids = [kid_55873]; };
	framePtr = F.prev;

	
}

function tree_55889(kind_55891, kids_55893) {
	var result_55894 = null;

	var F={procname:"vdom.tree",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
		F.line = 209;
		result_55894 = newVNode_55884(kind_55891);
		L1: do {
			F.line = 210;
			var k_55919 = null;
			F.line = 2060;
			var i_55923 = 0;
			L2: do {
				F.line = 2061;
					L3: while (true) {
					if (!(i_55923 < (kids_55893 != null ? kids_55893.length : 0))) break L3;
						F.line = 2062;
						k_55919 = kids_55893[chckIndx(i_55923, 0, kids_55893.length-1)-0];
						F.line = 210;
						add_55870(result_55894, k_55919);
						F.line = 2063;
						i_55923 = addInt(i_55923, 1);
					}
			} while(false);
		} while(false);
	framePtr = F.prev;

	return result_55894;

}

function createDom_77001() {
	var result_77003 = null;

	var F={procname:"website.createDom",prev:framePtr,filename:"website.nim",line:0};
	framePtr = F;
		F.line = 3;
		F.line = 3;
		var tmp_77010 = tree_55889(42, []);
		F.line = 3;
		tmp_77010.class = "todomvc-wrapper";
		result_77003 = tmp_77010;
	framePtr = F.prev;

	return result_77003;

}
setRenderer_74013(createDom_77001, "ROOT", null);
