/* Generated by the Nim Compiler v0.17.1 */
/*   (c) 2017 Andreas Rumpf */

var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;
var NTI98026 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI62062 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI62063 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI83524 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI83520 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI83121 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI83487 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI83486 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI83484 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI83482 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI83466 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI83002 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI83476 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI83468 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI53383 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53379 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53375 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53371 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53367 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53363 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53359 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53355 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53351 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53347 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53343 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53339 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53335 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53331 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53327 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53323 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53319 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53315 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53311 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53307 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI53204 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI53258 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI53218 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI53431 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI53429 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI53427 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI53222 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI53220 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI98022 = {size: 0, kind: 14, base: null, node: null, finalizer: null};
var NTI98024 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI53260 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI83458 = {size: 0,kind: 16,base: null,node: null,finalizer: null};
var NTI31254 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI83452 = {size: 0,kind: 16,base: null,node: null,finalizer: null};
var NTI31246 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI28004 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI41209 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI31208 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI28038 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI28040 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI31287 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI31224 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI31238 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI31242 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI102019 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NTI102015 = {size: 0,kind: 25,base: null,node: null,finalizer: null};
var NNI31242 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI31242.node = NNI31242;
var NNI31238 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI31238.node = NNI31238;
NTI31287.base = NTI31224;
var NNI31224 = {kind: 2, len: 4, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI31287, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI28040, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI28038, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI28038, name: "trace", sons: null}]};
NTI31224.node = NNI31224;
var NNI31208 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI31208.node = NNI31208;
NTI31224.base = NTI31208;
NTI31238.base = NTI31224;
NTI31242.base = NTI31238;
var NNI41209 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI28040, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI28004, name: "Field1", sons: null}]};
NTI41209.node = NNI41209;
var NNI31246 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI31246.node = NNI31246;
NTI31246.base = NTI31224;
NTI83452.base = NTI28040;
var NNI31254 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI31254.node = NNI31254;
NTI31254.base = NTI31224;
NTI83458.base = NTI28040;
var NNI53260 = {kind: 2, len: 91, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "background", len: 0, typ: NTI28040, name: "background", sons: null}, 
{kind: 1, offset: "backgroundAttachment", len: 0, typ: NTI28040, name: "backgroundAttachment", sons: null}, 
{kind: 1, offset: "backgroundColor", len: 0, typ: NTI28040, name: "backgroundColor", sons: null}, 
{kind: 1, offset: "backgroundImage", len: 0, typ: NTI28040, name: "backgroundImage", sons: null}, 
{kind: 1, offset: "backgroundPosition", len: 0, typ: NTI28040, name: "backgroundPosition", sons: null}, 
{kind: 1, offset: "backgroundRepeat", len: 0, typ: NTI28040, name: "backgroundRepeat", sons: null}, 
{kind: 1, offset: "border", len: 0, typ: NTI28040, name: "border", sons: null}, 
{kind: 1, offset: "borderBottom", len: 0, typ: NTI28040, name: "borderBottom", sons: null}, 
{kind: 1, offset: "borderBottomColor", len: 0, typ: NTI28040, name: "borderBottomColor", sons: null}, 
{kind: 1, offset: "borderBottomStyle", len: 0, typ: NTI28040, name: "borderBottomStyle", sons: null}, 
{kind: 1, offset: "borderBottomWidth", len: 0, typ: NTI28040, name: "borderBottomWidth", sons: null}, 
{kind: 1, offset: "borderColor", len: 0, typ: NTI28040, name: "borderColor", sons: null}, 
{kind: 1, offset: "borderLeft", len: 0, typ: NTI28040, name: "borderLeft", sons: null}, 
{kind: 1, offset: "borderLeftColor", len: 0, typ: NTI28040, name: "borderLeftColor", sons: null}, 
{kind: 1, offset: "borderLeftStyle", len: 0, typ: NTI28040, name: "borderLeftStyle", sons: null}, 
{kind: 1, offset: "borderLeftWidth", len: 0, typ: NTI28040, name: "borderLeftWidth", sons: null}, 
{kind: 1, offset: "borderRight", len: 0, typ: NTI28040, name: "borderRight", sons: null}, 
{kind: 1, offset: "borderRightColor", len: 0, typ: NTI28040, name: "borderRightColor", sons: null}, 
{kind: 1, offset: "borderRightStyle", len: 0, typ: NTI28040, name: "borderRightStyle", sons: null}, 
{kind: 1, offset: "borderRightWidth", len: 0, typ: NTI28040, name: "borderRightWidth", sons: null}, 
{kind: 1, offset: "borderStyle", len: 0, typ: NTI28040, name: "borderStyle", sons: null}, 
{kind: 1, offset: "borderTop", len: 0, typ: NTI28040, name: "borderTop", sons: null}, 
{kind: 1, offset: "borderTopColor", len: 0, typ: NTI28040, name: "borderTopColor", sons: null}, 
{kind: 1, offset: "borderTopStyle", len: 0, typ: NTI28040, name: "borderTopStyle", sons: null}, 
{kind: 1, offset: "borderTopWidth", len: 0, typ: NTI28040, name: "borderTopWidth", sons: null}, 
{kind: 1, offset: "borderWidth", len: 0, typ: NTI28040, name: "borderWidth", sons: null}, 
{kind: 1, offset: "bottom", len: 0, typ: NTI28040, name: "bottom", sons: null}, 
{kind: 1, offset: "captionSide", len: 0, typ: NTI28040, name: "captionSide", sons: null}, 
{kind: 1, offset: "clear", len: 0, typ: NTI28040, name: "clear", sons: null}, 
{kind: 1, offset: "clip", len: 0, typ: NTI28040, name: "clip", sons: null}, 
{kind: 1, offset: "color", len: 0, typ: NTI28040, name: "color", sons: null}, 
{kind: 1, offset: "cursor", len: 0, typ: NTI28040, name: "cursor", sons: null}, 
{kind: 1, offset: "direction", len: 0, typ: NTI28040, name: "direction", sons: null}, 
{kind: 1, offset: "display", len: 0, typ: NTI28040, name: "display", sons: null}, 
{kind: 1, offset: "emptyCells", len: 0, typ: NTI28040, name: "emptyCells", sons: null}, 
{kind: 1, offset: "cssFloat", len: 0, typ: NTI28040, name: "cssFloat", sons: null}, 
{kind: 1, offset: "font", len: 0, typ: NTI28040, name: "font", sons: null}, 
{kind: 1, offset: "fontFamily", len: 0, typ: NTI28040, name: "fontFamily", sons: null}, 
{kind: 1, offset: "fontSize", len: 0, typ: NTI28040, name: "fontSize", sons: null}, 
{kind: 1, offset: "fontStretch", len: 0, typ: NTI28040, name: "fontStretch", sons: null}, 
{kind: 1, offset: "fontStyle", len: 0, typ: NTI28040, name: "fontStyle", sons: null}, 
{kind: 1, offset: "fontVariant", len: 0, typ: NTI28040, name: "fontVariant", sons: null}, 
{kind: 1, offset: "fontWeight", len: 0, typ: NTI28040, name: "fontWeight", sons: null}, 
{kind: 1, offset: "height", len: 0, typ: NTI28040, name: "height", sons: null}, 
{kind: 1, offset: "left", len: 0, typ: NTI28040, name: "left", sons: null}, 
{kind: 1, offset: "letterSpacing", len: 0, typ: NTI28040, name: "letterSpacing", sons: null}, 
{kind: 1, offset: "lineHeight", len: 0, typ: NTI28040, name: "lineHeight", sons: null}, 
{kind: 1, offset: "listStyle", len: 0, typ: NTI28040, name: "listStyle", sons: null}, 
{kind: 1, offset: "listStyleImage", len: 0, typ: NTI28040, name: "listStyleImage", sons: null}, 
{kind: 1, offset: "listStylePosition", len: 0, typ: NTI28040, name: "listStylePosition", sons: null}, 
{kind: 1, offset: "listStyleType", len: 0, typ: NTI28040, name: "listStyleType", sons: null}, 
{kind: 1, offset: "margin", len: 0, typ: NTI28040, name: "margin", sons: null}, 
{kind: 1, offset: "marginBottom", len: 0, typ: NTI28040, name: "marginBottom", sons: null}, 
{kind: 1, offset: "marginLeft", len: 0, typ: NTI28040, name: "marginLeft", sons: null}, 
{kind: 1, offset: "marginRight", len: 0, typ: NTI28040, name: "marginRight", sons: null}, 
{kind: 1, offset: "marginTop", len: 0, typ: NTI28040, name: "marginTop", sons: null}, 
{kind: 1, offset: "maxHeight", len: 0, typ: NTI28040, name: "maxHeight", sons: null}, 
{kind: 1, offset: "maxWidth", len: 0, typ: NTI28040, name: "maxWidth", sons: null}, 
{kind: 1, offset: "minHeight", len: 0, typ: NTI28040, name: "minHeight", sons: null}, 
{kind: 1, offset: "minWidth", len: 0, typ: NTI28040, name: "minWidth", sons: null}, 
{kind: 1, offset: "overflow", len: 0, typ: NTI28040, name: "overflow", sons: null}, 
{kind: 1, offset: "padding", len: 0, typ: NTI28040, name: "padding", sons: null}, 
{kind: 1, offset: "paddingBottom", len: 0, typ: NTI28040, name: "paddingBottom", sons: null}, 
{kind: 1, offset: "paddingLeft", len: 0, typ: NTI28040, name: "paddingLeft", sons: null}, 
{kind: 1, offset: "paddingRight", len: 0, typ: NTI28040, name: "paddingRight", sons: null}, 
{kind: 1, offset: "paddingTop", len: 0, typ: NTI28040, name: "paddingTop", sons: null}, 
{kind: 1, offset: "pageBreakAfter", len: 0, typ: NTI28040, name: "pageBreakAfter", sons: null}, 
{kind: 1, offset: "pageBreakBefore", len: 0, typ: NTI28040, name: "pageBreakBefore", sons: null}, 
{kind: 1, offset: "pointerEvents", len: 0, typ: NTI28040, name: "pointerEvents", sons: null}, 
{kind: 1, offset: "position", len: 0, typ: NTI28040, name: "position", sons: null}, 
{kind: 1, offset: "right", len: 0, typ: NTI28040, name: "right", sons: null}, 
{kind: 1, offset: "scrollbar3dLightColor", len: 0, typ: NTI28040, name: "scrollbar3dLightColor", sons: null}, 
{kind: 1, offset: "scrollbarArrowColor", len: 0, typ: NTI28040, name: "scrollbarArrowColor", sons: null}, 
{kind: 1, offset: "scrollbarBaseColor", len: 0, typ: NTI28040, name: "scrollbarBaseColor", sons: null}, 
{kind: 1, offset: "scrollbarDarkshadowColor", len: 0, typ: NTI28040, name: "scrollbarDarkshadowColor", sons: null}, 
{kind: 1, offset: "scrollbarFaceColor", len: 0, typ: NTI28040, name: "scrollbarFaceColor", sons: null}, 
{kind: 1, offset: "scrollbarHighlightColor", len: 0, typ: NTI28040, name: "scrollbarHighlightColor", sons: null}, 
{kind: 1, offset: "scrollbarShadowColor", len: 0, typ: NTI28040, name: "scrollbarShadowColor", sons: null}, 
{kind: 1, offset: "scrollbarTrackColor", len: 0, typ: NTI28040, name: "scrollbarTrackColor", sons: null}, 
{kind: 1, offset: "tableLayout", len: 0, typ: NTI28040, name: "tableLayout", sons: null}, 
{kind: 1, offset: "textAlign", len: 0, typ: NTI28040, name: "textAlign", sons: null}, 
{kind: 1, offset: "textDecoration", len: 0, typ: NTI28040, name: "textDecoration", sons: null}, 
{kind: 1, offset: "textIndent", len: 0, typ: NTI28040, name: "textIndent", sons: null}, 
{kind: 1, offset: "textTransform", len: 0, typ: NTI28040, name: "textTransform", sons: null}, 
{kind: 1, offset: "transform", len: 0, typ: NTI28040, name: "transform", sons: null}, 
{kind: 1, offset: "top", len: 0, typ: NTI28040, name: "top", sons: null}, 
{kind: 1, offset: "verticalAlign", len: 0, typ: NTI28040, name: "verticalAlign", sons: null}, 
{kind: 1, offset: "visibility", len: 0, typ: NTI28040, name: "visibility", sons: null}, 
{kind: 1, offset: "width", len: 0, typ: NTI28040, name: "width", sons: null}, 
{kind: 1, offset: "wordSpacing", len: 0, typ: NTI28040, name: "wordSpacing", sons: null}, 
{kind: 1, offset: "zIndex", len: 0, typ: NTI28004, name: "zIndex", sons: null}]};
NTI53260.node = NNI53260;
NTI53260.base = NTI31208;
var NNI98022 = {kind: 2, offset: 0, typ: null, name: null, len: 5, sons: {"0": {kind: 1, offset: 0, typ: NTI98022, name: "pkReplace", len: 0, sons: null}, 
"1": {kind: 1, offset: 1, typ: NTI98022, name: "pkRemove", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI98022, name: "pkAppend", len: 0, sons: null}, 
"3": {kind: 1, offset: 3, typ: NTI98022, name: "pkInsertBefore", len: 0, sons: null}, 
"4": {kind: 1, offset: 4, typ: NTI98022, name: "pkDetach", len: 0, sons: null}}};
NTI98022.node = NNI98022;
NTI53427.base = NTI53220;
NTI53429.base = NTI53220;
NTI53431.base = NTI53220;
var NNI53218 = {kind: 2, offset: 0, typ: null, name: null, len: 12, sons: {"1": {kind: 1, offset: 1, typ: NTI53218, name: "ElementNode", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI53218, name: "AttributeNode", len: 0, sons: null}, 
"3": {kind: 1, offset: 3, typ: NTI53218, name: "TextNode", len: 0, sons: null}, 
"4": {kind: 1, offset: 4, typ: NTI53218, name: "CDATANode", len: 0, sons: null}, 
"5": {kind: 1, offset: 5, typ: NTI53218, name: "EntityRefNode", len: 0, sons: null}, 
"6": {kind: 1, offset: 6, typ: NTI53218, name: "EntityNode", len: 0, sons: null}, 
"7": {kind: 1, offset: 7, typ: NTI53218, name: "ProcessingInstructionNode", len: 0, sons: null}, 
"8": {kind: 1, offset: 8, typ: NTI53218, name: "CommentNode", len: 0, sons: null}, 
"9": {kind: 1, offset: 9, typ: NTI53218, name: "DocumentNode", len: 0, sons: null}, 
"10": {kind: 1, offset: 10, typ: NTI53218, name: "DocumentTypeNode", len: 0, sons: null}, 
"11": {kind: 1, offset: 11, typ: NTI53218, name: "DocumentFragmentNode", len: 0, sons: null}, 
"12": {kind: 1, offset: 12, typ: NTI53218, name: "NotationNode", len: 0, sons: null}}};
NTI53218.node = NNI53218;
NTI53258.base = NTI53260;
var NNI53222 = {kind: 2, len: 14, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "attributes", len: 0, typ: NTI53427, name: "attributes", sons: null}, 
{kind: 1, offset: "childNodes", len: 0, typ: NTI53429, name: "childNodes", sons: null}, 
{kind: 1, offset: "children", len: 0, typ: NTI53431, name: "children", sons: null}, 
{kind: 1, offset: "data", len: 0, typ: NTI28040, name: "data", sons: null}, 
{kind: 1, offset: "firstChild", len: 0, typ: NTI53220, name: "firstChild", sons: null}, 
{kind: 1, offset: "lastChild", len: 0, typ: NTI53220, name: "lastChild", sons: null}, 
{kind: 1, offset: "nextSibling", len: 0, typ: NTI53220, name: "nextSibling", sons: null}, 
{kind: 1, offset: "nodeName", len: 0, typ: NTI28040, name: "nodeName", sons: null}, 
{kind: 1, offset: "nodeType", len: 0, typ: NTI53218, name: "nodeType", sons: null}, 
{kind: 1, offset: "nodeValue", len: 0, typ: NTI28040, name: "nodeValue", sons: null}, 
{kind: 1, offset: "parentNode", len: 0, typ: NTI53220, name: "parentNode", sons: null}, 
{kind: 1, offset: "previousSibling", len: 0, typ: NTI53220, name: "previousSibling", sons: null}, 
{kind: 1, offset: "innerHTML", len: 0, typ: NTI28040, name: "innerHTML", sons: null}, 
{kind: 1, offset: "style", len: 0, typ: NTI53258, name: "style", sons: null}]};
NTI53222.node = NNI53222;
var NNI53204 = {kind: 2, len: 20, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "onabort", len: 0, typ: NTI53307, name: "onabort", sons: null}, 
{kind: 1, offset: "onblur", len: 0, typ: NTI53311, name: "onblur", sons: null}, 
{kind: 1, offset: "onchange", len: 0, typ: NTI53315, name: "onchange", sons: null}, 
{kind: 1, offset: "onclick", len: 0, typ: NTI53319, name: "onclick", sons: null}, 
{kind: 1, offset: "ondblclick", len: 0, typ: NTI53323, name: "ondblclick", sons: null}, 
{kind: 1, offset: "onerror", len: 0, typ: NTI53327, name: "onerror", sons: null}, 
{kind: 1, offset: "onfocus", len: 0, typ: NTI53331, name: "onfocus", sons: null}, 
{kind: 1, offset: "onkeydown", len: 0, typ: NTI53335, name: "onkeydown", sons: null}, 
{kind: 1, offset: "onkeypress", len: 0, typ: NTI53339, name: "onkeypress", sons: null}, 
{kind: 1, offset: "onkeyup", len: 0, typ: NTI53343, name: "onkeyup", sons: null}, 
{kind: 1, offset: "onload", len: 0, typ: NTI53347, name: "onload", sons: null}, 
{kind: 1, offset: "onmousedown", len: 0, typ: NTI53351, name: "onmousedown", sons: null}, 
{kind: 1, offset: "onmousemove", len: 0, typ: NTI53355, name: "onmousemove", sons: null}, 
{kind: 1, offset: "onmouseout", len: 0, typ: NTI53359, name: "onmouseout", sons: null}, 
{kind: 1, offset: "onmouseover", len: 0, typ: NTI53363, name: "onmouseover", sons: null}, 
{kind: 1, offset: "onmouseup", len: 0, typ: NTI53367, name: "onmouseup", sons: null}, 
{kind: 1, offset: "onreset", len: 0, typ: NTI53371, name: "onreset", sons: null}, 
{kind: 1, offset: "onselect", len: 0, typ: NTI53375, name: "onselect", sons: null}, 
{kind: 1, offset: "onsubmit", len: 0, typ: NTI53379, name: "onsubmit", sons: null}, 
{kind: 1, offset: "onunload", len: 0, typ: NTI53383, name: "onunload", sons: null}]};
NTI53204.node = NNI53204;
NTI53204.base = NTI31208;
NTI53222.base = NTI53204;
NTI53220.base = NTI53222;
var NNI83002 = {kind: 2, offset: 0, typ: null, name: null, len: 117, sons: {"0": {kind: 1, offset: 0, typ: NTI83002, name: "#text", len: 0, sons: null}, 
"1": {kind: 1, offset: 1, typ: NTI83002, name: "#int", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI83002, name: "#bool", len: 0, sons: null}, 
"3": {kind: 1, offset: 3, typ: NTI83002, name: "#vthunk", len: 0, sons: null}, 
"4": {kind: 1, offset: 4, typ: NTI83002, name: "#dthunk", len: 0, sons: null}, 
"5": {kind: 1, offset: 5, typ: NTI83002, name: "#component", len: 0, sons: null}, 
"6": {kind: 1, offset: 6, typ: NTI83002, name: "html", len: 0, sons: null}, 
"7": {kind: 1, offset: 7, typ: NTI83002, name: "head", len: 0, sons: null}, 
"8": {kind: 1, offset: 8, typ: NTI83002, name: "title", len: 0, sons: null}, 
"9": {kind: 1, offset: 9, typ: NTI83002, name: "base", len: 0, sons: null}, 
"10": {kind: 1, offset: 10, typ: NTI83002, name: "link", len: 0, sons: null}, 
"11": {kind: 1, offset: 11, typ: NTI83002, name: "meta", len: 0, sons: null}, 
"12": {kind: 1, offset: 12, typ: NTI83002, name: "style", len: 0, sons: null}, 
"13": {kind: 1, offset: 13, typ: NTI83002, name: "script", len: 0, sons: null}, 
"14": {kind: 1, offset: 14, typ: NTI83002, name: "noscript", len: 0, sons: null}, 
"15": {kind: 1, offset: 15, typ: NTI83002, name: "body", len: 0, sons: null}, 
"16": {kind: 1, offset: 16, typ: NTI83002, name: "section", len: 0, sons: null}, 
"17": {kind: 1, offset: 17, typ: NTI83002, name: "nav", len: 0, sons: null}, 
"18": {kind: 1, offset: 18, typ: NTI83002, name: "article", len: 0, sons: null}, 
"19": {kind: 1, offset: 19, typ: NTI83002, name: "aside", len: 0, sons: null}, 
"20": {kind: 1, offset: 20, typ: NTI83002, name: "h1", len: 0, sons: null}, 
"21": {kind: 1, offset: 21, typ: NTI83002, name: "h2", len: 0, sons: null}, 
"22": {kind: 1, offset: 22, typ: NTI83002, name: "h3", len: 0, sons: null}, 
"23": {kind: 1, offset: 23, typ: NTI83002, name: "h4", len: 0, sons: null}, 
"24": {kind: 1, offset: 24, typ: NTI83002, name: "h5", len: 0, sons: null}, 
"25": {kind: 1, offset: 25, typ: NTI83002, name: "h6", len: 0, sons: null}, 
"26": {kind: 1, offset: 26, typ: NTI83002, name: "header", len: 0, sons: null}, 
"27": {kind: 1, offset: 27, typ: NTI83002, name: "footer", len: 0, sons: null}, 
"28": {kind: 1, offset: 28, typ: NTI83002, name: "address", len: 0, sons: null}, 
"29": {kind: 1, offset: 29, typ: NTI83002, name: "main", len: 0, sons: null}, 
"30": {kind: 1, offset: 30, typ: NTI83002, name: "p", len: 0, sons: null}, 
"31": {kind: 1, offset: 31, typ: NTI83002, name: "hr", len: 0, sons: null}, 
"32": {kind: 1, offset: 32, typ: NTI83002, name: "pre", len: 0, sons: null}, 
"33": {kind: 1, offset: 33, typ: NTI83002, name: "blockquote", len: 0, sons: null}, 
"34": {kind: 1, offset: 34, typ: NTI83002, name: "ol", len: 0, sons: null}, 
"35": {kind: 1, offset: 35, typ: NTI83002, name: "ul", len: 0, sons: null}, 
"36": {kind: 1, offset: 36, typ: NTI83002, name: "li", len: 0, sons: null}, 
"37": {kind: 1, offset: 37, typ: NTI83002, name: "dl", len: 0, sons: null}, 
"38": {kind: 1, offset: 38, typ: NTI83002, name: "dt", len: 0, sons: null}, 
"39": {kind: 1, offset: 39, typ: NTI83002, name: "dd", len: 0, sons: null}, 
"40": {kind: 1, offset: 40, typ: NTI83002, name: "figure", len: 0, sons: null}, 
"41": {kind: 1, offset: 41, typ: NTI83002, name: "figcaption", len: 0, sons: null}, 
"42": {kind: 1, offset: 42, typ: NTI83002, name: "div", len: 0, sons: null}, 
"43": {kind: 1, offset: 43, typ: NTI83002, name: "a", len: 0, sons: null}, 
"44": {kind: 1, offset: 44, typ: NTI83002, name: "em", len: 0, sons: null}, 
"45": {kind: 1, offset: 45, typ: NTI83002, name: "strong", len: 0, sons: null}, 
"46": {kind: 1, offset: 46, typ: NTI83002, name: "small", len: 0, sons: null}, 
"47": {kind: 1, offset: 47, typ: NTI83002, name: "s", len: 0, sons: null}, 
"48": {kind: 1, offset: 48, typ: NTI83002, name: "cite", len: 0, sons: null}, 
"49": {kind: 1, offset: 49, typ: NTI83002, name: "quote", len: 0, sons: null}, 
"50": {kind: 1, offset: 50, typ: NTI83002, name: "dfn", len: 0, sons: null}, 
"51": {kind: 1, offset: 51, typ: NTI83002, name: "abbr", len: 0, sons: null}, 
"52": {kind: 1, offset: 52, typ: NTI83002, name: "data", len: 0, sons: null}, 
"53": {kind: 1, offset: 53, typ: NTI83002, name: "time", len: 0, sons: null}, 
"54": {kind: 1, offset: 54, typ: NTI83002, name: "code", len: 0, sons: null}, 
"55": {kind: 1, offset: 55, typ: NTI83002, name: "var", len: 0, sons: null}, 
"56": {kind: 1, offset: 56, typ: NTI83002, name: "samp", len: 0, sons: null}, 
"57": {kind: 1, offset: 57, typ: NTI83002, name: "kdb", len: 0, sons: null}, 
"58": {kind: 1, offset: 58, typ: NTI83002, name: "sub", len: 0, sons: null}, 
"59": {kind: 1, offset: 59, typ: NTI83002, name: "sup", len: 0, sons: null}, 
"60": {kind: 1, offset: 60, typ: NTI83002, name: "i", len: 0, sons: null}, 
"61": {kind: 1, offset: 61, typ: NTI83002, name: "b", len: 0, sons: null}, 
"62": {kind: 1, offset: 62, typ: NTI83002, name: "u", len: 0, sons: null}, 
"63": {kind: 1, offset: 63, typ: NTI83002, name: "mark", len: 0, sons: null}, 
"64": {kind: 1, offset: 64, typ: NTI83002, name: "ruby", len: 0, sons: null}, 
"65": {kind: 1, offset: 65, typ: NTI83002, name: "rt", len: 0, sons: null}, 
"66": {kind: 1, offset: 66, typ: NTI83002, name: "rp", len: 0, sons: null}, 
"67": {kind: 1, offset: 67, typ: NTI83002, name: "bdi", len: 0, sons: null}, 
"68": {kind: 1, offset: 68, typ: NTI83002, name: "dbo", len: 0, sons: null}, 
"69": {kind: 1, offset: 69, typ: NTI83002, name: "span", len: 0, sons: null}, 
"70": {kind: 1, offset: 70, typ: NTI83002, name: "br", len: 0, sons: null}, 
"71": {kind: 1, offset: 71, typ: NTI83002, name: "wbr", len: 0, sons: null}, 
"72": {kind: 1, offset: 72, typ: NTI83002, name: "ins", len: 0, sons: null}, 
"73": {kind: 1, offset: 73, typ: NTI83002, name: "del", len: 0, sons: null}, 
"74": {kind: 1, offset: 74, typ: NTI83002, name: "img", len: 0, sons: null}, 
"75": {kind: 1, offset: 75, typ: NTI83002, name: "iframe", len: 0, sons: null}, 
"76": {kind: 1, offset: 76, typ: NTI83002, name: "embed", len: 0, sons: null}, 
"77": {kind: 1, offset: 77, typ: NTI83002, name: "object", len: 0, sons: null}, 
"78": {kind: 1, offset: 78, typ: NTI83002, name: "param", len: 0, sons: null}, 
"79": {kind: 1, offset: 79, typ: NTI83002, name: "video", len: 0, sons: null}, 
"80": {kind: 1, offset: 80, typ: NTI83002, name: "audio", len: 0, sons: null}, 
"81": {kind: 1, offset: 81, typ: NTI83002, name: "source", len: 0, sons: null}, 
"82": {kind: 1, offset: 82, typ: NTI83002, name: "track", len: 0, sons: null}, 
"83": {kind: 1, offset: 83, typ: NTI83002, name: "canvas", len: 0, sons: null}, 
"84": {kind: 1, offset: 84, typ: NTI83002, name: "map", len: 0, sons: null}, 
"85": {kind: 1, offset: 85, typ: NTI83002, name: "area", len: 0, sons: null}, 
"86": {kind: 1, offset: 86, typ: NTI83002, name: "svg", len: 0, sons: null}, 
"87": {kind: 1, offset: 87, typ: NTI83002, name: "math", len: 0, sons: null}, 
"88": {kind: 1, offset: 88, typ: NTI83002, name: "table", len: 0, sons: null}, 
"89": {kind: 1, offset: 89, typ: NTI83002, name: "caption", len: 0, sons: null}, 
"90": {kind: 1, offset: 90, typ: NTI83002, name: "colgroup", len: 0, sons: null}, 
"91": {kind: 1, offset: 91, typ: NTI83002, name: "col", len: 0, sons: null}, 
"92": {kind: 1, offset: 92, typ: NTI83002, name: "tbody", len: 0, sons: null}, 
"93": {kind: 1, offset: 93, typ: NTI83002, name: "thead", len: 0, sons: null}, 
"94": {kind: 1, offset: 94, typ: NTI83002, name: "tfoot", len: 0, sons: null}, 
"95": {kind: 1, offset: 95, typ: NTI83002, name: "tr", len: 0, sons: null}, 
"96": {kind: 1, offset: 96, typ: NTI83002, name: "td", len: 0, sons: null}, 
"97": {kind: 1, offset: 97, typ: NTI83002, name: "th", len: 0, sons: null}, 
"98": {kind: 1, offset: 98, typ: NTI83002, name: "form", len: 0, sons: null}, 
"99": {kind: 1, offset: 99, typ: NTI83002, name: "fieldset", len: 0, sons: null}, 
"100": {kind: 1, offset: 100, typ: NTI83002, name: "legend", len: 0, sons: null}, 
"101": {kind: 1, offset: 101, typ: NTI83002, name: "label", len: 0, sons: null}, 
"102": {kind: 1, offset: 102, typ: NTI83002, name: "input", len: 0, sons: null}, 
"103": {kind: 1, offset: 103, typ: NTI83002, name: "button", len: 0, sons: null}, 
"104": {kind: 1, offset: 104, typ: NTI83002, name: "select", len: 0, sons: null}, 
"105": {kind: 1, offset: 105, typ: NTI83002, name: "datalist", len: 0, sons: null}, 
"106": {kind: 1, offset: 106, typ: NTI83002, name: "optgroup", len: 0, sons: null}, 
"107": {kind: 1, offset: 107, typ: NTI83002, name: "option", len: 0, sons: null}, 
"108": {kind: 1, offset: 108, typ: NTI83002, name: "textarea", len: 0, sons: null}, 
"109": {kind: 1, offset: 109, typ: NTI83002, name: "keygen", len: 0, sons: null}, 
"110": {kind: 1, offset: 110, typ: NTI83002, name: "output", len: 0, sons: null}, 
"111": {kind: 1, offset: 111, typ: NTI83002, name: "progress", len: 0, sons: null}, 
"112": {kind: 1, offset: 112, typ: NTI83002, name: "meter", len: 0, sons: null}, 
"113": {kind: 1, offset: 113, typ: NTI83002, name: "details", len: 0, sons: null}, 
"114": {kind: 1, offset: 114, typ: NTI83002, name: "summary", len: 0, sons: null}, 
"115": {kind: 1, offset: 115, typ: NTI83002, name: "command", len: 0, sons: null}, 
"116": {kind: 1, offset: 116, typ: NTI83002, name: "menu", len: 0, sons: null}}};
NTI83002.node = NNI83002;
NTI83482.base = NTI83468;
NTI83484.base = NTI28040;
var NNI83121 = {kind: 2, offset: 0, typ: null, name: null, len: 28, sons: {"0": {kind: 1, offset: 0, typ: NTI83121, name: "onclick", len: 0, sons: null}, 
"1": {kind: 1, offset: 1, typ: NTI83121, name: "oncontextmenu", len: 0, sons: null}, 
"2": {kind: 1, offset: 2, typ: NTI83121, name: "ondblclick", len: 0, sons: null}, 
"3": {kind: 1, offset: 3, typ: NTI83121, name: "onkeyup", len: 0, sons: null}, 
"4": {kind: 1, offset: 4, typ: NTI83121, name: "onkeydown", len: 0, sons: null}, 
"5": {kind: 1, offset: 5, typ: NTI83121, name: "onkeypressed", len: 0, sons: null}, 
"6": {kind: 1, offset: 6, typ: NTI83121, name: "onfocus", len: 0, sons: null}, 
"7": {kind: 1, offset: 7, typ: NTI83121, name: "onblur", len: 0, sons: null}, 
"8": {kind: 1, offset: 8, typ: NTI83121, name: "onchange", len: 0, sons: null}, 
"9": {kind: 1, offset: 9, typ: NTI83121, name: "onscroll", len: 0, sons: null}, 
"10": {kind: 1, offset: 10, typ: NTI83121, name: "onmousedown", len: 0, sons: null}, 
"11": {kind: 1, offset: 11, typ: NTI83121, name: "onmouseenter", len: 0, sons: null}, 
"12": {kind: 1, offset: 12, typ: NTI83121, name: "onmouseleave", len: 0, sons: null}, 
"13": {kind: 1, offset: 13, typ: NTI83121, name: "onmousemove", len: 0, sons: null}, 
"14": {kind: 1, offset: 14, typ: NTI83121, name: "onmouseout", len: 0, sons: null}, 
"15": {kind: 1, offset: 15, typ: NTI83121, name: "onmouseover", len: 0, sons: null}, 
"16": {kind: 1, offset: 16, typ: NTI83121, name: "onmouseup", len: 0, sons: null}, 
"17": {kind: 1, offset: 17, typ: NTI83121, name: "ondrag", len: 0, sons: null}, 
"18": {kind: 1, offset: 18, typ: NTI83121, name: "ondragend", len: 0, sons: null}, 
"19": {kind: 1, offset: 19, typ: NTI83121, name: "ondragenter", len: 0, sons: null}, 
"20": {kind: 1, offset: 20, typ: NTI83121, name: "ondragleave", len: 0, sons: null}, 
"21": {kind: 1, offset: 21, typ: NTI83121, name: "ondragover", len: 0, sons: null}, 
"22": {kind: 1, offset: 22, typ: NTI83121, name: "ondragstart", len: 0, sons: null}, 
"23": {kind: 1, offset: 23, typ: NTI83121, name: "ondrop", len: 0, sons: null}, 
"24": {kind: 1, offset: 24, typ: NTI83121, name: "onsubmit", len: 0, sons: null}, 
"25": {kind: 1, offset: 25, typ: NTI83121, name: "oninput", len: 0, sons: null}, 
"26": {kind: 1, offset: 26, typ: NTI83121, name: "onkeyupenter", len: 0, sons: null}, 
"27": {kind: 1, offset: 27, typ: NTI83121, name: "onkeyuplater", len: 0, sons: null}}};
NTI83121.node = NNI83121;
var NNI83487 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI83121, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI83520, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI83524, name: "Field2", sons: null}]};
NTI83487.node = NNI83487;
NTI83486.base = NTI83487;
var NNI62062 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI62062.node = NNI62062;
NTI62063.base = NTI62062;
var NNI83476 = {kind: 2, len: 10, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "kind", len: 0, typ: NTI83002, name: "kind", sons: null}, 
{kind: 1, offset: "key", len: 0, typ: NTI83466, name: "key", sons: null}, 
{kind: 1, offset: "id", len: 0, typ: NTI28040, name: "id", sons: null}, 
{kind: 1, offset: "class", len: 0, typ: NTI28040, name: "class", sons: null}, 
{kind: 1, offset: "text", len: 0, typ: NTI28040, name: "text", sons: null}, 
{kind: 1, offset: "kids", len: 0, typ: NTI83482, name: "kids", sons: null}, 
{kind: 1, offset: "attrs", len: 0, typ: NTI83484, name: "attrs", sons: null}, 
{kind: 1, offset: "events", len: 0, typ: NTI83486, name: "events", sons: null}, 
{kind: 1, offset: "style", len: 0, typ: NTI62063, name: "style", sons: null}, 
{kind: 1, offset: "dom", len: 0, typ: NTI53220, name: "dom", sons: null}]};
NTI83476.node = NNI83476;
NTI83476.base = NTI31208;
NTI83468.base = NTI83476;
var NNI98024 = {kind: 2, len: 4, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "k", len: 0, typ: NTI98022, name: "k", sons: null}, 
{kind: 1, offset: "parent", len: 0, typ: NTI53220, name: "parent", sons: null}, 
{kind: 1, offset: "current", len: 0, typ: NTI53220, name: "current", sons: null}, 
{kind: 1, offset: "n", len: 0, typ: NTI83468, name: "n", sons: null}]};
NTI98024.node = NNI98024;
var NNI98026 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI83468, name: "parent", sons: null}, 
{kind: 1, offset: "newChild", len: 0, typ: NTI83468, name: "newChild", sons: null}, 
{kind: 1, offset: "pos", len: 0, typ: NTI28004, name: "pos", sons: null}]};
NTI98026.node = NNI98026;

function setConstr() {
		      var result = {};
      for (var i = 0; i < arguments.length; ++i) {
        var x = arguments[i];
        if (typeof(x) == "object") {
          for (var j = x[0]; j <= x[1]; ++j) {
            result[j] = true;
          }
        } else {
          result[x] = true;
        }
      }
      return result;
    

	
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_47417, src_47418, ti_47419) {
	var result_47829 = null;

		switch (ti_47419.kind) {
		case 21:
		case 22:
		case 23:
		case 5:
			if (!(isFatPointer_47401(ti_47419))) {
			result_47829 = src_47418;
			}
			else {
				result_47829 = [src_47418[0], src_47418[1]];
			}
			
			break;
		case 19:
			      if (dest_47417 === null || dest_47417 === undefined) {
        dest_47417 = {};
      }
      else {
        for (var key in dest_47417) { delete dest_47417[key]; }
      }
      for (var key in src_47418) { dest_47417[key] = src_47418[key]; }
      result_47829 = dest_47417;
    
			break;
		case 18:
		case 17:
			if (!((ti_47419.base == null))) {
			result_47829 = nimCopy(dest_47417, src_47418, ti_47419.base);
			}
			else {
			if ((ti_47419.kind == 17)) {
			result_47829 = (dest_47417 === null || dest_47417 === undefined) ? {m_type: ti_47419} : dest_47417;
			}
			else {
				result_47829 = (dest_47417 === null || dest_47417 === undefined) ? {} : dest_47417;
			}
			}
			nimCopyAux(result_47829, src_47418, ti_47419.node);
			break;
		case 24:
		case 4:
		case 27:
		case 16:
			      if (src_47418 === null) {
        result_47829 = null;
      }
      else {
        if (dest_47417 === null || dest_47417 === undefined) {
          dest_47417 = new Array(src_47418.length);
        }
        else {
          dest_47417.length = src_47418.length;
        }
        result_47829 = dest_47417;
        for (var i = 0; i < src_47418.length; ++i) {
          result_47829[i] = nimCopy(result_47829[i], src_47418[i], ti_47419.base);
        }
      }
    
			break;
		case 28:
			      if (src_47418 !== null) {
        result_47829 = src_47418.slice(0);
      }
    
			break;
		default: 
			result_47829 = src_47418;
			break;
		}

	return result_47829;

}

function makeNimstrLit(c_42203) {
		    var ln = c_42203.length;
    var result = new Array(ln + 1);
    var i = 0;
    for (; i < ln; ++i) {
      result[i] = c_42203.charCodeAt(i);
    }
    result[i] = 0; // terminating zero
    return result;
    

	
}

function eqStrings(a_44803, b_44804) {
		    if (a_44803 == b_44804) return true;
    if ((!a_44803) || (!b_44804)) return false;
    var alen = a_44803.length;
    if (alen != b_44804.length) return false;
    for (var i = 0; i < alen; ++i)
      if (a_44803[i] != b_44804[i]) return false;
    return true;
  

	
}

function arrayConstr(len_47864, value_47865, typ_47866) {
		      var result = new Array(len_47864);
      for (var i = 0; i < len_47864; ++i) result[i] = nimCopy(null, value_47865, typ_47866);
      return result;
    

	
}

function cstrToNimstr(c_42403) {
		  var ln = c_42403.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_42403.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else if((ch > 127) && (ch < 2048)) {
      result[r] = (ch >> 6) | 192;
      ++r;
      result[r] = (ch & 63) | 128;
    }
    else {
      result[r] = (ch >> 12) | 224;
      ++r;
      result[r] = ((ch >> 6) & 63) | 128;
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  result[r] = 0; // terminating zero
  return result;
  

	
}

function toJSStr(s_42603) {
		    var len = s_42603.length-1;
    var asciiPart = new Array(len);
    var fcc = String.fromCharCode;
    var nonAsciiPart = null;
    var nonAsciiOffset = 0;
    for (var i = 0; i < len; ++i) {
      if (nonAsciiPart !== null) {
        var offset = (i - nonAsciiOffset) * 2;
        var code = s_42603[i].toString(16);
        if (code.length == 1) {
          code = "0"+code;
        }
        nonAsciiPart[offset] = "%";
        nonAsciiPart[offset + 1] = code;
      }
      else if (s_42603[i] < 128)
        asciiPart[i] = fcc(s_42603[i]);
      else {
        asciiPart.length = i;
        nonAsciiOffset = i;
        nonAsciiPart = new Array((len - i) * 2);
        --i;
      }
    }
    asciiPart = asciiPart.join("");
    return (nonAsciiPart === null) ?
        asciiPart : asciiPart + decodeURIComponent(nonAsciiPart.join(""));
  

	
}

function raiseException(e_41606, ename_41607) {
		e_41606.name = ename_41607;
		if ((excHandler == 0)) {
		unhandledException(e_41606);
		}
		
		e_41606.trace = nimCopy(null, rawWriteStackTrace_41428(), NTI28038);
		throw e_41606;

	
}

function addInt(a_45003, b_45004) {
		      var result = a_45003 + b_45004;
      if (result > 2147483647 || result < -2147483648) raiseOverflow();
      return result;
    

	
}
			var toTag_83449 = nimCopy(null, ["#text", "#int", "#bool", "#vthunk", "#dthunk", "#component", "HTML", "HEAD", "TITLE", "BASE", "LINK", "META", "STYLE", "SCRIPT", "NOSCRIPT", "BODY", "SECTION", "NAV", "ARTICLE", "ASIDE", "H1", "H2", "H3", "H4", "H5", "H6", "HEADER", "FOOTER", "ADDRESS", "MAIN", "P", "HR", "PRE", "BLOCKQUOTE", "OL", "UL", "LI", "DL", "DT", "DD", "FIGURE", "FIGCAPTION", "DIV", "A", "EM", "STRONG", "SMALL", "S", "CITE", "QUOTE", "DFN", "ABBR", "DATA", "TIME", "CODE", "VAR", "SAMP", "KDB", "SUB", "SUP", "I", "B", "U", "MARK", "RUBY", "RT", "RP", "BDI", "DBO", "SPAN", "BR", "WBR", "INS", "DEL", "IMG", "IFRAME", "EMBED", "OBJECT", "PARAM", "VIDEO", "AUDIO", "SOURCE", "TRACK", "CANVAS", "MAP", "AREA", "SVG", "MATH", "TABLE", "CAPTION", "COLGROUP", "COL", "TBODY", "THEAD", "TFOOT", "TR", "TD", "TH", "FORM", "FIELDSET", "LEGEND", "LABEL", "INPUT", "BUTTON", "SELECT", "DATALIST", "OPTGROUP", "OPTION", "TEXTAREA", "KEYGEN", "OUTPUT", "PROGRESS", "METER", "DETAILS", "SUMMARY", "COMMAND", "MENU"], NTI83452);

function chckIndx(i_48003, a_48004, b_48005) {
			var Tmp1;

	var result_48006 = 0;

	BeforeRet: do {
			if (!(a_48004 <= i_48003)) Tmp1 = false; else {				Tmp1 = (i_48003 <= b_48005);			}		if (Tmp1) {
		result_48006 = i_48003;
		break BeforeRet;
		}
		else {
		raiseIndexError();
		}
		
	} while (false);

	return result_48006;

}

function subInt(a_45203, b_45204) {
		      var result = a_45203 - b_45204;
      if (result > 2147483647 || result < -2147483648) raiseOverflow();
      return result;
    

	
}
			var toEventName_83455 = nimCopy(null, ["click", "contextmenu", "dblclick", "keyup", "keydown", "keypressed", "focus", "blur", "change", "scroll", "mousedown", "mouseenter", "mouseleave", "mousemove", "mouseout", "mouseover", "mouseup", "drag", "dragend", "dragenter", "dragleave", "dragover", "dragstart", "drop", "submit", "input", "keyupenter", "keyuplater"], NTI83458);

function nimMin(a_47039, b_47040) {
		var Tmp1;

	var result_47041 = 0;

	BeforeRet: do {
		if ((a_47039 <= b_47040)) {
		Tmp1 = a_47039;
		}
		else {
		Tmp1 = b_47040;
		}
		
		result_47041 = Tmp1;
		break BeforeRet;
	} while (false);

	return result_47041;

}
var nimvm_33687 = false;
var nim_program_result = 0;
var globalRaiseHook_39205 = [null];
var localRaiseHook_39210 = [null];
var outOfMemHook_39213 = [null];
var gid_83694 = [0];
var objectID_85232 = [0];
var vcomponents_92014 = [{}];
var dcomponents_92028 = [{}];
var kxi_98083 = [null];

function isFatPointer_47401(ti_47403) {
	var result_47404 = false;

	BeforeRet: do {
		result_47404 = !((ConstSet1[ti_47403.base.kind] != undefined));
		break BeforeRet;
	} while (false);

	return result_47404;

}

function nimCopyAux(dest_47422, src_47423, n_47425) {
		switch (n_47425.kind) {
		case 0:
			break;
		case 1:
			      dest_47422[n_47425.offset] = nimCopy(dest_47422[n_47425.offset], src_47423[n_47425.offset], n_47425.typ);
    
			break;
		case 2:
			L1: do {
				var i_47815 = 0;
				var colontmp__47817 = 0;
				colontmp__47817 = (n_47425.len - 1);
				var res_47820 = 0;
				L2: do {
						L3: while (true) {
						if (!(res_47820 <= colontmp__47817)) break L3;
							i_47815 = res_47820;
							nimCopyAux(dest_47422, src_47423, n_47425.sons[i_47815]);
							res_47820 += 1;
						}
				} while(false);
			} while(false);
			break;
		case 3:
			      dest_47422[n_47425.offset] = nimCopy(dest_47422[n_47425.offset], src_47423[n_47425.offset], n_47425.typ);
      for (var i = 0; i < n_47425.sons.length; ++i) {
        nimCopyAux(dest_47422, src_47423, n_47425.sons[i][1]);
      }
    
			break;
		}

	
}

function newSeq_102037(len_102041) {
	var result_102043 = null;

	var F={procname:"newSeq.newSeq",prev:framePtr,filename:"lib/system.nim",line:0};
	framePtr = F;
		F.line = 696;
		result_102043 = new Array(len_102041); for (var i=0;i<len_102041;++i) {result_102043[i]={k: 0, parent: null, current: null, n: null};}	framePtr = F.prev;

	return result_102043;

}

function newSeq_102076(len_102080) {
	var result_102082 = null;

	var F={procname:"newSeq.newSeq",prev:framePtr,filename:"lib/system.nim",line:0};
	framePtr = F;
		F.line = 696;
		result_102082 = new Array(len_102080); for (var i=0;i<len_102080;++i) {result_102082[i]={parent: null, newChild: null, pos: 0};}	framePtr = F.prev;

	return result_102082;

}

function add_39229(x_39232, x_39232_Idx, y_39233) {
		        var len = x_39232[0].length-1;
        for (var i = 0; i < y_39233.length; ++i) {
          x_39232[0][len] = y_39233.charCodeAt(i);
          ++len;
        }
        x_39232[0][len] = 0
      

	
}

function auxWriteStackTrace_41204(f_41206) {
					var Tmp3;

	var result_41207 = [null];

		var it_41215 = f_41206;
		var i_41216 = 0;
		var total_41217 = 0;
		var tempFrames_41221 = arrayConstr(64, {Field0: null, Field1: 0}, NTI41209);
		L1: do {
				L2: while (true) {
					if (!!((it_41215 == null))) Tmp3 = false; else {						Tmp3 = (i_41216 <= 63);					}				if (!Tmp3) break L2;
					tempFrames_41221[i_41216].Field0 = it_41215.procname;
					tempFrames_41221[i_41216].Field1 = it_41215.line;
					i_41216 += 1;
					total_41217 += 1;
					it_41215 = it_41215.prev;
				}
		} while(false);
		L4: do {
				L5: while (true) {
				if (!!((it_41215 == null))) break L5;
					total_41217 += 1;
					it_41215 = it_41215.prev;
				}
		} while(false);
		result_41207[0] = nimCopy(null, makeNimstrLit(""), NTI28038);
		if (!((total_41217 == i_41216))) {
		if (result_41207[0] != null) { result_41207[0] = (result_41207[0].slice(0, -1)).concat(makeNimstrLit("(")); } else { result_41207[0] = makeNimstrLit("(");};
		if (result_41207[0] != null) { result_41207[0] = (result_41207[0].slice(0, -1)).concat(cstrToNimstr(((total_41217 - i_41216))+"")); } else { result_41207[0] = cstrToNimstr(((total_41217 - i_41216))+"");};
		if (result_41207[0] != null) { result_41207[0] = (result_41207[0].slice(0, -1)).concat(makeNimstrLit(" calls omitted) ...\x0A")); } else { result_41207[0] = makeNimstrLit(" calls omitted) ...\x0A");};
		}
		
		L6: do {
			var j_41415 = 0;
			var colontmp__41421 = 0;
			colontmp__41421 = (i_41216 - 1);
			var res_41424 = colontmp__41421;
			L7: do {
					L8: while (true) {
					if (!(0 <= res_41424)) break L8;
						j_41415 = res_41424;
						add_39229(result_41207, 0, tempFrames_41221[j_41415].Field0);
						if ((0 < tempFrames_41221[j_41415].Field1)) {
						if (result_41207[0] != null) { result_41207[0] = (result_41207[0].slice(0, -1)).concat(makeNimstrLit(", line: ")); } else { result_41207[0] = makeNimstrLit(", line: ");};
						if (result_41207[0] != null) { result_41207[0] = (result_41207[0].slice(0, -1)).concat(cstrToNimstr((tempFrames_41221[j_41415].Field1)+"")); } else { result_41207[0] = cstrToNimstr((tempFrames_41221[j_41415].Field1)+"");};
						}
						
						if (result_41207[0] != null) { result_41207[0] = (result_41207[0].slice(0, -1)).concat(makeNimstrLit("\x0A")); } else { result_41207[0] = makeNimstrLit("\x0A");};
						res_41424 -= 1;
					}
			} while(false);
		} while(false);

	return result_41207[0];

}

function rawWriteStackTrace_41428() {
	var result_41430 = null;

		if (!((framePtr == null))) {
		result_41430 = nimCopy(null, (makeNimstrLit("Traceback (most recent call last)\x0A").slice(0,-1)).concat(auxWriteStackTrace_41204(framePtr)), NTI28038);
		}
		else {
			result_41430 = nimCopy(null, makeNimstrLit("No stack traceback available\x0A"), NTI28038);
		}
		

	return result_41430;

}

function unhandledException(e_41453) {
			var Tmp1;

		var buf_41454 = [makeNimstrLit("")];
			if (!!(eqStrings(e_41453.message, null))) Tmp1 = false; else {				Tmp1 = !((e_41453.message[0] == 0));			}		if (Tmp1) {
		if (buf_41454[0] != null) { buf_41454[0] = (buf_41454[0].slice(0, -1)).concat(makeNimstrLit("Error: unhandled exception: ")); } else { buf_41454[0] = makeNimstrLit("Error: unhandled exception: ");};
		if (buf_41454[0] != null) { buf_41454[0] = (buf_41454[0].slice(0, -1)).concat(e_41453.message); } else { buf_41454[0] = e_41453.message;};
		}
		else {
		if (buf_41454[0] != null) { buf_41454[0] = (buf_41454[0].slice(0, -1)).concat(makeNimstrLit("Error: unhandled exception")); } else { buf_41454[0] = makeNimstrLit("Error: unhandled exception");};
		}
		
		if (buf_41454[0] != null) { buf_41454[0] = (buf_41454[0].slice(0, -1)).concat(makeNimstrLit(" [")); } else { buf_41454[0] = makeNimstrLit(" [");};
		add_39229(buf_41454, 0, e_41453.name);
		if (buf_41454[0] != null) { buf_41454[0] = (buf_41454[0].slice(0, -1)).concat(makeNimstrLit("]\x0A")); } else { buf_41454[0] = makeNimstrLit("]\x0A");};
		if (buf_41454[0] != null) { buf_41454[0] = (buf_41454[0].slice(0, -1)).concat(rawWriteStackTrace_41428()); } else { buf_41454[0] = rawWriteStackTrace_41428();};
		var cbuf_41601 = toJSStr(buf_41454[0]);
		framePtr = null;
		  if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_41601);
  }
  else {
    throw cbuf_41601;
  }
  

	
}

function raiseOverflow() {
		var e_42040 = null;
		e_42040 = {m_type: NTI31242, parent: null, name: null, message: null, trace: null};
		e_42040.message = nimCopy(null, makeNimstrLit("over- or underflow"), NTI28038);
		e_42040.parent = null;
		raiseException(e_42040, "OverflowError");

	
}

function sysFatal_50021(message_50027) {
	var F={procname:"sysFatal.sysFatal",prev:framePtr,filename:"lib/system.nim",line:0};
	framePtr = F;
		F.line = 2703;
		var e_50029 = null;
		F.line = 2704;
		e_50029 = {m_type: NTI31246, parent: null, name: null, message: null, trace: null};
		F.line = 2705;
		e_50029.message = nimCopy(null, message_50027, NTI28038);
		F.line = 2706;
		raiseException(e_50029, "AssertionError");
	framePtr = F.prev;

	
}

function raiseAssert_50016(msg_50018) {
	var F={procname:"system.raiseAssert",prev:framePtr,filename:"lib/system.nim",line:0};
	framePtr = F;
		F.line = 3586;
		sysFatal_50021(msg_50018);
	framePtr = F.prev;

	
}

function failedAssertImpl_50039(msg_50041) {
	var F={procname:"system.failedAssertImpl",prev:framePtr,filename:"lib/system.nim",line:0};
	framePtr = F;
		F.line = 3594;
		raiseAssert_50016(msg_50041);
	framePtr = F.prev;

	
}

function raiseIndexError() {
		var e_42094 = null;
		e_42094 = {m_type: NTI31254, parent: null, name: null, message: null, trace: null};
		e_42094.message = nimCopy(null, makeNimstrLit("index out of bounds"), NTI28038);
		e_42094.parent = null;
		raiseException(e_42094, "IndexError");

	
}

function valueeq__83575(n_83577, v_83578) {
	var F={procname:"vdom.value=",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
		F.line = 141;
		n_83577.text = v_83578;
	framePtr = F.prev;

	
}

function value_83571(n_83573) {
	var result_83574 = null;

	var F={procname:"vdom.value",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
		F.line = 140;
		result_83574 = n_83573.text;
	framePtr = F.prev;

	return result_83574;

}

function wrapEvent_98111(d_98113, n_98114, k_98115, action_98116) {

			function laterWrapper_98165() {

					function colonanonymous__98171(ev_98173) {

							function wrapper_98174() {
								var F={procname:":anonymous.wrapper",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
								framePtr = F;
									F.line = 65;
									var v_98179 = ev_98173.target.value;
									F.line = 66;
									valueeq__83575(n_98169, v_98179);
									F.line = 67;
									action_98168(ev_98173, n_98169);
									if (!((value_83571(n_98169) == v_98179))) {
									F.line = 69;
									ev_98173.target.value = value_83571(n_98169);
									}
									
								framePtr = F.prev;

								
							}

						var F={procname:"laterWrapper.:anonymous",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
						framePtr = F;
							if (!((timer_98170 == null))) {
							F.line = 95;
							clearTimeout(timer_98170);
							}
							
							F.line = 96;
							timer_98170 = setTimeout(wrapper_98174, 400);
						framePtr = F.prev;

						
					}

				var result_98167 = null;

				var F={procname:"wrapEvent.laterWrapper",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
				framePtr = F;
					F.line = 90;
					var action_98168 = action_98116;
					F.line = 91;
					var n_98169 = n_98114;
					F.line = 92;
					var timer_98170 = null;
					F.line = 93;
					result_98167 = colonanonymous__98171;
				framePtr = F.prev;

				return result_98167;

			}

			function enterWrapper_98150() {

					function colonanonymous__98155(ev_98157) {
						var F={procname:"enterWrapper.:anonymous",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
						framePtr = F;
							if ((ev_98157.keyCode == 13)) {
							F.line = 65;
							var v_98162 = ev_98157.target.value;
							F.line = 66;
							valueeq__83575(n_98154, v_98162);
							F.line = 67;
							action_98153(ev_98157, n_98154);
							if (!((value_83571(n_98154) == v_98162))) {
							F.line = 69;
							ev_98157.target.value = value_83571(n_98154);
							}
							
							}
							
						framePtr = F.prev;

						
					}

				var result_98152 = null;

				var F={procname:"wrapEvent.enterWrapper",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
				framePtr = F;
					F.line = 84;
					var action_98153 = action_98116;
					F.line = 85;
					var n_98154 = n_98114;
					F.line = 86;
					result_98152 = colonanonymous__98155;
				framePtr = F.prev;

				return result_98152;

			}

			function stdWrapper_98118() {

					function colonanonymous__98123(ev_98125) {
								var Tmp1;

						var F={procname:"stdWrapper.:anonymous",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
						framePtr = F;
								if ((n_98122.kind == 108)) Tmp1 = true; else {									Tmp1 = (n_98122.kind == 102);								}							if (Tmp1) {
							F.line = 65;
							var v_98147 = ev_98125.target.value;
							F.line = 66;
							valueeq__83575(n_98122, v_98147);
							F.line = 67;
							action_98121(ev_98125, n_98122);
							if (!((value_83571(n_98122) == v_98147))) {
							F.line = 69;
							ev_98125.target.value = value_83571(n_98122);
							}
							
							}
							else {
								F.line = 81;
							action_98121(ev_98125, n_98122);
							}
							
						framePtr = F.prev;

						
					}

				var result_98120 = null;

				var F={procname:"wrapEvent.stdWrapper",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
				framePtr = F;
					F.line = 76;
					var action_98121 = action_98116;
					F.line = 77;
					var n_98122 = n_98114;
					F.line = 78;
					result_98120 = colonanonymous__98123;
				framePtr = F.prev;

				return result_98120;

			}

	var result_98117 = null;

	var F={procname:"karax.wrapEvent",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		F.line = 98;
		switch (k_98115) {
		case 27:
			F.line = 100;
			result_98117 = laterWrapper_98165();
			F.line = 101;
			d_98113.addEventListener("keyup", result_98117, false);
			break;
		case 26:
			F.line = 103;
			result_98117 = enterWrapper_98150();
			F.line = 104;
			d_98113.addEventListener("keyup", result_98117, false);
			break;
		default: 
			F.line = 106;
			result_98117 = stdWrapper_98118();
			F.line = 107;
			d_98113.addEventListener(toEventName_83455[chckIndx(k_98115, 0, toEventName_83455.length-1)-0], result_98117, false);
			break;
		}
	framePtr = F.prev;

	return result_98117;

}

function applyEvents_98205(n_98207, kxi_98208) {
	var F={procname:"karax.applyEvents",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		F.line = 118;
		var dest_98209 = n_98207.dom;
		L1: do {
			F.line = 119;
			var i_98226 = 0;
			F.line = 3812;
			var colontmp__98228 = 0;
			F.line = 119;
			colontmp__98228 = (n_98207.events != null ? n_98207.events.length : 0);
			F.line = 3813;
			var i_98231 = 0;
			L2: do {
				F.line = 3814;
					L3: while (true) {
					if (!(i_98231 < colontmp__98228)) break L3;
						F.line = 3815;
						i_98226 = i_98231;
						F.line = 120;
						n_98207.events[chckIndx(i_98226, 0, n_98207.events.length-1)-0]["Field2"] = wrapEvent_98111(dest_98209, n_98207, n_98207.events[chckIndx(i_98226, 0, n_98207.events.length-1)-0]["Field0"], n_98207.events[chckIndx(i_98226, 0, n_98207.events.length-1)-0]["Field1"]);
						F.line = 3816;
						i_98231 = addInt(i_98231, 1);
					}
			} while(false);
		} while(false);
	framePtr = F.prev;

	
}

function applyStyle_64308(n_64310, s_64311) {
	var F={procname:"vstyles.applyStyle",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vstyles.nim",line:0};
	framePtr = F;
		F.line = 290;
		n_64310.style = {};
		L1: do {
			F.line = 291;
			var i_64347 = 0;
			F.line = 1965;
			var colontmp__64381 = 0;
			F.line = 291;
			colontmp__64381 = subInt(s_64311.length, 1);
			F.line = 1955;
			var res_64384 = 0;
			L2: do {
				F.line = 1956;
					L3: while (true) {
					if (!(res_64384 <= colontmp__64381)) break L3;
						F.line = 1957;
						i_64347 = res_64384;
						F.line = 292;
						n_64310.style[s_64311[i_64347]] = s_64311[addInt(i_64347, 1)];
						F.line = 1971;
						res_64384 = addInt(res_64384, 2);
					}
			} while(false);
		} while(false);
	framePtr = F.prev;

	
}

function vnodeToDom_98234(n_98236, kxi_98237) {
			var Tmp9;

	var result_98238 = null;

	var F={procname:"karax.vnodeToDom",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if ((n_98236.kind == 0)) {
		F.line = 124;
		result_98238 = document.createTextNode(n_98236.text);
		F.line = 125;
		n_98236.dom = result_98238;
		}
		else {
		if ((n_98236.kind == 3)) {
		F.line = 127;
		var x_98274 = vcomponents_92014[0][n_98236.text](n_98236.kids);
		F.line = 128;
		result_98238 = vnodeToDom_98234(x_98274, kxi_98237);
		F.line = 130;
		n_98236.dom = result_98238;
		F.line = 131;
		break BeforeRet;
		}
		else {
		if ((n_98236.kind == 4)) {
		F.line = 133;
		result_98238 = dcomponents_92028[0][n_98236.text](n_98236.kids);
		F.line = 135;
		n_98236.dom = result_98238;
		F.line = 136;
		break BeforeRet;
		}
		else {
		if ((n_98236.kind == 5)) {
		F.line = 138;
		var x_98310 = n_98236;
		if (!((x_98310.onAttachImpl == null))) {
		F.line = 139;
		x_98310.onAttachImpl(x_98310);
		}
		
		if (!(!((x_98310.renderImpl == null)))) {
		F.line = 140;
		failedAssertImpl_50039(makeNimstrLit("\x0A  not (x.renderImpl == nil) "));
		}
		
		if ((x_98310.expanded == null)) {
		F.line = 142;
		x_98310.expanded = x_98310.renderImpl(x_98310);
		}
		
		if (!(!((x_98310.expanded == null)))) {
		F.line = 144;
		failedAssertImpl_50039(makeNimstrLit("\x0A  not (x.expanded == nil) "));
		}
		
		F.line = 145;
		result_98238 = vnodeToDom_98234(x_98310.expanded, kxi_98237);
		F.line = 146;
		n_98236.dom = result_98238;
		F.line = 147;
		break BeforeRet;
		}
		else {
			F.line = 149;
			result_98238 = document.createElement(toTag_83449[chckIndx(n_98236.kind, 0, toTag_83449.length-1)-0]);
			F.line = 150;
			n_98236.dom = result_98238;
			L1: do {
				F.line = 151;
				var k_98601 = null;
				L2: do {
					F.line = 221;
					var i_98632 = 0;
					F.line = 3812;
					var colontmp__98634 = 0;
					F.line = 221;
					colontmp__98634 = (n_98236.kids != null ? n_98236.kids.length : 0);
					F.line = 3813;
					var i_98636 = 0;
					L3: do {
						F.line = 3814;
							L4: while (true) {
							if (!(i_98636 < colontmp__98634)) break L4;
								F.line = 3815;
								i_98632 = i_98636;
								F.line = 221;
								k_98601 = n_98236.kids[chckIndx(i_98632, 0, n_98236.kids.length-1)-0];
								F.line = 152;
								result_98238.appendChild(vnodeToDom_98234(k_98601, kxi_98237));
								F.line = 3816;
								i_98636 = addInt(i_98636, 1);
							}
					} while(false);
				} while(false);
			} while(false);
			if (!((n_98236.text == null))) {
			F.line = 155;
			result_98238.value = n_98236.text;
			}
			
		}
		}}}
		if (!((n_98236.id == null))) {
		F.line = 157;
		result_98238.id = n_98236.id;
		}
		
		if (!((n_98236.class == null))) {
		F.line = 159;
		result_98238.className = n_98236.class;
		}
		
		L5: do {
			F.line = 162;
			var k_98602 = null;
			F.line = 162;
			var v_98603 = null;
			L6: do {
				F.line = 224;
				var i_98641 = 0;
				F.line = 1965;
				var colontmp__98643 = 0;
				F.line = 224;
				colontmp__98643 = subInt((n_98236.attrs != null ? n_98236.attrs.length : 0), 2);
				F.line = 1955;
				var res_98645 = 0;
				L7: do {
					F.line = 1956;
						L8: while (true) {
						if (!(res_98645 <= colontmp__98643)) break L8;
							F.line = 1957;
							i_98641 = res_98645;
							F.line = 225;
							k_98602 = n_98236.attrs[chckIndx(i_98641, 0, n_98236.attrs.length-1)-0];
							F.line = 225;
							v_98603 = n_98236.attrs[chckIndx(addInt(i_98641, 1), 0, n_98236.attrs.length-1)-0];
							if (!((v_98603 == null))) {
							F.line = 164;
							result_98238.setAttribute(k_98602, v_98603);
							}
							
							F.line = 1971;
							res_98645 = addInt(res_98645, 2);
						}
				} while(false);
			} while(false);
		} while(false);
		F.line = 165;
		applyEvents_98205(n_98236, kxi_98237);
			if (!(n_98236 == kxi_98237.toFocusV)) Tmp9 = false; else {				Tmp9 = (kxi_98237.toFocus === null);			}		if (Tmp9) {
		F.line = 167;
		kxi_98237.toFocus = result_98238;
		}
		
		if (!((n_98236.style === null))) {
		F.line = 168;
		applyStyle_64308(result_98238, n_98236.style);
		}
		
	} while (false);
	framePtr = F.prev;

	return result_98238;

}

function replaceById_98720(id_98722, newTree_98723) {
	var F={procname:"karax.replaceById",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		F.line = 188;
		var x_98724 = document.getElementById(id_98722);
		F.line = 189;
		x_98724.parentNode.replaceChild(newTree_98723, x_98724);
	framePtr = F.prev;

	
}

function len_83849(x_83851) {
	var result_83852 = 0;

	var F={procname:"vdom.len",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
		F.line = 202;
		result_83852 = (x_83851.kids != null ? x_83851.kids.length : 0);
	framePtr = F.prev;

	return result_83852;

}

function X5BX5D__83860(x_83862, idx_83863) {
	var result_83864 = null;

	var F={procname:"vdom.[]",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
		F.line = 203;
		result_83864 = x_83862.kids[chckIndx(idx_83863, 0, x_83862.kids.length-1)-0];
	framePtr = F.prev;

	return result_83864;

}

function same_98650(n_98652, e_98653, nesting_98654) {
			var Tmp1;

	var result_98655 = false;

	var F={procname:"karax.same",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if ((n_98652.kind == 5)) {
		F.line = 172;
		result_98655 = same_98650(n_98652.expanded, e_98653, addInt(nesting_98654, 1));
		}
		else {
			if ((n_98652.kind == 3)) Tmp1 = true; else {				Tmp1 = (n_98652.kind == 4);			}		if (Tmp1) {
		F.line = 175;
		result_98655 = true;
		}
		else {
		if ((toTag_83449[chckIndx(n_98652.kind, 0, toTag_83449.length-1)-0] == e_98653.nodeName)) {
		F.line = 177;
		result_98655 = true;
		if (!((n_98652.kind == 0))) {
		if (!((e_98653.childNodes.length == len_83849(n_98652)))) {
		F.line = 180;
		console.log(e_98653.childNodes.length, len_83849(n_98652), toTag_83449[chckIndx(n_98652.kind, 0, toTag_83449.length-1)-0], nesting_98654);
		F.line = 181;
		result_98655 = false;
		break BeforeRet;
		}
		
		L2: do {
			F.line = 182;
			var i_98707 = 0;
			F.line = 3812;
			var colontmp__98715 = 0;
			F.line = 182;
			colontmp__98715 = len_83849(n_98652);
			F.line = 3813;
			var i_98718 = 0;
			L3: do {
				F.line = 3814;
					L4: while (true) {
					if (!(i_98718 < colontmp__98715)) break L4;
						F.line = 3815;
						i_98707 = i_98718;
						if (!(same_98650(X5BX5D__83860(n_98652, i_98707), e_98653.childNodes[i_98707], addInt(nesting_98654, 1)))) {
						F.line = 183;
						result_98655 = false;
						break BeforeRet;
						}
						
						F.line = 3816;
						i_98718 = addInt(i_98718, 1);
					}
			} while(false);
		} while(false);
		}
		
		}
		else {
			F.line = 185;
		console.log(toTag_83449[chckIndx(n_98652.kind, 0, toTag_83449.length-1)-0], e_98653.nodeName);
		}
		}}
	} while (false);
	framePtr = F.prev;

	return result_98655;

}

function sameAttrs_84032(a_84034, b_84035) {
	var result_84036 = false;

	var F={procname:"vdom.sameAttrs",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if (((a_84034.attrs != null ? a_84034.attrs.length : 0) == (b_84035.attrs != null ? b_84035.attrs.length : 0))) {
		F.line = 229;
		result_84036 = true;
		L1: do {
			F.line = 230;
			var i_84067 = 0;
			F.line = 3812;
			var colontmp__84069 = 0;
			F.line = 230;
			colontmp__84069 = (a_84034.attrs != null ? a_84034.attrs.length : 0);
			F.line = 3813;
			var i_84072 = 0;
			L2: do {
				F.line = 3814;
					L3: while (true) {
					if (!(i_84072 < colontmp__84069)) break L3;
						F.line = 3815;
						i_84067 = i_84072;
						if (!((a_84034.attrs[chckIndx(i_84067, 0, a_84034.attrs.length-1)-0] == b_84035.attrs[chckIndx(i_84067, 0, b_84035.attrs.length-1)-0]))) {
						F.line = 231;
						result_84036 = false;
						break BeforeRet;
						}
						
						F.line = 3816;
						i_84072 = addInt(i_84072, 1);
					}
			} while(false);
		} while(false);
		}
		
	} while (false);
	framePtr = F.prev;

	return result_84036;

}

function eq_63451(a_63453, b_63454) {
	var result_63455 = false;

	var F={procname:"vstyles.eq",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vstyles.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if ((a_63453 === null)) {
		if ((b_63454 === null)) {
		F.line = 220;
		result_63455 = true;
		break BeforeRet;
		}
		else {
			F.line = 221;
			result_63455 = false;
			break BeforeRet;
		}
		
		}
		else {
		if ((b_63454 === null)) {
		F.line = 222;
		result_63455 = false;
		break BeforeRet;
		}
		}
		if (!((a_63453.length == b_63454.length))) {
		F.line = 223;
		result_63455 = false;
		break BeforeRet;
		}
		
		L1: do {
			F.line = 224;
			var i_63558 = 0;
			F.line = 3812;
			var colontmp__63592 = 0;
			F.line = 224;
			colontmp__63592 = a_63453.length;
			F.line = 3813;
			var i_63595 = 0;
			L2: do {
				F.line = 3814;
					L3: while (true) {
					if (!(i_63595 < colontmp__63592)) break L3;
						F.line = 3815;
						i_63558 = i_63595;
						if (!((a_63453[i_63558] == b_63454[i_63558]))) {
						F.line = 225;
						result_63455 = false;
						break BeforeRet;
						}
						
						F.line = 3816;
						i_63595 = addInt(i_63595, 1);
					}
			} while(false);
		} while(false);
		F.line = 226;
		result_63455 = true;
		break BeforeRet;
	} while (false);
	framePtr = F.prev;

	return result_63455;

}

function eq_98732(a_98734, b_98735) {
			var Tmp1;
		var Tmp5;

	var result_98736 = 0;

	var F={procname:"karax.eq",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if (!((a_98734.kind == b_98735.kind))) {
		F.line = 196;
		result_98736 = 1;
		break BeforeRet;
		}
		
		if (!((a_98734.id == b_98735.id))) {
		F.line = 197;
		result_98736 = 1;
		break BeforeRet;
		}
		
		F.line = 198;
		result_98736 = 3;
		if (!((a_98734.key == b_98735.key))) {
		F.line = 199;
		result_98736 = 1;
		break BeforeRet;
		}
		
		if ((a_98734.kind == 0)) {
		if (!((a_98734.text == b_98735.text))) {
		F.line = 201;
		result_98736 = 1;
		break BeforeRet;
		}
		
		}
		else {
			if ((a_98734.kind == 3)) Tmp1 = true; else {				Tmp1 = (a_98734.kind == 4);			}		if (Tmp1) {
		if (!((a_98734.text == b_98735.text))) {
		F.line = 203;
		result_98736 = 1;
		break BeforeRet;
		}
		
		if (!((len_83849(a_98734) == len_83849(b_98735)))) {
		F.line = 204;
		result_98736 = 1;
		break BeforeRet;
		}
		
		L2: do {
			F.line = 205;
			var i_98781 = 0;
			F.line = 3812;
			var colontmp__99002 = 0;
			F.line = 205;
			colontmp__99002 = len_83849(a_98734);
			F.line = 3813;
			var i_99005 = 0;
			L3: do {
				F.line = 3814;
					L4: while (true) {
					if (!(i_99005 < colontmp__99002)) break L4;
						F.line = 3815;
						i_98781 = i_99005;
						if ((eq_98732(X5BX5D__83860(a_98734, i_98781), X5BX5D__83860(b_98735, i_98781)) == 1)) {
						F.line = 206;
						result_98736 = 1;
						break BeforeRet;
						}
						
						F.line = 3816;
						i_99005 = addInt(i_99005, 1);
					}
			} while(false);
		} while(false);
		}
		else {
		if ((b_98735.kind == 5)) {
		if (!((a_98734.text == b_98735.text))) {
		F.line = 209;
		result_98736 = 1;
		break BeforeRet;
		}
		
		F.line = 210;
		var x_98799 = b_98735;
		if (!(!((x_98799.changedImpl == null)))) {
		F.line = 211;
		failedAssertImpl_50039(makeNimstrLit("\x0A  not (x.changedImpl == nil) "));
		}
		
		F.line = 212;
		if (x_98799.changedImpl(x_98799, a_98734)) {
		Tmp5 = 0;
		}
		else {
		Tmp5 = 3;
		}
		
		result_98736 = Tmp5;
		break BeforeRet;
		}
		}}
		if (!(sameAttrs_84032(a_98734, b_98735))) {
		F.line = 213;
		result_98736 = 1;
		break BeforeRet;
		}
		
		if (!((a_98734.class == b_98735.class))) {
		F.line = 214;
		result_98736 = 1;
		break BeforeRet;
		}
		
		if (!(eq_63451(a_98734.style, b_98735.style))) {
		F.line = 215;
		result_98736 = 2;
		break BeforeRet;
		}
		
		F.line = 217;
		break BeforeRet;
	} while (false);
	framePtr = F.prev;

	return result_98736;

}

function updateStyles_99008(newNode_99010, oldNode_99011) {
	var F={procname:"karax.updateStyles",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		if (!((oldNode_99011.dom == null))) {
		if (!((newNode_99010.style == null))) {
		F.line = 222;
		applyStyle_64308(oldNode_99011.dom, newNode_99010.style);
		}
		else {
			F.line = 223;
			oldNode_99011.dom.style = {m_type: NTI53260, background: null, backgroundAttachment: null, backgroundColor: null, backgroundImage: null, backgroundPosition: null, backgroundRepeat: null, border: null, borderBottom: null, borderBottomColor: null, borderBottomStyle: null, borderBottomWidth: null, borderColor: null, borderLeft: null, borderLeftColor: null, borderLeftStyle: null, borderLeftWidth: null, borderRight: null, borderRightColor: null, borderRightStyle: null, borderRightWidth: null, borderStyle: null, borderTop: null, borderTopColor: null, borderTopStyle: null, borderTopWidth: null, borderWidth: null, bottom: null, captionSide: null, clear: null, clip: null, color: null, cursor: null, direction: null, display: null, emptyCells: null, cssFloat: null, font: null, fontFamily: null, fontSize: null, fontStretch: null, fontStyle: null, fontVariant: null, fontWeight: null, height: null, left: null, letterSpacing: null, lineHeight: null, listStyle: null, listStyleImage: null, listStylePosition: null, listStyleType: null, margin: null, marginBottom: null, marginLeft: null, marginRight: null, marginTop: null, maxHeight: null, maxWidth: null, minHeight: null, minWidth: null, overflow: null, padding: null, paddingBottom: null, paddingLeft: null, paddingRight: null, paddingTop: null, pageBreakAfter: null, pageBreakBefore: null, pointerEvents: null, position: null, right: null, scrollbar3dLightColor: null, scrollbarArrowColor: null, scrollbarBaseColor: null, scrollbarDarkshadowColor: null, scrollbarFaceColor: null, scrollbarHighlightColor: null, scrollbarShadowColor: null, scrollbarTrackColor: null, tableLayout: null, textAlign: null, textDecoration: null, textIndent: null, textTransform: null, transform: null, top: null, verticalAlign: null, visibility: null, width: null, wordSpacing: null, zIndex: 0};
		}
		
		}
		
		F.line = 224;
		oldNode_99011.style = newNode_99010.style;
	framePtr = F.prev;

	
}

function mergeEvents_99035(newNode_99037, oldNode_99038, kxi_99039) {
						var Tmp4;

	var F={procname:"karax.mergeEvents",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		F.line = 227;
		var d_99040 = oldNode_99038.dom;
		L1: do {
			F.line = 228;
			var i_99057 = 0;
			F.line = 3812;
			var colontmp__99063 = 0;
			F.line = 228;
			colontmp__99063 = (oldNode_99038.events != null ? oldNode_99038.events.length : 0);
			F.line = 3813;
			var i_99066 = 0;
			L2: do {
				F.line = 3814;
					L3: while (true) {
					if (!(i_99066 < colontmp__99063)) break L3;
						F.line = 3815;
						i_99057 = i_99066;
						F.line = 229;
						var k_99058 = oldNode_99038.events[chckIndx(i_99057, 0, oldNode_99038.events.length-1)-0]["Field0"];
						F.line = 230;
						F.line = 230;
						switch (k_99058) {
						case 27:
						case 26:
							Tmp4 = "keyup";
							break;
						default: 
							Tmp4 = toEventName_83455[chckIndx(k_99058, 0, toEventName_83455.length-1)-0];
							break;
						}
						var name_99061 = Tmp4;
						F.line = 233;
						d_99040.removeEventListener(name_99061, oldNode_99038.events[chckIndx(i_99057, 0, oldNode_99038.events.length-1)-0]["Field2"]);
						F.line = 3816;
						i_99066 = addInt(i_99066, 1);
					}
			} while(false);
		} while(false);
		F.line = 234;
		oldNode_99038.events = newNode_99037.events;
		F.line = 235;
		applyEvents_98205(oldNode_99038, kxi_99039);
	framePtr = F.prev;

	
}

function X5BX5Deq__83865(x_83867, idx_83868, y_83869) {
	var F={procname:"vdom.[]=",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
		F.line = 204;
		x_83867.kids[chckIndx(idx_83868, 0, x_83867.kids.length-1)-0] = y_83869;
	framePtr = F.prev;

	
}

function addPatchV_99172(kxi_99174, parent_99175, pos_99176, newChild_99177) {
	var F={procname:"karax.addPatchV",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		F.line = 263;
		var L_99178 = kxi_99174.patchLenV;
		if (((kxi_99174.patchesV != null ? kxi_99174.patchesV.length : 0) <= L_99178)) {
		F.line = 266;
		if (kxi_99174.patchesV != null) { kxi_99174.patchesV.push({parent: parent_99175, newChild: newChild_99177, pos: pos_99176}); } else { kxi_99174.patchesV = [{parent: parent_99175, newChild: newChild_99177, pos: pos_99176}]; };
		}
		else {
			F.line = 268;
			kxi_99174.patchesV[chckIndx(L_99178, 0, kxi_99174.patchesV.length-1)-0].parent = parent_99175;
			F.line = 269;
			kxi_99174.patchesV[chckIndx(L_99178, 0, kxi_99174.patchesV.length-1)-0].newChild = newChild_99177;
			F.line = 270;
			kxi_99174.patchesV[chckIndx(L_99178, 0, kxi_99174.patchesV.length-1)-0].pos = pos_99176;
		}
		
		F.line = 271;
		kxi_99174.patchLenV = addInt(kxi_99174.patchLenV, 1);
	framePtr = F.prev;

	
}

function addPatch_99137(kxi_99139, ka_99140, parenta_99141, currenta_99142, na_99143) {
	var F={procname:"karax.addPatch",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		F.line = 251;
		var L_99144 = kxi_99139.patchLen;
		if (((kxi_99139.patches != null ? kxi_99139.patches.length : 0) <= L_99144)) {
		F.line = 254;
		if (kxi_99139.patches != null) { kxi_99139.patches.push({k: ka_99140, parent: parenta_99141, current: currenta_99142, n: na_99143}); } else { kxi_99139.patches = [{k: ka_99140, parent: parenta_99141, current: currenta_99142, n: na_99143}]; };
		}
		else {
			F.line = 256;
			kxi_99139.patches[chckIndx(L_99144, 0, kxi_99139.patches.length-1)-0].k = ka_99140;
			F.line = 257;
			kxi_99139.patches[chckIndx(L_99144, 0, kxi_99139.patches.length-1)-0].parent = parenta_99141;
			F.line = 258;
			kxi_99139.patches[chckIndx(L_99144, 0, kxi_99139.patches.length-1)-0].current = currenta_99142;
			F.line = 259;
			kxi_99139.patches[chckIndx(L_99144, 0, kxi_99139.patches.length-1)-0].n = na_99143;
		}
		
		F.line = 260;
		kxi_99139.patchLen = addInt(kxi_99139.patchLen, 1);
	framePtr = F.prev;

	
}

function diff_99414(newNode_99416, oldNode_99417, parent_99418, current_99419, kxi_99420) {
				var Tmp1;
				var Tmp2;
			var Tmp3;
			var Tmp4;
						var Tmp7;
						var Tmp10;
						var Tmp11;

	var result_99421 = 0;

	var F={procname:"karax.diff",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		F.line = 313;
		result_99421 = eq_98732(newNode_99416, oldNode_99417);
		F.line = 314;
		switch (result_99421) {
		case 3:
		case 2:
			F.line = 316;
			newNode_99416.dom = oldNode_99417.dom;
			if ((result_99421 == 2)) {
			F.line = 317;
			updateStyles_99008(newNode_99416, oldNode_99417);
			}
			
				if (!(((newNode_99416.events != null ? newNode_99416.events.length : 0) == 0))) Tmp1 = true; else {					Tmp1 = !(((oldNode_99417.events != null ? oldNode_99417.events.length : 0) == 0));				}			if (Tmp1) {
			F.line = 319;
			mergeEvents_99035(newNode_99416, oldNode_99417, kxi_99420);
			}
			
				if ((oldNode_99417.kind == 102)) Tmp2 = true; else {					Tmp2 = (oldNode_99417.kind == 108);				}			if (Tmp2) {
			if (!((oldNode_99417.text == newNode_99416.text))) {
			F.line = 322;
			oldNode_99417.text = newNode_99416.text;
			F.line = 323;
			oldNode_99417.dom.value = newNode_99416.text;
			}
			
			}
			
			F.line = 325;
			var newLength_99641 = len_83849(newNode_99416);
			F.line = 326;
			var oldLength_99642 = len_83849(oldNode_99417);
			if (((newLength_99641 == 0) && (oldLength_99642 == 0))) {
			F.line = 327;
			break BeforeRet;
			}
			
			F.line = 328;
			var minLength_99643 = nimMin(newLength_99641, oldLength_99642);
			if (!((oldNode_99417.kind == newNode_99416.kind))) {
			F.line = 330;
			failedAssertImpl_50039(makeNimstrLit("oldNode.kind == newNode.kind "));
			}
			
			F.line = 331;
			var commonPrefix_99801 = 0;
			F.line = 332;
			if ((oldNode_99417.kind == 5)) Tmp4 = true; else {				Tmp4 = (oldNode_99417.kind == 3);			}			if (Tmp4) Tmp3 = true; else {				Tmp3 = (oldNode_99417.kind == 4);			}			var isSpecial_99829 = Tmp3;
			L5: do {
				F.line = 361;
					L6: while (true) {
					if (!(commonPrefix_99801 < minLength_99643)) break L6;
						F.line = 337;
						var oldLen_99861 = kxi_99420.patchLen;
						F.line = 338;
						var oldLenV_99863 = kxi_99420.patchLenV;
						if (!((commonPrefix_99801 < len_83849(newNode_99416)))) {
						F.line = 339;
						failedAssertImpl_50039(makeNimstrLit("commonPrefix < len(newNode) "));
						}
						
						if (!((commonPrefix_99801 < len_83849(oldNode_99417)))) {
						F.line = 340;
						failedAssertImpl_50039(makeNimstrLit("commonPrefix < len(oldNode) "));
						}
						
						F.line = 341;
						if (isSpecial_99829) {
						Tmp7 = diff_99414(X5BX5D__83860(newNode_99416, commonPrefix_99801), X5BX5D__83860(oldNode_99417, commonPrefix_99801), parent_99418, current_99419, kxi_99420);
						}
						else {
						Tmp7 = diff_99414(X5BX5D__83860(newNode_99416, commonPrefix_99801), X5BX5D__83860(oldNode_99417, commonPrefix_99801), current_99419, current_99419.childNodes[chckIndx(commonPrefix_99801, 0, current_99419.childNodes.length-1)-0], kxi_99420);
						}
						
						var r_100202 = Tmp7;
						F.line = 362;
						switch (r_100202) {
						case 3:
						case 0:
						case 2:
							F.line = 347;
							X5BX5Deq__83865(newNode_99416, commonPrefix_99801, X5BX5D__83860(oldNode_99417, commonPrefix_99801));
							F.line = 363;
							commonPrefix_99801 = addInt(commonPrefix_99801, 1);
							break;
						case 4:
							F.line = 350;
							addPatchV_99172(kxi_99420, oldNode_99417, commonPrefix_99801, X5BX5D__83860(newNode_99416, commonPrefix_99801));
							F.line = 363;
							commonPrefix_99801 = addInt(commonPrefix_99801, 1);
							F.line = 353;
							result_99421 = 4;
							break;
						case 1:
							F.line = 356;
							kxi_99420.patchLen = oldLen_99861;
							F.line = 357;
							kxi_99420.patchLenV = oldLenV_99863;
							if (!((result_99421 == 1))) {
							F.line = 358;
							result_99421 = r_100202;
							}
							
							F.line = 359;
							break L5;
							break;
						}
					}
			} while(false);
			F.line = 366;
			var oldPos_100229 = subInt(oldLength_99642, 1);
			F.line = 367;
			var newPos_100230 = subInt(newLength_99641, 1);
			L8: do {
				F.line = 368;
					L9: while (true) {
						if (!(commonPrefix_99801 <= oldPos_100229)) Tmp10 = false; else {							Tmp10 = (commonPrefix_99801 <= newPos_100230);						}					if (!Tmp10) break L9;
						F.line = 337;
						var oldLen_100238 = kxi_99420.patchLen;
						F.line = 338;
						var oldLenV_100240 = kxi_99420.patchLenV;
						if (!((newPos_100230 < len_83849(newNode_99416)))) {
						F.line = 339;
						failedAssertImpl_50039(makeNimstrLit("newPos < len(newNode) "));
						}
						
						if (!((oldPos_100229 < len_83849(oldNode_99417)))) {
						F.line = 340;
						failedAssertImpl_50039(makeNimstrLit("oldPos < len(oldNode) "));
						}
						
						F.line = 341;
						if (isSpecial_99829) {
						Tmp11 = diff_99414(X5BX5D__83860(newNode_99416, newPos_100230), X5BX5D__83860(oldNode_99417, oldPos_100229), parent_99418, current_99419, kxi_99420);
						}
						else {
						Tmp11 = diff_99414(X5BX5D__83860(newNode_99416, newPos_100230), X5BX5D__83860(oldNode_99417, oldPos_100229), current_99419, current_99419.childNodes[chckIndx(oldPos_100229, 0, current_99419.childNodes.length-1)-0], kxi_99420);
						}
						
						var r_100602 = Tmp11;
						F.line = 369;
						switch (r_100602) {
						case 3:
						case 0:
						case 2:
							F.line = 347;
							X5BX5Deq__83865(newNode_99416, newPos_100230, X5BX5D__83860(oldNode_99417, oldPos_100229));
							F.line = 370;
							oldPos_100229 = subInt(oldPos_100229, 1);
							F.line = 371;
							newPos_100230 = subInt(newPos_100230, 1);
							break;
						case 4:
							F.line = 350;
							addPatchV_99172(kxi_99420, oldNode_99417, oldPos_100229, X5BX5D__83860(newNode_99416, newPos_100230));
							F.line = 370;
							oldPos_100229 = subInt(oldPos_100229, 1);
							F.line = 371;
							newPos_100230 = subInt(newPos_100230, 1);
							F.line = 353;
							result_99421 = 4;
							break;
						case 1:
							F.line = 356;
							kxi_99420.patchLen = oldLen_100238;
							F.line = 357;
							kxi_99420.patchLenV = oldLenV_100240;
							if (!((result_99421 == 1))) {
							F.line = 358;
							result_99421 = r_100602;
							}
							
							F.line = 359;
							break L8;
							break;
						}
					}
			} while(false);
			F.line = 373;
			var pos_100647 = addInt(nimMin(oldPos_100229, newPos_100230), 1);
			L12: do {
				F.line = 375;
				var i_100657 = 0;
				F.line = 1973;
				var colontmp__101404 = 0;
				F.line = 375;
				colontmp__101404 = subInt(pos_100647, 1);
				F.line = 1955;
				var res_101407 = commonPrefix_99801;
				L13: do {
					F.line = 1956;
						L14: while (true) {
						if (!(res_101407 <= colontmp__101404)) break L14;
							F.line = 1957;
							i_100657 = res_101407;
							F.line = 376;
							var r_100658 = diff_99414(X5BX5D__83860(newNode_99416, i_100657), X5BX5D__83860(oldNode_99417, i_100657), current_99419, current_99419.childNodes[chckIndx(i_100657, 0, current_99419.childNodes.length-1)-0], kxi_99420);
							if ((r_100658 == 4)) {
							F.line = 379;
							addPatchV_99172(kxi_99420, oldNode_99417, i_100657, X5BX5D__83860(newNode_99416, i_100657));
							}
							else {
							if (!((r_100658 == 1))) {
							F.line = 381;
							X5BX5Deq__83865(newNode_99416, i_100657, X5BX5D__83860(oldNode_99417, i_100657));
							}
							}
							F.line = 1976;
							res_101407 = addInt(res_101407, 1);
						}
				} while(false);
			} while(false);
			if ((addInt(oldPos_100229, 1) == oldLength_99642)) {
			L15: do {
				F.line = 386;
				var i_100684 = 0;
				F.line = 1955;
				var res_101414 = pos_100647;
				L16: do {
					F.line = 1956;
						L17: while (true) {
						if (!(res_101414 <= newPos_100230)) break L17;
							F.line = 1957;
							i_100684 = res_101414;
							F.line = 387;
							addPatch_99137(kxi_99420, 2, current_99419, null, X5BX5D__83860(newNode_99416, i_100684));
							F.line = 388;
							result_99421 = 4;
							F.line = 1976;
							res_101414 = addInt(res_101414, 1);
						}
				} while(false);
			} while(false);
			}
			else {
				F.line = 390;
				var before_100685 = current_99419.childNodes[chckIndx(addInt(oldPos_100229, 1), 0, current_99419.childNodes.length-1)-0];
				L18: do {
					F.line = 391;
					var i_100695 = 0;
					F.line = 1955;
					var res_101421 = pos_100647;
					L19: do {
						F.line = 1956;
							L20: while (true) {
							if (!(res_101421 <= newPos_100230)) break L20;
								F.line = 1957;
								i_100695 = res_101421;
								F.line = 392;
								addPatch_99137(kxi_99420, 3, current_99419, before_100685, X5BX5D__83860(newNode_99416, i_100695));
								F.line = 393;
								result_99421 = 4;
								F.line = 1976;
								res_101421 = addInt(res_101421, 1);
							}
					} while(false);
				} while(false);
			}
			
			L21: do {
				F.line = 395;
				var i_100705 = 0;
				F.line = 1955;
				var res_101428 = pos_100647;
				L22: do {
					F.line = 1956;
						L23: while (true) {
						if (!(res_101428 <= oldPos_100229)) break L23;
							F.line = 1957;
							i_100705 = res_101428;
							F.line = 396;
							addPatch_99137(kxi_98083[0], 4, null, null, X5BX5D__83860(oldNode_99417, i_100705));
							F.line = 398;
							addPatch_99137(kxi_99420, 1, current_99419, current_99419.childNodes[chckIndx(i_100705, 0, current_99419.childNodes.length-1)-0], null);
							F.line = 399;
							result_99421 = 4;
							F.line = 1976;
							res_101428 = addInt(res_101428, 1);
						}
				} while(false);
			} while(false);
			break;
		case 0:
			if (!((oldNode_99417.kind == 5))) {
			F.line = 402;
			failedAssertImpl_50039(makeNimstrLit("oldNode.kind == component "));
			}
			
			F.line = 403;
			var x_100801 = oldNode_99417;
			F.line = 404;
			x_100801.updatedImpl(x_100801, newNode_99416);
			F.line = 405;
			var oldExpanded_100802 = x_100801.expanded;
			F.line = 406;
			x_100801.expanded = x_100801.renderImpl(x_100801);
			F.line = 407;
			x_100801.renderedVersion = x_100801.version;
			if ((oldExpanded_100802 == null)) {
			F.line = 409;
			addPatch_99137(kxi_98083[0], 4, null, null, oldNode_99417);
			F.line = 410;
			addPatch_99137(kxi_99420, 0, parent_99418, current_99419, x_100801.expanded);
			}
			else {
				F.line = 412;
				var res_100814 = diff_99414(x_100801.expanded, oldExpanded_100802, parent_99418, current_99419, kxi_99420);
				if ((res_100814 == 4)) {
				}
				else {
				if (!((res_100814 == 1))) {
				F.line = 417;
				x_100801.expanded = oldExpanded_100802;
				if (!(!((oldExpanded_100802.dom == null)))) {
				F.line = 418;
				failedAssertImpl_50039(makeNimstrLit("\x0A  not (oldExpanded.dom == nil) old expanded.dom is nil"));
				}
				
				}
				else {
					if (!(!((x_100801.expanded.dom == null)))) {
					F.line = 420;
					failedAssertImpl_50039(makeNimstrLit("\x0A  not (x.expanded.dom == nil) expanded.dom is nil"));
					}
					
				}
				}
			}
			
			break;
		case 1:
			F.line = 422;
			addPatch_99137(kxi_98083[0], 4, null, null, oldNode_99417);
			F.line = 423;
			addPatch_99137(kxi_99420, 0, parent_99418, current_99419, newNode_99416);
			break;
		case 4:
			if (true) {
			F.line = 424;
			raiseAssert_50016(makeNimstrLit("false eq returned usenewNode"));
			}
			
			break;
		}
	} while (false);
	framePtr = F.prev;

	return result_99421;

}

function apply_99206(kxi_99208) {
	var F={procname:"karax.apply",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		L1: do {
			F.line = 274;
			var i_99218 = 0;
			F.line = 3812;
			var colontmp__99402 = 0;
			F.line = 274;
			colontmp__99402 = kxi_99208.patchLen;
			F.line = 3813;
			var i_99405 = 0;
			L2: do {
				F.line = 3814;
					L3: while (true) {
					if (!(i_99405 < colontmp__99402)) break L3;
						F.line = 3815;
						i_99218 = i_99405;
						F.line = 275;
						var p_99219 = nimCopy(null, kxi_99208.patches[chckIndx(i_99218, 0, kxi_99208.patches.length-1)-0], NTI98024);
						F.line = 276;
						switch (p_99219.k) {
						case 0:
							F.line = 278;
							var nn_99220 = vnodeToDom_98234(p_99219.n, kxi_99208);
							if ((p_99219.parent == null)) {
							F.line = 280;
							replaceById_98720(kxi_99208.rootId, nn_99220);
							}
							else {
								F.line = 282;
							p_99219.parent.replaceChild(nn_99220, p_99219.current);
							}
							
							break;
						case 1:
							F.line = 284;
							p_99219.parent.removeChild(p_99219.current);
							break;
						case 2:
							F.line = 286;
							var nn_99232 = vnodeToDom_98234(p_99219.n, kxi_99208);
							F.line = 287;
							p_99219.parent.appendChild(nn_99232);
							break;
						case 3:
							F.line = 289;
							var nn_99233 = vnodeToDom_98234(p_99219.n, kxi_99208);
							F.line = 290;
							p_99219.parent.insertBefore(nn_99233, p_99219.current);
							break;
						case 4:
							F.line = 292;
							var n_99234 = p_99219.n;
							if ((n_99234.kind == 5)) {
							F.line = 294;
							var x_99244 = n_99234;
							if (!((x_99244.onDetachImpl == null))) {
							F.line = 295;
							x_99244.onDetachImpl(x_99244);
							}
							
							}
							
							F.line = 296;
							n_99234.dom = null;
							break;
						}
						F.line = 3816;
						i_99405 = addInt(i_99405, 1);
					}
			} while(false);
		} while(false);
		F.line = 297;
		kxi_99208.patchLen = 0;
		L4: do {
			F.line = 298;
			var i_99262 = 0;
			F.line = 3812;
			var colontmp__99408 = 0;
			F.line = 298;
			colontmp__99408 = kxi_99208.patchLenV;
			F.line = 3813;
			var i_99411 = 0;
			L5: do {
				F.line = 3814;
					L6: while (true) {
					if (!(i_99411 < colontmp__99408)) break L6;
						F.line = 3815;
						i_99262 = i_99411;
						F.line = 299;
						var p_99263 = nimCopy(null, kxi_99208.patchesV[chckIndx(i_99262, 0, kxi_99208.patchesV.length-1)-0], NTI98026);
						F.line = 300;
						X5BX5Deq__83865(p_99263.parent, p_99263.pos, p_99263.newChild);
						if (!(!((p_99263.newChild.dom == null)))) {
						F.line = 301;
						failedAssertImpl_50039(makeNimstrLit("\x0A  not (p.newChild.dom == nil) "));
						}
						
						F.line = 3816;
						i_99411 = addInt(i_99411, 1);
					}
			} while(false);
		} while(false);
		F.line = 302;
		kxi_99208.patchLenV = 0;
	framePtr = F.prev;

	
}

function dodraw_101601(kxi_101603) {
	var F={procname:"karax.dodraw",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
	BeforeRet: do {
		if ((kxi_101603.renderer === null)) {
		F.line = 437;
		break BeforeRet;
		}
		
		F.line = 438;
		var newtree_101610 = kxi_101603.renderer();
		F.line = 439;
		kxi_101603.runCount = addInt(kxi_101603.runCount, 1);
		F.line = 440;
		newtree_101610.id = kxi_101603.rootId;
		F.line = 441;
		kxi_101603.toFocus = null;
		if ((kxi_101603.currentTree == null)) {
		F.line = 443;
		kxi_101603.currentTree = newtree_101610;
		F.line = 444;
		var asdom_101631 = vnodeToDom_98234(kxi_101603.currentTree, kxi_101603);
		F.line = 445;
		replaceById_98720(kxi_101603.rootId, asdom_101631);
		}
		else {
			if (!(same_98650(kxi_101603.currentTree, document.getElementById(kxi_101603.rootId), 0))) {
			F.line = 447;
			raiseAssert_50016(makeNimstrLit("same(kxi.currentTree, getElementById(document, kxi.rootId), 0) "));
			}
			
			F.line = 448;
			var olddom_101632 = document.getElementById(kxi_101603.rootId);
			F.line = 449;
			diff_99414(newtree_101610, kxi_101603.currentTree, null, olddom_101632, kxi_101603);
			F.line = 451;
			apply_99206(kxi_101603);
			F.line = 452;
			kxi_101603.currentTree = newtree_101610;
		}
		
		if (!(same_98650(kxi_101603.currentTree, document.getElementById(kxi_101603.rootId), 0))) {
		F.line = 453;
		raiseAssert_50016(makeNimstrLit("same(kxi.currentTree, getElementById(document, kxi.rootId), 0) "));
		}
		
		if (!((kxi_101603.postRenderCallback === null))) {
		F.line = 456;
		kxi_101603.postRenderCallback();
		}
		
		if (!((kxi_101603.toFocus == null))) {
		F.line = 460;
		kxi_101603.toFocus.focus();
		}
		
		F.line = 461;
		kxi_101603.renderId = 0;
	} while (false);
	framePtr = F.prev;

	
}

function init_102007(ev_102009) {

		function colonanonymous__102010() {
			var F={procname:"init.:anonymous",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
			framePtr = F;
				F.line = 485;
				dodraw_101601(kxi_98083[0]);
			framePtr = F.prev;

			
		}

	var F={procname:"karax.init",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		F.line = 485;
		kxi_98083[0].renderId = window.requestAnimationFrame(colonanonymous__102010);
	framePtr = F.prev;

	
}

function setRenderer_102013(renderer_102017, root_102018, clientPostRenderCallback_102021) {
	var result_102022 = null;

	var F={procname:"karax.setRenderer",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/karax.nim",line:0};
	framePtr = F;
		F.line = 490;
		result_102022 = {rootId: root_102018, renderer: nimCopy(null, renderer_102017, NTI102015), postRenderCallback: nimCopy(null, clientPostRenderCallback_102021, NTI102019), patches: newSeq_102037(60), patchesV: newSeq_102076(30), currentTree: null, toFocus: null, toFocusV: null, renderId: 0, patchLen: 0, patchLenV: 0, runCount: 0};
		F.line = 494;
		kxi_98083[0] = result_102022;
		F.line = 495;
		window.onload = init_102007;
	framePtr = F.prev;

	return result_102022;

}

function newVNode_83884(kind_83886) {
	var result_83887 = null;

	var F={procname:"vdom.newVNode",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
		F.line = 206;
		result_83887 = {kind: kind_83886, key: -1, m_type: NTI83476, id: null, class: null, text: null, kids: null, attrs: null, events: null, style: null, dom: null};
	framePtr = F.prev;

	return result_83887;

}

function add_83870(parent_83872, kid_83873) {
	var F={procname:"vdom.add",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
		F.line = 205;
		if (parent_83872.kids != null) { parent_83872.kids.push(kid_83873); } else { parent_83872.kids = [kid_83873]; };
	framePtr = F.prev;

	
}

function tree_83889(kind_83891, kids_83893) {
	var result_83894 = null;

	var F={procname:"vdom.tree",prev:framePtr,filename:"/Users/zachcarter/.nimble/pkgs/karax-0.1.0/vdom.nim",line:0};
	framePtr = F;
		F.line = 209;
		result_83894 = newVNode_83884(kind_83891);
		L1: do {
			F.line = 210;
			var k_83919 = null;
			F.line = 2060;
			var i_83923 = 0;
			L2: do {
				F.line = 2061;
					L3: while (true) {
					if (!(i_83923 < (kids_83893 != null ? kids_83893.length : 0))) break L3;
						F.line = 2062;
						k_83919 = kids_83893[chckIndx(i_83923, 0, kids_83893.length-1)-0];
						F.line = 210;
						add_83870(result_83894, k_83919);
						F.line = 2063;
						i_83923 = addInt(i_83923, 1);
					}
			} while(false);
		} while(false);
	framePtr = F.prev;

	return result_83894;

}

function createDom_105001() {
	var result_105003 = null;

	var F={procname:"website.createDom",prev:framePtr,filename:"website.nim",line:0};
	framePtr = F;
		F.line = 3;
		F.line = 3;
		var tmp_105010 = tree_83889(42, []);
		F.line = 3;
		tmp_105010.class = "todomvc-wrapper";
		result_105003 = tmp_105010;
	framePtr = F.prev;

	return result_105003;

}
setRenderer_102013(createDom_105001, "ROOT", null);
